//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGStoryDataControllerStoryItemListener-Protocol.h"

@class MISSING_TYPE;

@interface _TtC39IGSundialInspirationHubAutoCreatedReels41IGSundialAutoCreatedReelsHighlightFetcher : NSObject <IGStoryDataControllerStoryItemListener>
{
    MISSING_TYPE *userSession;
    MISSING_TYPE *completion;
    MISSING_TYPE *requestedReelPK;
}

- (void).cxx_destruct;
- (id)init;
- (void)storyDataController:(id)arg1 fetchItemsDidFailForReelPK:(id)arg2 error:(id)arg3 refreshType:(long long)arg4 updateDuration:(double)arg5;
- (void)storyDataController:(id)arg1 didUpdateReel:(id)arg2 refreshType:(long long)arg3 updateDuration:(double)arg4;
- (void)storyDataController:(id)arg1 didReturnNoStoryItemResultsForReelPK:(id)arg2 refreshType:(long long)arg3 updateDuration:(double)arg4;

@end

