//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC22IGNftComposeNetworking25IGNftComposeCreatePostAPI : NSObject
{
    MISSING_TYPE *analyticsModule;
    MISSING_TYPE *userSession;
}

- (void).cxx_destruct;
- (id)init;
- (void)createPostForNftMediaMetadata:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)initWithAnalyticsModule:(id)arg1 userSession:(id)arg2;

@end

