//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC9IGHangout24IGHangoutRoomCoordinator.h"

#import "IGHangoutEntryPointHandling-Protocol.h"

@interface _TtC9IGHangout24IGHangoutRoomCoordinator (IGHangout) <IGHangoutEntryPointHandling>
- (void)generateHangoutViewControllerWithIdentifier:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
@end

