//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FBAACEncoderBase.h"

@interface AppleAudioEncoder : FBAACEncoderBase
{
    function_30f7e6d5 _writeEncodedData;
    function_4084f207 _fireError;
    function_77eca650 _audioEncoderBitrateChangedCallback;
    function_55c89946 _audioEncoderCodecChangedCallback;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onResumed;
- (void)onPaused;
- (void)onStopped;
- (void)onStarted;
- (void)writeEncodedData:(const char *)arg1 size:(unsigned long long)arg2 pts:(CDStruct_1b6d18a9)arg3 dts:(CDStruct_1b6d18a9)arg4 duration:(CDStruct_1b6d18a9)arg5;
- (void)writeDescription:(struct AudioStreamBasicDescription)arg1 pts:(CDStruct_1b6d18a9)arg2 dts:(CDStruct_1b6d18a9)arg3;
- (unsigned int)audioEncoderSelectedCodec:(unsigned int)arg1;
- (void)audioEncoderSelectedBitrate:(int)arg1;
- (void)encodeAudio:(struct opaqueCMSampleBuffer *)arg1;
- (id)initWithAudioConfig:(const struct AudioEncoderConfig *)arg1 nodeOptions:(const struct AppleAudioEncoderNodeOptions *)arg2 writeDataCallback:(function_30f7e6d5)arg3 errorCallback:(function_4084f207)arg4 audioEncoderBitrateChangedCallback:(function_77eca650)arg5 audioEncoderCodecChangedCallback:(function_55c89946)arg6;

@end

