//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BKBloksBasicAnimation_DEPRECATED.h"

@interface BKBloksDelayedAnimation_DEPRECATED : BKBloksBasicAnimation_DEPRECATED
{
    BKBloksBasicAnimation_DEPRECATED *_animation;
    double _delay;
    double _startTimestamp;
}

- (void).cxx_destruct;
- (void)run:(double)arg1;
- (void)reset;
- (id)initWithAnimation:(id)arg1 delay:(double)arg2;

@end

