//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface FBAddressBookContactPerson : NSObject
{
    NSMutableArray *_phoneValues;
    NSMutableArray *_emailValues;
    NSString *_name;
    NSString *_md5HashValue;
    NSMutableArray *_phoneObjects;
    NSMutableArray *_emailObjects;
    NSString *_recordID;
    NSString *_lastName;
    NSString *_middleName;
    NSString *_firstName;
    NSString *_modifier;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *modifier; // @synthesize modifier=_modifier;
@property(copy, nonatomic) NSArray *phoneObjects; // @synthesize phoneObjects=_phoneObjects;
@property(copy, nonatomic) NSArray *emailObjects; // @synthesize emailObjects=_emailObjects;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(copy, nonatomic) NSString *middleName; // @synthesize middleName=_middleName;
@property(copy, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(copy, nonatomic) NSString *recordID; // @synthesize recordID=_recordID;
@property(copy, nonatomic, getter=getMd5HashValue, setter=setMd5HashValue:) NSString *md5HashValue;
- (void)addEmail:(id)arg1 withLabel:(id)arg2;
- (void)addPhoneNumber:(id)arg1 withLabel:(id)arg2;
- (id)init;

@end

