//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBAutoupdaterReactService, FBAutoupdaterUpdate, NSString;

@protocol FBAutoupdaterReactServiceDelegate <NSObject>
- (void)autoupdaterReactServiceDidActivateResourceAfterLockingUpdate:(FBAutoupdaterReactService *)arg1;
- (void)autoupdaterReactService:(FBAutoupdaterReactService *)arg1 didRequestReactResource:(FBAutoupdaterUpdate *)arg2 lastActiveVersion:(NSString *)arg3;

@optional
- (_Bool)shouldForceRefreshNow;
- (void)showUpdateProcessInStatusBar:(NSString *)arg1;
- (NSString *)autoUpdaterServiceOverrideReleaseID;
@end

