//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBAutoupdaterBackgroundDownloaderDelegate-Protocol.h"
#import "FBAutoupdaterUnarchiverDelegate-Protocol.h"

@class FBAutoupdaterHost, FBAutoupdaterUpdate, NSArray, NSDateFormatter, NSFileManager, NSMutableArray, NSOperationQueue, NSProgress, NSString;
@protocol FBAutoupdaterCleaner, FBAutoupdaterDeltaUpdateApplier, FBAutoupdaterDownloader, FBAutoupdaterDriverDelegate, FBAutoupdaterDriverProgressDelegate, FBAutoupdaterInfoUpdater, FBAutoupdaterInstaller, FBAutoupdaterPreparer, FBAutoupdaterUnarchiver, FBAutoupdaterVerifier;

@interface FBAutoupdaterDriver : NSObject <FBAutoupdaterBackgroundDownloaderDelegate, FBAutoupdaterUnarchiverDelegate>
{
    NSArray *_cachedUpdates;
    NSFileManager *_fileManager;
    NSOperationQueue *_progressDelegateQueue;
    NSMutableArray *_processQueue;
    FBAutoupdaterUpdate *_updateBeingProcessed;
    _Bool _deltaProcessed;
    NSDateFormatter *_dateFormatter;
    _Bool _autoRemoveUnappliedUpdates;
    _Bool _applyUpdatesAfterInstall;
    id <FBAutoupdaterDriverDelegate> _delegate;
    id <FBAutoupdaterDriverProgressDelegate> _progressDelegate;
    id <FBAutoupdaterCleaner> _cleaner;
    id <FBAutoupdaterDownloader> _downloader;
    id <FBAutoupdaterUnarchiver> _unarchiver;
    id <FBAutoupdaterDeltaUpdateApplier> _deltaApplier;
    id <FBAutoupdaterPreparer> _preparer;
    id <FBAutoupdaterVerifier> _verifier;
    id <FBAutoupdaterInfoUpdater> _infoUpdater;
    id <FBAutoupdaterInstaller> _installer;
    FBAutoupdaterHost *_host;
    NSProgress *_progress;
    NSProgress *_currentOperationProgress;
    NSString *_downloadPath;
    NSString *_extractPath;
    NSString *_deltaUpdateToPath;
    NSString *_deltaUpdateFromPath;
    NSString *_installFromPath;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool applyUpdatesAfterInstall; // @synthesize applyUpdatesAfterInstall=_applyUpdatesAfterInstall;
@property(nonatomic) _Bool autoRemoveUnappliedUpdates; // @synthesize autoRemoveUnappliedUpdates=_autoRemoveUnappliedUpdates;
@property(copy, nonatomic) NSString *installFromPath; // @synthesize installFromPath=_installFromPath;
@property(copy, nonatomic) NSString *deltaUpdateFromPath; // @synthesize deltaUpdateFromPath=_deltaUpdateFromPath;
@property(copy, nonatomic) NSString *deltaUpdateToPath; // @synthesize deltaUpdateToPath=_deltaUpdateToPath;
@property(copy, nonatomic) NSString *extractPath; // @synthesize extractPath=_extractPath;
@property(copy, nonatomic) NSString *downloadPath; // @synthesize downloadPath=_downloadPath;
@property(retain, nonatomic) NSProgress *currentOperationProgress; // @synthesize currentOperationProgress=_currentOperationProgress;
@property(retain, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(retain, nonatomic) FBAutoupdaterUpdate *updateBeingProcessed; // @synthesize updateBeingProcessed=_updateBeingProcessed;
@property(retain, nonatomic) FBAutoupdaterHost *host; // @synthesize host=_host;
@property(retain, nonatomic) id <FBAutoupdaterInstaller> installer; // @synthesize installer=_installer;
@property(retain, nonatomic) id <FBAutoupdaterInfoUpdater> infoUpdater; // @synthesize infoUpdater=_infoUpdater;
@property(retain, nonatomic) id <FBAutoupdaterVerifier> verifier; // @synthesize verifier=_verifier;
@property(retain, nonatomic) id <FBAutoupdaterPreparer> preparer; // @synthesize preparer=_preparer;
@property(retain, nonatomic) id <FBAutoupdaterDeltaUpdateApplier> deltaApplier; // @synthesize deltaApplier=_deltaApplier;
@property(retain, nonatomic) id <FBAutoupdaterUnarchiver> unarchiver; // @synthesize unarchiver=_unarchiver;
@property(retain, nonatomic) id <FBAutoupdaterDownloader> downloader; // @synthesize downloader=_downloader;
@property(retain, nonatomic) id <FBAutoupdaterCleaner> cleaner; // @synthesize cleaner=_cleaner;
@property(nonatomic) __weak id <FBAutoupdaterDriverProgressDelegate> progressDelegate; // @synthesize progressDelegate=_progressDelegate;
@property(nonatomic) __weak id <FBAutoupdaterDriverDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)_createPathIfNeeded:(id)arg1 error:(id *)arg2;
- (id)_generateTemporaryPath:(id)arg1;
- (id)_generateAppliedDeltaUpdatePath;
- (id)_generateExtractPath;
- (id)_generateDownloadPath;
- (void)autoupdaterUnarchiver:(id)arg1 update:(id)arg2 didFail:(id)arg3;
- (void)autoupdaterUnarchiver:(id)arg1 didFinishUpdate:(id)arg2;
- (_Bool)autoupdaterUnarchiver:(id)arg1 update:(id)arg2 shouldUnarchiveFile:(id)arg3 toPath:(id)arg4 crc32:(unsigned long long)arg5;
- (void)autoupdaterUnarchiver:(id)arg1 update:(id)arg2 didMakeProgress:(id)arg3;
- (void)autoupdaterUnarchiver:(id)arg1 didStartUpdate:(id)arg2;
- (_Bool)autoupdaterBackgroundDownloader:(id)arg1 allowCellularAccessForDownloadingUpdate:(id)arg2;
- (void)autoupdaterBackgroundDownloader:(id)arg1 didFinishEventsForIdentifier:(id)arg2;
- (void)autoupdaterDownloader:(id)arg1 update:(id)arg2 didFail:(id)arg3;
- (void)autoupdaterDownloader:(id)arg1 didFinishUpdate:(id)arg2;
- (void)autoupdaterDownloader:(id)arg1 update:(id)arg2 didMakeProgress:(id)arg3;
- (void)autoupdaterDownloader:(id)arg1 didStartUpdate:(id)arg2 expectedLength:(long long)arg3;
- (void)_finishUpdate:(id)arg1;
- (void)_completeUpdateProcessing:(id)arg1;
- (_Bool)_runInstallerForUpdate:(id)arg1;
- (_Bool)_runInfoUpdaterForUpdate:(id)arg1;
- (_Bool)_runVerifierForUpdate:(id)arg1;
- (_Bool)_runPreparerForUpdate:(id)arg1;
- (_Bool)_runDeltaApplierForUpdate:(id)arg1;
- (void)_processUnarchivedUpdate:(id)arg1;
- (void)retryWithFullUpdateIfNeeded:(id)arg1;
- (void)_unarchiveUpdate:(id)arg1;
- (void)_downloadUpdate:(id)arg1;
- (void)_failUpdate:(id)arg1 error:(id)arg2;
- (void)_failUpdate:(id)arg1 withMessage:(id)arg2;
- (void)_processNextUpdateInformationFromQueue;
- (void)_enqueueUpdateForProcessing:(id)arg1;
- (_Bool)_shouldProcessUpdate:(id)arg1;
- (void)_updateProgress:(id)arg1 forStage:(int)arg2;
- (_Bool)_unexpectedUpdate:(id)arg1;
- (id)_sessionIdentifier;
- (id)relativePathFrom:(id)arg1 toPath:(id)arg2;
- (void)generatingPathForUpdate:(id)arg1;
- (void)removeAllInactiveUpdatesAndResetActiveUpdate;
- (void)_unapplyAppliedUpdate;
- (_Bool)applyUpdate:(id)arg1 error:(id *)arg2;
- (void)cancelUpdate;
- (void)processUpdateInformation:(id)arg1;
- (id)initWithDelegate:(id)arg1 progressDelegate:(id)arg2 delegateQueue:(id)arg3 host:(id)arg4 cleaner:(id)arg5 downloader:(id)arg6 unarchiver:(id)arg7 deltaApplier:(id)arg8 preparer:(id)arg9 verifier:(id)arg10 infoUpdater:(id)arg11 installer:(id)arg12;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

