//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBCAFClientStateUpdateResponse, FBCAFConnectionStatusChangeResponse, FBCAFEntityResponse, FBCAFEntityUpdateResponse, FBCAFErrorResponse, FBCAFPresenceUpdateResponse, FBCAFSessionResponse, NSString;

@protocol FBCAFResponseHandling <NSObject>
- (void)handleSameCursorUpdateReceived:(NSString *)arg1;
- (void)handleOutOfOrderUpdateReceivedWith:(NSString *)arg1 newCursor:(NSString *)arg2;
- (void)handlePresenceUpdate:(FBCAFPresenceUpdateResponse *)arg1;
- (void)handleClientStateUpdate:(FBCAFClientStateUpdateResponse *)arg1;
- (void)handleEntityUpdate:(FBCAFEntityUpdateResponse *)arg1;
- (void)handleConnectionStatusChange:(FBCAFConnectionStatusChangeResponse *)arg1;
- (void)handleError:(FBCAFErrorResponse *)arg1;
- (void)handleSession:(FBCAFSessionResponse *)arg1;
- (void)handleEntity:(FBCAFEntityResponse *)arg1;
@end

