//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBPayComponentConforming-Protocol.h"
#import "FBPayComponentFormViewControllerDelegate-Protocol.h"
#import "FBPayComponentShippingAddressSelectionViewControllerDelegate-Protocol.h"

@class FBPayComponentInlineCell, FBPayComponentInlineCellViewModel, FBPayExpressCheckoutContext, FBPayExpressCheckoutErrorHandler, FBPayExpressCheckoutLogger, FBPayExpressCheckoutPaymentRequest, FBPayFormFieldsForCountry, FBPayShippingAddressComponentResponse, FBPaymentsShippingAddress, NSArray, NSString;
@protocol FBPayComponentCellResizingDelegate, FBPayShippingAddressComponentDelegate;

@interface FBPayShippingAddressComponent : NSObject <FBPayComponentShippingAddressSelectionViewControllerDelegate, FBPayComponentFormViewControllerDelegate, FBPayComponentConforming>
{
    FBPayExpressCheckoutPaymentRequest *_paymentRequest;
    FBPayExpressCheckoutContext *_ecpContext;
    FBPayComponentInlineCellViewModel *_inlineCellViewModel;
    FBPayComponentInlineCell *_inlineCell;
    FBPayShippingAddressComponentResponse *_shippingAddressComponentDataResponse;
    long long _componentResponseDataSourceType;
    FBPayExpressCheckoutLogger *_logger;
    _Bool _didAlreadyLogInitialLoad;
    FBPaymentsShippingAddress *_selectedShippingAddress;
    NSArray *_allAvailableShippingAddresses;
    FBPayFormFieldsForCountry *_shippingAddressFormFields;
    _Bool _isUserInteractionEnabled;
    id <FBPayComponentCellResizingDelegate> _cellResizingDelegate;
    FBPayExpressCheckoutErrorHandler *_errorHandler;
    id <FBPayShippingAddressComponentDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <FBPayShippingAddressComponentDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) FBPayExpressCheckoutErrorHandler *errorHandler; // @synthesize errorHandler=_errorHandler;
@property(nonatomic) __weak id <FBPayComponentCellResizingDelegate> cellResizingDelegate; // @synthesize cellResizingDelegate=_cellResizingDelegate;
- (void)fbpayComponentFormViewController:(id)arg1 didHaveComponentDataMutatingRequest:(id)arg2 mutatingCallback:(CDUnknownBlockType)arg3;
- (void)shippingAddressSelectionViewController:(id)arg1 didNeedToPerformMutationWithRequest:(id)arg2 mutatingCallback:(CDUnknownBlockType)arg3;
- (void)shippingAddressSelectionViewController:(id)arg1 didSelectNewShippingAddress:(id)arg2 updatedAllShippingAddresses:(id)arg3;
- (id)provideComponentSelectionOrFormViewController;
- (void)setUserInteractionEnabled:(_Bool)arg1;
- (void)updateWithPaymentRequest:(id)arg1;
- (void)initiateComponentDataFetchFromTriggeringSource:(long long)arg1;
- (id)formConfigurationForNUX:(id)arg1;
- (id)componentCellForPUX;
- (long long)componentType;
- (void)_logAddShippingAddressMutationSuccess:(id)arg1;
- (void)_logComponentClicked;
- (void)_logComponentInitialLoadDidSucceed:(_Bool)arg1 shippingAddress:(id)arg2;
- (void)_logComponentInit;
- (void)_handleComponentMutatinRequest:(CDUnknownBlockType)arg1 mutatingRequest:(id)arg2;
- (void)_notifyNewShippingAddress:(_Bool)arg1;
- (void)_updateCellWithInlineCellViewModel:(id)arg1;
- (void)_handleComponentInlineModelUpdates;
- (void)_updateComponentWithDelta:(_Bool)arg1 isDataFromNetwork:(_Bool)arg2;
- (void)_handleComponentDataResponse:(id)arg1;
- (_Bool)_hasDataDifference:(id)arg1;
- (void)_setAddress:(id)arg1;
- (id)getFormFieldsForCountry;
- (id)initWithPaymentRequest:(id)arg1 ecpContext:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

