//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBPaySecurityDynamicAuthenticating-Protocol.h"

@class FBPayAuthenticationContext, NSString;
@protocol FBPayDynamicAutheticationProcedure, FBPaySecurityStaticAuthenticating;

@interface FBPayDynamicAuthenticationFlowManager : NSObject <FBPaySecurityDynamicAuthenticating>
{
    FBPayAuthenticationContext *_managerContext;
    id <FBPaySecurityStaticAuthenticating> _staticAuthenticationManager;
    id <FBPayDynamicAutheticationProcedure> _currentProcedure;
}

- (void).cxx_destruct;
- (void)perfomDynamicAuthenticationProcedure:(id)arg1 presenterController:(id)arg2 authenticationError:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)perfomDynamicAuthenticationProcedure:(id)arg1 presenterController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithContext:(id)arg1 staticAuth:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

