//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface FBPrivacyUIIScanner : NSObject
{
    CDUnknownBlockType _callback;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    NSObject<OS_dispatch_queue> *_scannerQueue;
}

+ (id)newWithHeuristicTypes:(unsigned long long)arg1 callbackQueue:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
- (void)runWithURL:(id)arg1 source:(id)arg2 skippedParams:(id)arg3 sourceStackTrace:(id)arg4;
- (id)initWithHeuristicTypes:(unsigned long long)arg1 callbackQueue:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (id)init;

@end

