//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class FBSDKWebDialog, NSDictionary, NSError;

@protocol FBSDKWebDialogDelegate
- (void)webDialogDidCancel:(FBSDKWebDialog *)arg1;
- (void)webDialog:(FBSDKWebDialog *)arg1 didFailWithError:(NSError *)arg2;
- (void)webDialog:(FBSDKWebDialog *)arg1 didCompleteWithResults:(NSDictionary *)arg2;
@end

