//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ACSStorageManager-Protocol.h"

@class NSMutableArray, NSString;
@protocol FBStash;

@interface IABPCMACSStorageManager : NSObject <ACSStorageManager>
{
    id <FBStash> _stash;
    NSMutableArray *_serverConfigs;
    NSMutableArray *_cachedTokens;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <FBStash> stash; // @synthesize stash=_stash;
- (void)_updateStashforKey:(id)arg1 withData:(id)arg2;
- (_Bool)areCachedTokensValid;
- (void)removeServerConfigWithId:(id)arg1;
- (void)storeServerConfig:(id)arg1;
- (id)getServerConfigs;
- (id)getServerConfigWithId:(id)arg1;
- (void)deleteCachedToken:(id)arg1;
- (void)storeCachedToken:(id)arg1;
- (id)getCachedTokenWithServerConfigId:(id)arg1;
- (void)dealloc;
- (id)initWithStash:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

