//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "IGGestureHandler-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class IGBottomButtonsView, IGTableLayoutSpec, NSArray, NSMutableSet, NSString, UIButton, UILabel, UITableView;
@protocol IGActivityFiltersViewControllerDelegate;

@interface IGActivityFiltersViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, IGGestureHandler>
{
    NSArray *_filterSections;
    NSMutableSet *_selectedFilterIDs;
    UILabel *_titleLabel;
    UIButton *_clearButton;
    UITableView *_tableView;
    IGTableLayoutSpec *_layoutSpec;
    IGBottomButtonsView *_bottomButton;
    id <IGActivityFiltersViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGActivityFiltersViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)canRespondToGesture:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)_clearButtonTapped;
- (void)_applyButtonTapped;
- (void)_updateClearButton;
- (struct CGSize)_preferredSize;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithFilterSections:(id)arg1 selectedFilterIDs:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

