//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IGAccountLocationTransparencyRowViewDelegate-Protocol.h"
#import "IGAccountLocationTransparencyViewProtocol-Protocol.h"
#import "IGContextSheetHeaderViewDelegate-Protocol.h"

@class IGAccountLocationTransparencyRowView, IGAccountLocationTransparencyViewLayoutSpec, IGButton, IGContextSheetHeaderView, NSString;
@protocol IGAccountLocationTransparencyViewDelegate;

@interface IGAccountLocationTransparencyViewV2 : UIView <IGAccountLocationTransparencyRowViewDelegate, IGContextSheetHeaderViewDelegate, IGAccountLocationTransparencyViewProtocol>
{
    IGContextSheetHeaderView *_headerView;
    UIView *_transparencyContainerView;
    IGAccountLocationTransparencyRowView *_scmeView;
    IGAccountLocationTransparencyRowView *_locationTransparencyView;
    UIView *_aboutThisAccountContainerView;
    IGButton *_aboutThisAccountButton;
    IGAccountLocationTransparencyViewLayoutSpec *_layoutSpec;
    id <IGAccountLocationTransparencyViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGAccountLocationTransparencyViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_onAboutThisAccountTapped:(id)arg1;
- (void)accountLocationTransparencyRowView:(id)arg1 didTapLinkWithURL:(id)arg2;
- (void)contextSheetHeaderViewDidPressFollowButton;
- (void)contextSheetHeaderViewDidPressTertiaryTitleLabel:(id)arg1;
- (void)contextSheetHeaderViewDidPressSubtitleLabel:(id)arg1;
- (void)contextSheetHeaderViewDidPressTitleLabel:(id)arg1;
- (void)contextSheetHeaderViewDidPressImage:(id)arg1 profilePictureImageView:(id)arg2;
- (void)contextSheetHeaderViewDidPressView:(id)arg1;
- (void)spinOnceAndConfigureToRingSpec:(id)arg1;
- (void)_configureLocationTransparencyView:(id)arg1;
- (void)_configureSCMEView:(id)arg1;
- (void)configureWithViewModel:(id)arg1 layoutSpec:(id)arg2 analyticsModule:(id)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

