//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/BKBloksComponentController.h>

#import "IGInsightsLineChartViewDelegate-Protocol.h"

@class IGInsightsLineChartView, NSNumber, NSString;

@interface IGBloksChartComponentController : BKBloksComponentController <IGInsightsLineChartViewDelegate>
{
    IGInsightsLineChartView *_lineChartView;
    NSNumber *_currentSelectedXTickMarkIndex;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *currentSelectedXTickMarkIndex; // @synthesize currentSelectedXTickMarkIndex=_currentSelectedXTickMarkIndex;
@property(readonly, nonatomic) IGInsightsLineChartView *lineChartView; // @synthesize lineChartView=_lineChartView;
- (void)_configureWithModel;
- (void)componentDidAcquireView:(id)arg1;
- (void)componentDidAcquireView:(id)arg1 withModel:(id)arg2 context:(id)arg3;
- (void)chartView:(id)arg1 didSelectDataPointAtIndex:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

