//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BKContext, BKLispyExpression, BKModel, BKObjectSet, IGBloksVideoComponentController, IGPhoto, IGVideo, NSString, NSURL;

@protocol IGBloksVideoComponentControllerDataProvider <NSObject>
- (void)registerComponentController:(IGBloksVideoComponentController *)arg1 toContext:(BKContext *)arg2;
- (BKLispyExpression *)onStateUpdateForObjectSet:(BKObjectSet *)arg1;
- (BKLispyExpression *)onProgressUpdateForObjectSet:(BKObjectSet *)arg1;
- (IGVideo *)video;
- (IGPhoto *)coverPhoto;
- (NSURL *)subtitleURL;
- (NSString *)analyticsModule;
- (_Bool)shouldShowAudioIndicator;
- (_Bool)hasAudio;
- (_Bool)shouldShowCaptions;
- (_Bool)timeIndicatorEnabled;
- (_Bool)tapToToggleVideoAudioEnabled;
- (_Bool)shouldLoop;
- (_Bool)shouldAutoPlay;
- (BKModel *)model;
@end

