//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGBrandedContentPartnersViewControllerDelegate-Protocol.h"
#import "IGBrandedContentViolationConfirmationViewControllerDelegate-Protocol.h"
#import "IGGenericMegaphoneViewV2Delegate-Protocol.h"
#import "IGSimpleReelPreviewViewDelegate-Protocol.h"

@class IGDefaultGenericMegaphoneLogger, IGGenericMegaphone, IGGenericMegaphoneViewV2, IGMedia, IGSimpleReelPreviewView, IGSimpleReelPreviewViewModel, IGStoryReel, IGStoryViewerPresentationAnimationController, IGUserSession, NSString, UIActivityIndicatorView;

@interface IGBrandedContentViolationViewController : IGViewController <IGGenericMegaphoneViewV2Delegate, IGBrandedContentViolationConfirmationViewControllerDelegate, IGSimpleReelPreviewViewDelegate, IGBrandedContentPartnersViewControllerDelegate>
{
    _Bool _hasPrefetched;
    IGGenericMegaphone *_megaphone;
    IGGenericMegaphoneViewV2 *_megaphoneView;
    IGDefaultGenericMegaphoneLogger *_megaphoneLogger;
    IGViewController *_feedPreviewController;
    UIActivityIndicatorView *_spinner;
    IGSimpleReelPreviewView *_storyPreviewView;
    IGSimpleReelPreviewViewModel *_storyPreviewViewModel;
    IGUserSession *_userSession;
    IGMedia *_media;
    IGStoryReel *_reel;
    NSString *_feedItemId;
    NSString *_mediaId;
    IGStoryViewerPresentationAnimationController *_animationController;
}

- (void).cxx_destruct;
- (void)_storyPreviewTapped;
- (void)_onDoneTapped:(id)arg1;
- (void)_showStoryViewViewController;
- (void)partnersViewControllerDidTapDoneButton;
- (void)partnersViewController:(id)arg1 didUpdateAgeGatingInfo:(id)arg2 geoGatingCountries:(id)arg3;
- (void)partnersViewController:(id)arg1 didUpdatePartners:(id)arg2 isPaidPartnership:(_Bool)arg3 isBCAdsPermissionOn:(_Bool)arg4;
- (void)simpleReelPreviewViewDidTapSurveyReelPreviewView:(id)arg1;
- (void)brandedContentViolationConfirmationViewControllerDidTapDone;
- (void)_showConfirmationVCWithTitle:(id)arg1 message:(id)arg2;
- (id)_createGenericErrorAlertView;
- (void)megaphoneViewNeedsResize:(id)arg1;
- (void)megaphoneViewDidDismiss:(id)arg1;
- (void)megaphoneView:(id)arg1 didSelectButton:(id)arg2;
- (void)_fetchData;
- (void)viewDidLayoutSubviews;
- (void)_setupStoryPreviewView;
- (id)_previewForMedia:(id)arg1;
- (void)_setupFeedPreviewView;
- (void)_setupSpinner;
- (void)_setupMegaphoneView;
- (void)_setupViews;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 megaphone:(id)arg2 media:(id)arg3 reel:(id)arg4;
- (id)initWithUserSession:(id)arg1 feedItemId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

