//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, UIColor;

@interface IGBrowserTitleBarViewModel : NSObject
{
    NSArray *_leftButtonTypes;
    unsigned long long _rightButtonType;
    unsigned long long _browserHeaderStyle;
    UIColor *_titleBarBackgroundColor;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIColor *titleBarBackgroundColor; // @synthesize titleBarBackgroundColor=_titleBarBackgroundColor;
@property(readonly, nonatomic) unsigned long long browserHeaderStyle; // @synthesize browserHeaderStyle=_browserHeaderStyle;
@property(readonly, nonatomic) unsigned long long rightButtonType; // @synthesize rightButtonType=_rightButtonType;
@property(readonly, nonatomic) NSArray *leftButtonTypes; // @synthesize leftButtonTypes=_leftButtonTypes;
- (id)initWithLeftButtonTypes:(id)arg1 rightButtonType:(unsigned long long)arg2 browserHeaderStyle:(unsigned long long)arg3 titleBarBackgroundColor:(id)arg4;

@end

