//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGFeedConfigurationType-Protocol.h"

@class IGAdItemMapper, IGDefaultFeedConfiguration, IGDirectShareRecipient, IGSponsoredSupportConfiguration, NSString;

@interface IGChainingFeedConfiguration : NSObject <IGFeedConfigurationType>
{
    IGSponsoredSupportConfiguration *_sponsoredSupportConfiguration;
    IGDefaultFeedConfiguration *_defaultConfig;
    long long _entryPoint;
    IGAdItemMapper *_adItemMapper;
    IGDirectShareRecipient *_prioritizedDirectRecipient;
    CDStruct_0ba6daeb _IGTVConfiguration;
    CDStruct_fe30105c _carouselInteractionOptions;
    _Bool _disableAccountRecommendations;
}

- (void).cxx_destruct;
- (id)wishlistBarButton;
- (id)priorModule;
- (_Bool)supportFeaturedProducts;
- (CDStruct_fe30105c)carouselInteractionOptions;
- (struct UIEdgeInsets)CTAButtonTappableInsets;
- (unsigned long long)CTAButtonAccessoryPosition;
- (double)loadDistance;
- (_Bool)shouldShowTopSeparator;
- (_Bool)hideDismissedPostsOnDisappear;
- (_Bool)interactiveTagHints;
- (_Bool)persistentOverlayIndicators;
- (long long)UFIPageIndicatorPosition;
- (long long)pageIndicatorType;
- (long long)UFIExternalShareButtonStyle;
- (long long)UFISaveButtonStyle;
- (id)sponsoredSupportConfiguration;
- (_Bool)shouldRenderMediaInSquare;
- (_Bool)supportSeenState;
- (id)feedConsumptionTracker;
- (_Bool)supportCarouselIndexing;
- (_Bool)supportCarouselBumpingAnimation;
- (_Bool)shouldTrackCarouselSeenState;
- (_Bool)shouldTombstoneForUnrelatedHashtagFeedItem;
- (_Bool)supportAccountRecommendations;
- (unsigned long long)tombstoneTypeForFeed;
- (id)savedMediaCollection;
- (id)feedAccessibilityIdentifier;
- (id)analyticsModule;
- (_Bool)supportFavoritesTooltip;
- (_Bool)supportsEdgePostLabel;
- (_Bool)supportStoryRingInHeader;
- (_Bool)shouldPrefetchMediaForFeedItems;
- (_Bool)useAutoplayStrategyforHorizontalVideos;
- (_Bool)videoStitchingEnabled;
- (id)prioritizedDirectRecipient;
- (unsigned long long)igtvViewerFeedPreviewEntryPoint;
- (unsigned long long)sponsoredPostEntryPoint;
- (long long)feedItemHeaderStoryEntryPoint;
- (id)initWithLauncherSet:(id)arg1 analyticsModule:(id)arg2 entryPoint:(long long)arg3 IGTVConfiguration:(CDStruct_b31ca263)arg4 adItemMapper:(id)arg5 prioritizedDirectRecipient:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

