//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGListDiffable-Protocol.h"

@class NSString;

@interface IGCommentRankingToggleModel : NSObject <IGListDiffable>
{
    NSString *_sortOrderString;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *sortOrderString; // @synthesize sortOrderString=_sortOrderString;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithSortOrderString:(id)arg1;

@end

