//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IGCommentLikeRequestManager : NSObject
{
}

+ (void)startCommentLikeRequestForCommentID:(id)arg1 media:(id)arg2 isLikeAction:(_Bool)arg3 userSession:(id)arg4 networker:(id)arg5 analyticsModule:(id)arg6 extras:(id)arg7 successHandler:(CDUnknownBlockType)arg8 failureHandler:(CDUnknownBlockType)arg9;

@end

