//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol FBAnalyticsLogging, IGUserLauncherSetProviding;

@interface IGCoPresenceSignalingLogger : NSObject
{
    NSString *_peerUserPk;
    NSString *_selfUserPk;
    id <FBAnalyticsLogging> _logger;
    id <IGUserLauncherSetProviding> _launcherSet;
    _Bool _hasSetPeerAppCoPresence;
    _Bool _hasRecordedReceiverAppPresenceState;
    _Bool _receiverIsInForeground;
    _Bool _peerThreadCoPresenceEnabled;
    _Bool _hasSetPeerThreadCoPresence;
    _Bool _hasRecordedReceiverThreadPresenceState;
    _Bool _receiverIsInThread;
}

- (void).cxx_destruct;
- (void)setLauncherSet:(id)arg1;
- (void)setLogger:(id)arg1;
- (_Bool)_isClientPresentForPresenceType:(long long)arg1;
- (void)_logCoPresenceImpressionForReceiver:(id)arg1 presenceType:(long long)arg2;
- (void)_logCoPresenceImpressionForInitiator:(id)arg1 presenceType:(long long)arg2;
- (void)logThreadCoPresenceImpressionEvent:(id)arg1;
- (void)recordReceiverThreadState:(_Bool)arg1;
- (void)recordReceiverApplicationState:(_Bool)arg1;
- (void)setupForPeerIsInAudienceThread:(_Bool)arg1 isInAudienceApp:(_Bool)arg2 isThreadCoPresent:(_Bool)arg3;
- (id)initWithAnalyticsLogger:(id)arg1 launcherSet:(id)arg2 selfUserPk:(id)arg3 peerUserPk:(id)arg4;

@end

