//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGCoWatchPremiumContentGridItemSectionControllerSelectionDelegate-Protocol.h"
#import "IGCoWatchPremiumContentNetworkSourceDelegate-Protocol.h"
#import "IGCoWatchPremiumContentVideoDetailsSectionControllerSelectionDelegate-Protocol.h"
#import "IGListAdapterDataSource-Protocol.h"

@class IGCoWatchPremiumContentNetworkSource, NSArray, NSString;
@protocol IGCoWatchPremiumContentDataSourceDelegate;

@interface IGCoWatchPremiumContentDataSource : NSObject <IGCoWatchPremiumContentNetworkSourceDelegate, IGCoWatchPremiumContentVideoDetailsSectionControllerSelectionDelegate, IGCoWatchPremiumContentGridItemSectionControllerSelectionDelegate, IGListAdapterDataSource>
{
    _Bool _isLoading;
    IGCoWatchPremiumContentNetworkSource *_networkSource;
    id <IGCoWatchPremiumContentDataSourceDelegate> _delegate;
    NSArray *_items;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
- (void)gridItemSectionController:(id)arg1 didSelectCatalogItem:(id)arg2;
- (void)videoDetailsSectionController:(id)arg1 didSelectCatalogItem:(id)arg2;
- (void)premiumContentNetworkSourceDidFailToLoad:(id)arg1;
- (void)premiumContentNetworkSource:(id)arg1 didFinishLoadingContent:(id)arg2;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (_Bool)needsAge;
- (long long)itemCount;
- (_Bool)isLoading;
- (void)fetchMore;
- (void)fetch;
- (id)initWithNetworkSource:(id)arg1 delegate:(id)arg2 launcherSet:(id)arg3 analyticsModule:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

