//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class IGCommentGroupCaptionContentView, UIColor;

@interface IGCommentGroupCaptionCell : UICollectionViewCell
{
    UIColor *_previousColor;
    IGCommentGroupCaptionContentView *_commentGroupCaptionContentView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGCommentGroupCaptionContentView *commentGroupCaptionContentView; // @synthesize commentGroupCaptionContentView=_commentGroupCaptionContentView;
- (void)setCaptionViewModel:(id)arg1 coreTextLinkHandler:(id)arg2 profilePicViewDelegate:(id)arg3;
- (void)configureWithShowMediaThumbnail:(_Bool)arg1 mediaPhoto:(id)arg2 author:(id)arg3 authorFollowContext:(id)arg4 module:(id)arg5 launcherProvider:(id)arg6;
- (void)prepareForReuse;
- (void)layoutSubviews;

@end

