//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IGCodeConfirmationFieldDelegate-Protocol.h"

@class IGBottomButtonsView, IGCodeConfirmationField, IGCodeConfirmationViewModel, IGCoreTextView, NSString, UIButton, UILabel, UIScrollView;
@protocol IGCoreTextLinkHandler><IGCodeConfirmationViewDelegate><IGCodeVerificationViewDelegate;

@interface IGCodeVerificationView : UIView <IGCodeConfirmationFieldDelegate>
{
    IGCodeConfirmationViewModel *_viewModel;
    UIButton *_backButton;
    UILabel *_titleLabel;
    IGCoreTextView *_subTitleTextView;
    IGCodeConfirmationField *_confirmationCodeField;
    IGBottomButtonsView *_bottomButtonsView;
    UIScrollView *_containerScrollView;
    double _bottomButtonsViewOriginY;
    id <IGCoreTextLinkHandler><IGCodeConfirmationViewDelegate><IGCodeVerificationViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGCoreTextLinkHandler><IGCodeConfirmationViewDelegate><IGCodeVerificationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (double)_contentHeight;
- (void)adjustViewWithKeyboardFrame:(struct CGRect)arg1 duration:(double)arg2;
- (_Bool)becomeFirstResponder;
- (void)codeConfirmationeField:(id)arg1 allDigitsFilled:(_Bool)arg2;
- (void)_didTapNextButton;
- (void)_didTapBackButton;
- (void)configureWithViewModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

