//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class IGTapButton, UICollectionView, UILabel;
@protocol IGContextualAdsPivotCellDelegate;

@interface IGContextualAdsPivotCell : UICollectionViewCell
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    IGTapButton *_dismissButton;
    id <IGContextualAdsPivotCellDelegate> _delegate;
    UICollectionView *_collectionView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void)_didTapDismissButton;
- (void)configureWithPivotViewModel:(id)arg1 delegate:(id)arg2;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

