//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBIvarBasedEqualityObject.h>

@class IGDirectMediaInteropUpgradeConfig;
@protocol IGDirectMediaInteropUpgradeLoggerProtocol;

@interface IGCoWatchPremiumContentMediaPickerConfig : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    IGDirectMediaInteropUpgradeConfig *_upgradeNeeded_upgradeConfig;
    id <IGDirectMediaInteropUpgradeLoggerProtocol> _upgradeNeeded_logger;
}

+ (id)upgradeNeededWithUpgradeConfig:(id)arg1 logger:(id)arg2;
+ (id)enabled;
+ (id)disabled;
- (void).cxx_destruct;
- (void)matchDisabled:(CDUnknownBlockType)arg1 upgradeNeeded:(CDUnknownBlockType)arg2 enabled:(CDUnknownBlockType)arg3;

@end

