//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBIvarBasedEqualityObject.h>

@interface IGCreatorPartnershipAdsLabelItemAccessory : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    long long _requestCountLabel_requestCount;
}

+ (id)requestCountLabelWithRequestCount:(long long)arg1;
+ (id)chevron;
- (void)matchChevron:(CDUnknownBlockType)arg1 requestCountLabel:(CDUnknownBlockType)arg2;

@end

