//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "FBMessagePowerupDelegate-Protocol.h"

@class IGDirectTextMessageBubbleView, NSMutableArray, NSString;
@protocol FBMessagePowerupSupporting;

@interface IGDirectPowerupTextMessageCell : UICollectionViewCell <FBMessagePowerupDelegate>
{
    struct CGSize _textBubbleSize;
    IGDirectTextMessageBubbleView *_textBubbleView;
    id <FBMessagePowerupSupporting> _messagePowerup;
    NSMutableArray *_powerupsViews;
}

- (void).cxx_destruct;
- (void)messagePowerup:(id)arg1 setTextViewUserInteractionEnabled:(_Bool)arg2;
- (id)messagePowerup:(id)arg1 tintImage:(id)arg2 withGradientStartColor:(id)arg3 gradientEndColor:(id)arg4;
- (void)messagePowerup:(id)arg1 setTextViewColor:(id)arg2;
- (struct CGRect)messagePowerup:(id)arg1 convertRect:(struct CGRect)arg2 fromContainerToView:(id)arg3;
- (struct CGRect)messagePowerup:(id)arg1 convertRect:(struct CGRect)arg2 fromContentToView:(id)arg3;
- (void)messagePowerup:(id)arg1 addViewToMaskedBubbleView:(id)arg2;
- (void)messagePowerup:(id)arg1 addViewToContent:(id)arg2;
- (void)messagePowerup:(id)arg1 insertViewBelowTextView:(id)arg2;
- (struct CGRect)messagePowerupContentBounds:(id)arg1;
- (void)messagePowerup:(id)arg1 addViewToContainer:(id)arg2 inFrontOfContent:(_Bool)arg3 inFrontOfReactions:(_Bool)arg4;
- (void)messagePowerup:(id)arg1 transformContainer:(struct CGAffineTransform)arg2;
- (void)configureWithViewModel:(id)arg1 gradientContentsRect:(struct CGRect)arg2;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)_setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

