//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableOrderedSet, NSMutableSet, NSSet;
@protocol IGDirectThreadParticipantsRequestsControllerAnnouncer;

@interface IGDirectThreadParticipantsRequestsController : NSObject
{
    NSMutableArray *_requestedParticipants;
    NSMutableOrderedSet *_orderedRequestedParticipantIds;
    NSMutableSet *_selectedParticipants;
    NSMutableDictionary *_requesterUserIdToUsername;
    long long _maxParticipantsCount;
    id <IGDirectThreadParticipantsRequestsControllerAnnouncer> _announcer;
    _Bool _moreParticipantRequestsAvailable;
    long long _participantRequestsCount;
    long long _activeParticipantsCount;
    long long _participantRequestButtonActionState;
}

- (void).cxx_destruct;
@property(nonatomic) long long participantRequestButtonActionState; // @synthesize participantRequestButtonActionState=_participantRequestButtonActionState;
@property(readonly, nonatomic) _Bool moreParticipantRequestsAvailable; // @synthesize moreParticipantRequestsAvailable=_moreParticipantRequestsAvailable;
@property(readonly, nonatomic) NSArray *requestedParticipants; // @synthesize requestedParticipants=_requestedParticipants;
@property(readonly, nonatomic) long long activeParticipantsCount; // @synthesize activeParticipantsCount=_activeParticipantsCount;
@property(readonly, nonatomic) long long participantRequestsCount; // @synthesize participantRequestsCount=_participantRequestsCount;
@property(readonly, nonatomic) long long maxParticipantsCount; // @synthesize maxParticipantsCount=_maxParticipantsCount;
- (void)_removeSelectedParticipant:(id)arg1;
- (void)_addSelectedParticipant:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (_Bool)didReachMaxParticipants;
- (void)unselectAllParticipants;
- (void)selectAllParticipants;
- (void)toggleRequestedParticipant:(id)arg1;
- (void)removeRequestedParticipant:(id)arg1;
- (void)addRequestedParticipantsToChat:(id)arg1;
- (void)appendRequests:(id)arg1;
@property(readonly, nonatomic) NSDictionary *requesterUserIdToUsername;
@property(readonly, nonatomic) NSSet *selectedParticipants;
- (void)reset;
- (id)initWithLauncherSetProvider:(id)arg1;

@end

