//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBIvarBasedEqualityObject.h>

@interface IGDirectComposerOverflowTrayTarget : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    _Bool _stickers_selfieSticker;
}

+ (id)unified;
+ (id)stickersWithSelfieSticker:(_Bool)arg1;
+ (id)recents;
+ (id)gifs;
- (void)matchStickers:(CDUnknownBlockType)arg1 gifs:(CDUnknownBlockType)arg2 recents:(CDUnknownBlockType)arg3 unified:(CDUnknownBlockType)arg4;

@end

