//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGListGenericSectionController.h>

#import "IGDirectAggregatedMediaCellDelegate-Protocol.h"
#import "IGListWorkingRangeDelegate-Protocol.h"

@class IGMediaPreloader, IGUserSession, NSString;
@protocol IGDirectAggregatedMediaSectionControllerDelegate;

@interface IGDirectAggregatedMediaSectionController : IGListGenericSectionController <IGDirectAggregatedMediaCellDelegate, IGListWorkingRangeDelegate>
{
    IGUserSession *_userSession;
    IGMediaPreloader *_mediaPreloader;
    NSString *_threadId;
    unsigned long long _style;
    NSString *_analyticsModule;
    id <IGDirectAggregatedMediaSectionControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGDirectAggregatedMediaSectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)listAdapter:(id)arg1 sectionControllerDidExitWorkingRange:(id)arg2;
- (void)listAdapter:(id)arg1 sectionControllerWillEnterWorkingRange:(id)arg2;
- (void)aggregatedMediaCellDidRequestSave:(id)arg1;
- (void)_presentMediaViewerFromCell:(id)arg1;
- (void)didSelectItemAtIndex:(long long)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (id)initWithUserSession:(id)arg1 threadId:(id)arg2 style:(unsigned long long)arg3 analyticsModule:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

