//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface IGDirectThreadMegaphoneWrapperView : UIView
{
    UIView *_megaphoneView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *megaphoneView; // @synthesize megaphoneView=_megaphoneView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;

@end

