//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGListAdapterDataSource-Protocol.h"

@class IGListAdapter, NSArray, NSString, UICollectionView;
@protocol IGUserFeatureSets;

@interface IGDirectThreadLabelManager : NSObject <IGListAdapterDataSource>
{
    id <IGUserFeatureSets> _userFeatureSets;
    IGListAdapter *_listAdapter;
    UICollectionView *_collectionView;
    NSArray *_threadLabelsList;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *threadLabelsList; // @synthesize threadLabelsList=_threadLabelsList;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)_buildThreadLabelRows:(double)arg1;
- (void)_setupListAdapter;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (struct CGSize)threadLabelListSizeThatFits:(struct CGSize)arg1;
- (void)updateThreadLabelsList:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithUserFeatureSets:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

