//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGDirectMessageCell.h>

#import "IGHeartAnimatable-Protocol.h"

@class IGDirectReshareMessageContainerView, NSString;

@interface IGDirectHashtagMessageCell : IGDirectMessageCell <IGHeartAnimatable>
{
    struct CGSize _hashtagContentSize;
    IGDirectReshareMessageContainerView *_reshareContainerView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGDirectReshareMessageContainerView *reshareContainerView; // @synthesize reshareContainerView=_reshareContainerView;
- (id)contentViewForHeartAnimation;
- (struct CGSize)messageContentSize;
- (void)configureWithViewModel:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)_setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

