//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGListAdapterDataSource-Protocol.h"

@class IGDirectInboxCellSelectCoordinator, IGDirectInboxCellSwipeCoordinator, IGDirectInboxPendingRequests, IGDirectInboxThreadCellContentTheme, IGDirectPendingInboxAnalyticsLogger, IGDirectPendingInboxNuxSectionController, IGDirectPendingInboxNuxViewModel, IGDirectPendingInboxThreadSortButtonSectionController, IGDirectPendingInboxThreadSortButtonViewModel, IGTableLayoutSpec, IGUser, IGUserSession, NSArray, NSOrderedSet, NSString;
@protocol IGDirectPendingInboxListAdapterDataSourceDelegate, IGSubscriptionToken;

@interface IGDirectPendingInboxListAdapterDataSource : NSObject <IGListAdapterDataSource>
{
    IGDirectPendingInboxNuxViewModel *_nuxViewModel;
    IGDirectPendingInboxNuxSectionController *_nuxSectionController;
    IGDirectPendingInboxThreadSortButtonViewModel *_threadSortButtonViewModel;
    IGDirectPendingInboxThreadSortButtonSectionController *_threadSortButtonController;
    IGTableLayoutSpec *_tableLayoutSpec;
    IGDirectInboxThreadCellContentTheme *_threadCellContentTheme;
    _Bool _rankedRequestsEnabled;
    IGDirectPendingInboxAnalyticsLogger *_analyticsLogger;
    IGUser *_user;
    IGUserSession *_userSession;
    id <IGDirectPendingInboxListAdapterDataSourceDelegate> _delegate;
    IGDirectInboxCellSwipeCoordinator *_swipeCoordinator;
    IGDirectInboxCellSelectCoordinator *_selectCoordinator;
    NSOrderedSet *_threads;
    IGDirectInboxPendingRequests *_pendingRequests;
    long long _sortType;
    _Bool _hasMoreThreads;
    _Bool _isFilteredFolderEnabled;
    _Bool _isPermanentMessageRequestsEntryPointEnabled;
    _Bool _isSpamFetchEnabled;
    long long _maxHiddenRequestDisplayCount;
    _Bool _subscriptionRefactorEnabled;
    NSArray *_threadCellViewModelList;
    CDUnknownBlockType _viewModelSubscriptionCreationBlock;
    id <IGSubscriptionToken> _subscriptionToken;
}

- (void).cxx_destruct;
- (void)_addFooterViewModelIfNeeded:(id)arg1 unfilteredRequestsCount:(unsigned long long)arg2 filteredRequestsCount:(unsigned long long)arg3 listAdapter:(id)arg4;
- (_Bool)_shouldShowLoadMoreButtonWithFilteredRequestsCount:(unsigned long long)arg1 listAdapter:(id)arg2;
- (_Bool)_shouldShowEmptyStateForSortTimeReceived;
- (_Bool)_shouldShowEmptyState:(unsigned long long)arg1 filteredRequestsCount:(unsigned long long)arg2;
- (void)_addEmptyFeedViewModelIfNeeded:(id)arg1 listAdapter:(id)arg2;
- (void)_addUnfilteredThreadViewModelsIfNeeded:(id)arg1 unfilteredThreadCellViewModels:(id)arg2;
- (void)_addFilteredThreadsViewModelIfNeeded:(id)arg1 filteredThreadCellViewModels:(id)arg2;
- (void)_addSortButtonViewModelIfNeeded:(id)arg1;
- (void)_addDisclaimerViewModelIfNeeded:(id)arg1;
- (id)buildThreadViewModelForThread:(id)arg1 index:(unsigned long long)arg2 isEditing:(_Bool)arg3 isSelected:(_Bool)arg4;
- (id)analyticsModule;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (void)subscribeForSortType:(long long)arg1 shouldFinishRefreshing:(_Bool)arg2;
- (void)updateDataSourceWithThreads:(id)arg1 pendingRequests:(id)arg2 sortType:(long long)arg3 hasMoreThreads:(_Bool)arg4;
- (id)initWithUserSession:(id)arg1 tableLayoutSpec:(id)arg2 threadCellContentTheme:(id)arg3 analyticsLogger:(id)arg4 rankedRequestsEnabled:(_Bool)arg5 messageSettingsFromNuxEnabled:(_Bool)arg6 swipeCoordinator:(id)arg7 selectCoordinator:(id)arg8 threadSortButtonController:(id)arg9 delegate:(id)arg10 subscriptionRefactorEnabled:(_Bool)arg11 viewModelSubscriptionCreationBlock:(CDUnknownBlockType)arg12;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

