//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGDirectBlendedInboxDataLoader-Protocol.h"
#import "IGDirectInboxDataLoader-Protocol.h"

@class IGDirectLatestSubscriptionValueRetriever, IGDirectMsysMessagingMailbox, NSMutableDictionary, NSString;

@interface IGDirectMsysSecureInboxSubscriptionService : NSObject <IGDirectInboxDataLoader, IGDirectBlendedInboxDataLoader>
{
    IGDirectMsysMessagingMailbox *_mailbox;
    _Bool _supportsCutoverThreads;
    IGDirectLatestSubscriptionValueRetriever *_latestValueRetriever;
    NSMutableDictionary *_tabsToPipes;
    NSMutableDictionary *_tabsToPublishers;
}

- (void).cxx_destruct;
- (id)_retrievePublisherForTab:(id)arg1 filterType:(long long)arg2;
- (id)_retrievePipeForTab:(id)arg1 filterType:(long long)arg2;
- (void)loadWithDjangoPagingCursor:(id)arg1;
- (void)loadNextPageOfThreadsForBlendedInboxTab:(id)arg1;
- (void)loadNextPageOfThreadsForTab:(id)arg1;
- (void)registerSingleUseSubscriptionWithTab:(id)arg1 successBlock:(CDUnknownBlockType)arg2 errorBlock:(CDUnknownBlockType)arg3;
- (id)registerSubscriptionForTab:(id)arg1 updateBlock:(CDUnknownBlockType)arg2 errorBlock:(CDUnknownBlockType)arg3;
- (id)initWithUserSession:(id)arg1;
- (id)secureInboxSubscriptionPipeForTab:(id)arg1 filterType:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

