//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IGMainAppScrollingChildViewController-Protocol.h"

@class NSArray, NSSet;
@protocol IGStoryCreationViewControllerNavigationDelegate, IGSundialCreationViewControllerNavigationDelegate;

@protocol IGDirectInboxControlling <IGMainAppScrollingChildViewController>
- (void)storyCameraDidEndWithResetToFeed;
- (void)setSelectedFilter:(long long)arg1;
- (void)clearOverlays;
- (void)willActivateViewController;
- (void)willPresentFromStoryCreationAfterSendingMessage;
- (NSArray *)animatableCellsForRecipients:(NSSet *)arg1;
- (void)presentNewMessageCameraWithEntryPoint:(long long)arg1 customNavigationDelegate:(id <IGStoryCreationViewControllerNavigationDelegate>)arg2 sundialNavigationDelegate:(id <IGSundialCreationViewControllerNavigationDelegate>)arg3;
- (void)pushToCallsTab;
- (void)pushThreadComposerWithEntryPoint:(unsigned long long)arg1;
- (void)pushToPendingInboxAnimated:(_Bool)arg1;
- (void)scrollToTopAnimated:(_Bool)arg1;
@end

