//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class CALayer;

@interface IGDiscoveryGridItemCell : UICollectionViewCell
{
    CALayer *_highlightLayer;
}

- (void).cxx_destruct;
- (void)_createLayerIfNeeded;
- (void)_updateHighlightState;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

