//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBIvarBasedEqualityObject.h>

@class IGDirectMediaTypeFilter, NSString;

@interface IGDirectMediaPickerGalleryConfig : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    NSString *_enabled_subtitle;
    unsigned long long _enabled_checkmarkStyle;
    IGDirectMediaTypeFilter *_enabled_mediaTypeFilter;
    _Bool _enabled_isInteropThread;
}

+ (id)enabledWithSubtitle:(id)arg1 checkmarkStyle:(unsigned long long)arg2 mediaTypeFilter:(id)arg3 isInteropThread:(_Bool)arg4;
+ (id)disabled;
- (void).cxx_destruct;
- (void)matchDisabled:(CDUnknownBlockType)arg1 enabled:(CDUnknownBlockType)arg2;

@end

