//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class IGDirectInboxHeaderCellViewModel, IGSegmentedTabControl, IGTapButton, UILabel, UIView;
@protocol IGDirectInboxHeaderCellDelegate;

@interface IGDirectInboxHeaderCell : UICollectionViewCell
{
    IGDirectInboxHeaderCellViewModel *_viewModel;
    id <IGDirectInboxHeaderCellDelegate> _delegate;
    UIView *_cellBodyContainerView;
    UILabel *_headerLabel;
    UIView *_bottomLineView;
    IGTapButton *_headerActionButton;
    IGSegmentedTabControl *_segmentedTabControl;
}

- (void).cxx_destruct;
- (void)_tabControlValueChanged:(id)arg1;
- (void)_headerActionButtonTapped:(id)arg1;
- (id)accessibilityElements;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (void)updateTabControlSegments:(id)arg1;
- (void)configureWithViewModel:(id)arg1 delegate:(id)arg2;
- (void)_layoutTitleAndImageForHeaderActionButton;
- (void)_layoutHeaderActionButton;
- (void)layoutSubviews;
- (void)setUserInteractionEnabled:(_Bool)arg1;
- (void)_updateCurrentTab:(id)arg1;
- (void)_updateSegmentedTabControlWithTabs:(id)arg1;
- (void)_setupBottomLineViewIfNeeded;
- (void)_setupSegmentedTabControlIfNeeded;
- (void)_setupHeaderActionButton;
- (void)_setupHeaderLabel;
- (void)_setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

