//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGDynamicPageSectionController;

@protocol IGDynamicPageSectionControllerDelegate <NSObject>
- (void)dynamicPageSectionController:(IGDynamicPageSectionController *)arg1 willChangeToRepresentationStyle:(long long)arg2 previousRepresentationStyle:(long long)arg3;
- (void)dynamicPageSectionControllerDidEndBeingDisplayed:(IGDynamicPageSectionController *)arg1;
- (void)dynamicPageSectionControllerWillBeDisplayed:(IGDynamicPageSectionController *)arg1;
@end

