//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class IGButton, IGInsetLabel, IGTooltipView;
@protocol IGEditProfileBioAccessoryBarViewDelegate;

@interface IGEditProfileBioAccessoryBarView : UIView
{
    IGInsetLabel *_characterCountLabel;
    IGButton *_mentionButton;
    IGButton *_hashtagButton;
    UIView *_separator;
    _Bool _shouldShowAccessoryButtons;
    IGTooltipView *_tooltip;
    id <IGEditProfileBioAccessoryBarViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGEditProfileBioAccessoryBarViewDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)_areButtonsSelected;
- (void)_didTapHashtag;
- (void)_didTapMention;
- (_Bool)tryToShowTooltip;
- (void)selectMentionButton;
- (void)selectHashtagButton;
- (void)clearSelection;
- (void)layoutSubviews;
- (void)updateCharacterCountDifference:(long long)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithShouldShowAccessoryButtons:(_Bool)arg1;

@end

