//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBKVOController, IGTextButton, IGUser, IGUserSession, UILabel;

@interface IGEmptyStoryView : UIView
{
    IGUserSession *_userSession;
    UILabel *_titleLabel;
    UILabel *_descriptionLabel;
    IGTextButton *_subscribeButton;
    FBKVOController *_kvoController;
    IGUser *_currentItemOwner;
}

- (void).cxx_destruct;
- (void)_didTapSubscribeToggle;
- (void)_updateStorySubscriptionStatus:(_Bool)arg1;
- (void)configureWithCurrentItemUser:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithUserSession:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

