//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGFeedPreviewHandler, IGHashtagModel, IGMedia, IGProductItem, NSArray, NSDictionary, NSIndexPath, NSString;

@protocol IGFeedPreviewHandlerDelegate <NSObject>
- (void)previewHandlerDidTapSaveOrUnsave:(IGFeedPreviewHandler *)arg1 shouldSave:(_Bool)arg2 productItem:(IGProductItem *)arg3;
- (NSArray *)previewHandler:(IGFeedPreviewHandler *)arg1 previewActionsForMedia:(IGMedia *)arg2 defaultActionProvider:(NSArray * (^)(void))arg3 loggingExtra:(NSString *)arg4;
- (IGHashtagModel *)hashtagModelForPreviewHandler:(IGFeedPreviewHandler *)arg1;
- (NSDictionary *)previewHandler:(IGFeedPreviewHandler *)arg1 loggingExtrasForMedia:(IGMedia *)arg2 atIndexPath:(NSIndexPath *)arg3;
@end

