//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGSaveStatusListener-Protocol.h"
#import "IGShoppingGenericProductTileSectionControllerDelegate-Protocol.h"

@class IGSessionTracker, IGShoppingNavigationAnalyticsContext, IGShoppingScheduledLiveInfo, IGUserSession, NSString, UIViewController;
@protocol IGFeedUpcomingEventShoppingViewAdapterDelegate;

@interface IGFeedUpcomingEventShoppingViewAdapter : NSObject <IGSaveStatusListener, IGShoppingGenericProductTileSectionControllerDelegate>
{
    IGUserSession *_userSession;
    NSString *_upcomingEventId;
    IGShoppingScheduledLiveInfo *_shoppingInfo;
    UIViewController *_viewController;
    IGShoppingNavigationAnalyticsContext *_analyticsContext;
    IGSessionTracker *_shoppingSessionTracker;
    struct IGGridLayoutConfiguration _gridLayoutConfiguration;
    NSString *_mediaPk;
    NSString *_mediaAuthorPk;
    id <IGFeedUpcomingEventShoppingViewAdapterDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGFeedUpcomingEventShoppingViewAdapterDelegate> delegate; // @synthesize delegate=_delegate;
- (void)savableObject:(id)arg1 didUpdateSaveStatusWithHasSaved:(_Bool)arg2 saveAction:(long long)arg3;
- (void)genericProductTileSectionController:(id)arg1 didTapDismissForProductItemPk:(id)arg2;
- (void)genericProductTileSectionController:(id)arg1 willNavigateToPDPForProductItemPk:(id)arg2 merchantId:(id)arg3;
- (_Bool)genericProductTileSectionController:(id)arg1 containsLastSavedProductItemPk:(id)arg2;
- (void)genericProductTileSectionController:(id)arg1 didUpdateGenericProductItem:(id)arg2 withUpdatedSaveStatus:(_Bool)arg3 displayedMediaId:(id)arg4 successHandler:(CDUnknownBlockType)arg5;
- (id)_productTileLoggingProvider;
- (id)sectionControllerForProductFeedViewModel:(id)arg1;
- (id)productFeedViewModels;
- (id)initWithUserSession:(id)arg1 upcomingEventId:(id)arg2 shoppingInfo:(id)arg3 viewController:(id)arg4 analyticsContext:(id)arg5 shoppingSessionTracker:(id)arg6 gridLayoutConfiguration:(struct IGGridLayoutConfiguration)arg7 mediaPk:(id)arg8 mediaAuthorPk:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

