//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGFeedItemMediaCell.h>

#import "IGCoreTextLinkHandler-Protocol.h"

@class IGCoreTextView, IGUserSession, NSString, UIImageView, UIViewController;
@protocol IGFeedItemBuyerIncentiveAdsCellDelegate, IGSponsoredInfoProviding;

@interface IGFeedItemBuyerIncentiveAdsCell : IGFeedItemMediaCell <IGCoreTextLinkHandler>
{
    IGCoreTextView *_descriptionTextView;
    UIImageView *_iconImageView;
    UIViewController *_viewController;
    id <IGSponsoredInfoProviding> _sponsoredInfoProvider;
    NSString *_incentiveId;
    NSString *_incentiveTermsAndConditionsTitle;
    NSString *_incentiveTermsAndConditionsDescription;
    IGUserSession *_userSession;
    id <IGFeedItemBuyerIncentiveAdsCellDelegate> _delegate;
    long long _cellType;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long cellType; // @synthesize cellType=_cellType;
@property(nonatomic) __weak id <IGFeedItemBuyerIncentiveAdsCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (void)configureForCellType:(long long)arg1 description:(id)arg2 icon:(id)arg3 viewController:(id)arg4 sponsoredInfoProvider:(id)arg5 userSession:(id)arg6;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

