//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIImageView, UILabel, UIView;
@protocol IGFollowListSortingCellDelegate;

@interface IGFollowListSortingCell : UICollectionViewCell <UIGestureRecognizerDelegate>
{
    UILabel *_sortingTitle;
    UIImageView *_sortingImageView;
    UIView *_topSeparator;
    id <IGFollowListSortingCellDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGFollowListSortingCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_didTapCell;
- (id)_attributedStringForSortingTitle:(id)arg1;
- (void)configureWithViewModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

