//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGFeedNetworkSourceDelegate-Protocol.h"
#import "IGFundraiserMediaPickerPostItemSectionControllerDelegate-Protocol.h"
#import "IGListAdapterDataSource-Protocol.h"
#import "IGListDisplayDelegate-Protocol.h"
#import "IGTabControlSegment-Protocol.h"

@class IGFeedNetworkSource, IGFeedStarterKit, IGUserSession, NSString;
@protocol IGFundraiserMediaPickerPostsViewControllerDelegate;

@interface IGFundraiserMediaPickerPostsViewController : IGViewController <IGFeedNetworkSourceDelegate, IGFundraiserMediaPickerPostItemSectionControllerDelegate, IGListAdapterDataSource, IGListDisplayDelegate, IGTabControlSegment>
{
    IGFeedStarterKit *_feedStarterKit;
    IGFeedNetworkSource *_feedNetworkSource;
    IGUserSession *_userSession;
    id <IGFundraiserMediaPickerPostsViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGFundraiserMediaPickerPostsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_fetchMoreItems;
- (struct UIEdgeInsets)preferredContentInsets;
- (id)title;
- (void)postItemSectionController:(id)arg1 didSelectPostItem:(id)arg2;
- (void)listAdapter:(id)arg1 didEndDisplayingSectionController:(id)arg2 cell:(id)arg3 atIndex:(long long)arg4;
- (void)listAdapter:(id)arg1 willDisplaySectionController:(id)arg2 cell:(id)arg3 atIndex:(long long)arg4;
- (void)listAdapter:(id)arg1 didEndDisplayingSectionController:(id)arg2;
- (void)listAdapter:(id)arg1 willDisplaySectionController:(id)arg2;
- (void)feedNetworkSource:(id)arg1 willLoadItemsFromResponse:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didStartLoadingWithConfig:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didChangeToObjects:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didFailToLoadWithConfig:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didFinishLoadingObjects:(id)arg2 withConfig:(id)arg3;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

