//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSSet;

@interface IGGalleryViewModel : NSObject <NSCopying>
{
    NSArray *_mediaShells;
    NSArray *_reelShells;
    NSSet *_supplementaryFragments;
}

+ (id)newWithMediaShells:(id)arg1 reelShells:(id)arg2 supplementaryFragments:(id)arg3;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSSet *supplementaryFragments; // @synthesize supplementaryFragments=_supplementaryFragments;
@property(readonly, copy, nonatomic) NSArray *reelShells; // @synthesize reelShells=_reelShells;
@property(readonly, copy, nonatomic) NSArray *mediaShells; // @synthesize mediaShells=_mediaShells;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)_initWithMediaShells:(id)arg1 reelShells:(id)arg2 supplementaryFragments:(id)arg3;

@end

