//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGListSectionController.h>

#import "IGGenericSurveyAnswerListCellDelegate-Protocol.h"
#import "IGGenericSurveyButtonCellDelegate-Protocol.h"
#import "IGGenericSurveyTextViewDelegate-Protocol.h"

@class IGGenericSurveyAlertAssistant, IGGenericSurveyAnswerContext, IGGenericSurveyTapCTAContext, NSArray, NSSet, NSString;
@protocol IGGenericSurveyAnswerListSectionControllerDelegate;

@interface IGGenericSurveyAnswerListSectionController : IGListSectionController <IGGenericSurveyAnswerListCellDelegate, IGGenericSurveyButtonCellDelegate, IGGenericSurveyTextViewDelegate>
{
    id <IGGenericSurveyAnswerListSectionControllerDelegate> _delegate;
    IGGenericSurveyAlertAssistant *_alertAssistant;
    IGGenericSurveyAnswerContext *_context;
    NSArray *_cellTypeList;
    NSSet *_selectionSet;
    NSString *_textResponse;
    IGGenericSurveyTapCTAContext *_tapCTAContext;
    unsigned long long _surveyType;
}

+ (id)_surveyCellTypeClassMap;
- (void).cxx_destruct;
- (void)_complete;
- (unsigned long long)_errorTypeOnSubmit;
- (_Bool)_hasQuestionResponded;
- (void)_dismissKeyboard;
- (unsigned long long)_buttonState;
- (void)_updateSubmitButtonState;
- (void)_initCellTypeList;
- (id)_commentCell;
- (id)_buttonCell;
- (void)genericSurveyButtonCellDidTap;
- (_Bool)genericSurveyTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)genericSurveyTextViewDidEndEditing:(id)arg1;
- (void)genericSurveyAnswerListCell:(id)arg1 didChangeSelection:(id)arg2;
- (void)didUpdateToObject:(id)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (long long)numberOfItems;
- (id)initWithDelegate:(id)arg1 alertAssistant:(id)arg2 surveyType:(unsigned long long)arg3 tapCTAContext:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

