//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGListSectionController.h>

#import "IGGenericSurveyQuestionDelegate-Protocol.h"

@class IGGenericSurveyQuestionTitlesDataSource, NSString;
@protocol IGGenericSurveyQuestionTitleListSectionControllerDelegate;

@interface IGGenericSurveyQuestionTitleListSectionController : IGListSectionController <IGGenericSurveyQuestionDelegate>
{
    long long _currentQuestionIndex;
    long long _maxQuestionIndex;
    IGGenericSurveyQuestionTitlesDataSource *_dataSource;
    id <IGGenericSurveyQuestionTitleListSectionControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGGenericSurveyQuestionTitleListSectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned long long)_navBarButtonStatusWithQuestionIndex:(long long)arg1;
- (id)_visibleCell;
- (void)genericSurveyQuestionCellDidTapBackButton:(id)arg1;
- (void)genericSurveyQuestionCellDidTapForwardButton:(id)arg1;
- (void)didUpdateToObject:(id)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (void)updateQuestionTitleBarButtonStatus:(unsigned long long)arg1;
- (void)proceedToQuestionWithIndex:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

