//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGFeedSectionControllerActionDelegate-Protocol.h"

@class NSString;
@protocol IGGenericSurveyTapCTAContextDelegate;

@interface IGGenericSurveyTapCTAContext : NSObject <IGFeedSectionControllerActionDelegate>
{
    id <IGGenericSurveyTapCTAContextDelegate> _receiver;
    _Bool _hasCTATapped;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hasCTATapped; // @synthesize hasCTATapped=_hasCTATapped;
- (void)feedSectionControllerDidBeginWYTSurvey:(id)arg1;
- (void)feedSectionControllerDidLoop:(id)arg1;
- (void)feedSectionControllerDidEndUserInteraction:(id)arg1;
- (void)feedSectionControllerDidBeginUserInteraction:(id)arg1;
- (void)feedSectionController:(id)arg1 showDetailsForMedia:(id)arg2;
- (_Bool)feedSectionControllerIsInOverviewMode:(id)arg1;
- (void)feedSectionController:(id)arg1 showRelatedPostsForMedia:(id)arg2;
- (void)feedSectionControllerDidTapDismissButton:(id)arg1;
- (void)feedSectionController:(id)arg1 didLikeFeedItem:(id)arg2 mediaView:(id)arg3;
- (void)feedSectionControllerDidDismissFeedItem:(id)arg1;
- (_Bool)feedSectionControllerShouldExpandFeedItemOnMoreTapped:(id)arg1;
- (_Bool)feedSectionController:(id)arg1 shouldNavigateToCommentsWithEntryPoint:(long long)arg2;
- (void)feedSectionController:(id)arg1 didUnfollowHashtag:(id)arg2;
- (void)feedSectionController:(id)arg1 changedMuteStatusForUser:(id)arg2 changedPostsMuteStatus:(_Bool)arg3 changedStoryMuteStatus:(_Bool)arg4;
- (void)feedSectionController:(id)arg1 didUnfollowUser:(id)arg2;
- (void)feedSectionControllerDidSwipePageCell:(id)arg1 toIndex:(long long)arg2;
- (void)feedSectionControllerDidTapCommentEntryPoint:(id)arg1 replyText:(id)arg2;
- (void)feedSectionControllerDidTapCustomizableButton:(id)arg1;
- (void)setReceiver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

