//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGBouncyCollectionViewCell.h>

#import "IGImageViewDelegate-Protocol.h"
#import "IGTransitionZoomViewCustomizable-Protocol.h"

@class IGGradientView, IGGuideThumbnailAttributionView, IGImageView, IGStackLayout, NSString, UIImageView, UILabel;

@interface IGGuidesGridCell : IGBouncyCollectionViewCell <IGImageViewDelegate, IGTransitionZoomViewCustomizable>
{
    IGImageView *_coverImageView;
    IGGradientView *_bottomLegibilityGradient;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    IGGuideThumbnailAttributionView *_attributionView;
    IGStackLayout *_layout;
    UIImageView *_selectionImageView;
    long long _selectionState;
}

+ (double)suggestedNetEgoCellWidth;
+ (double)suggestedNetEgoCellHeight;
- (void).cxx_destruct;
@property(nonatomic) long long selectionState; // @synthesize selectionState=_selectionState;
- (double)zoomTransitionViewCornerRadius;
- (void)imageView:(id)arg1 willRequestImageWithURL:(id)arg2;
- (void)imageView:(id)arg1 didUpdateDownloadProgress:(double)arg2;
- (void)imageView:(id)arg1 didUpdateLoadingState:(id)arg2;
- (void)imageView:(id)arg1 didFailToLoadImageWithError:(id)arg2 networkRequestSummary:(id)arg3;
- (void)imageView:(id)arg1 didLoadImageFromSource:(unsigned long long)arg2 networkRequestSummary:(id)arg3;
- (void)configureWithTitle:(id)arg1 subtitle:(id)arg2 user:(id)arg3 coverImageSpecifier:(id)arg4 analyticsModule:(id)arg5;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

