//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGDirectShareSheetControllerDelegate-Protocol.h"
#import "IGFeedScrollViewListener-Protocol.h"
#import "IGGuideAddItemFlowControllerDelegate-Protocol.h"
#import "IGGuideCoverMediaPickerViewControllerDelegate-Protocol.h"
#import "IGGuideCreationUpsellDelegate-Protocol.h"
#import "IGGuideDetailSectionControllerDelegate-Protocol.h"
#import "IGGuideFooterViewDelegate-Protocol.h"
#import "IGGuideHeaderSectionControllerDelegate-Protocol.h"
#import "IGGuideItemReorderViewControllerDelegate-Protocol.h"
#import "IGGuideItemSectionControllerDelegate-Protocol.h"
#import "IGGuideItemsNetworkSourceDelegate-Protocol.h"
#import "IGGuideShareSheetDelegate-Protocol.h"
#import "IGGuideTabbedMediaPickerViewControllerDelegate-Protocol.h"
#import "IGListAdapterDataSource-Protocol.h"
#import "IGListAdapterDelegate-Protocol.h"
#import "IGMediaUpdatedListener-Protocol.h"
#import "IGShoppingSessionTracking-Protocol.h"
#import "IGTransitionZoomToCapable-Protocol.h"
#import "IGUFIButtonBarViewDelegate-Protocol.h"

@class IGFeedScrollViewAnnouncer, IGFeedVideoCellManager_DEPRECATED, IGGuide, IGGuideCreationFlowPresenter, IGGuideCreationLogger, IGGuideCreationUpsellItem, IGGuideFooterView, IGGuideHeaderSectionController, IGGuideItemsNetworkSource, IGGuideLogger, IGGuideNavigationBarView, IGGuideSeparatorObject, IGListAdapter, IGSessionTracker, IGUserSession, NSArray, NSString, UICollectionView;
@protocol IGDirectShareSheetControlling, IGGuideViewControllerMapDelegate, IGRequestToken;

@interface IGGuideViewController : IGViewController <IGDirectShareSheetControllerDelegate, IGListAdapterDataSource, IGListAdapterDelegate, IGGuideItemsNetworkSourceDelegate, IGGuideAddItemFlowControllerDelegate, IGGuideHeaderSectionControllerDelegate, IGGuideDetailSectionControllerDelegate, IGGuideItemSectionControllerDelegate, IGGuideCoverMediaPickerViewControllerDelegate, IGGuideTabbedMediaPickerViewControllerDelegate, IGGuideItemReorderViewControllerDelegate, IGGuideFooterViewDelegate, IGGuideShareSheetDelegate, IGFeedScrollViewListener, IGMediaUpdatedListener, IGUFIButtonBarViewDelegate, IGTransitionZoomToCapable, IGGuideCreationUpsellDelegate, IGShoppingSessionTracking>
{
    IGListAdapter *_listAdapter;
    UICollectionView *_collectionView;
    IGFeedScrollViewAnnouncer *_feedScrollAnnouncer;
    IGFeedVideoCellManager_DEPRECATED *_videoCellManager;
    IGGuideNavigationBarView *_navigationBarView;
    IGGuide *_uneditedEntryGuide;
    NSArray *_uneditedEntryItems;
    IGGuideSeparatorObject *_separatorObject;
    NSString *_initialGuideItemPk;
    IGGuideHeaderSectionController *_headerSectionController;
    IGGuideItemsNetworkSource *_itemsNetworkSource;
    id <IGRequestToken> _publishRequest;
    IGGuideFooterView *_footerView;
    id <IGDirectShareSheetControlling> _directShareController;
    IGGuideLogger *_logger;
    IGGuideCreationLogger *_creationLogger;
    unsigned long long _entryPoint;
    IGGuideCreationUpsellItem *_creationUpsellItem;
    IGGuideCreationFlowPresenter *_creationFlowPresenter;
    _Bool _navigationBarOpaque;
    _Bool _editingEnabled;
    IGSessionTracker *_shoppingSessionTracker;
    id <IGGuideViewControllerMapDelegate> _mapDelegate;
    IGGuide *_guide;
    IGUserSession *_userSession;
    NSArray *_items;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) _Bool editingEnabled; // @synthesize editingEnabled=_editingEnabled;
@property(nonatomic) _Bool navigationBarOpaque; // @synthesize navigationBarOpaque=_navigationBarOpaque;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(retain, nonatomic) IGGuide *guide; // @synthesize guide=_guide;
@property(nonatomic) __weak id <IGGuideViewControllerMapDelegate> mapDelegate; // @synthesize mapDelegate=_mapDelegate;
@property(readonly, nonatomic) IGSessionTracker *shoppingSessionTracker; // @synthesize shoppingSessionTracker=_shoppingSessionTracker;
- (void)didCompleteAnimationTransition;
- (id)transitionZoomItemOverrideOnExit;
- (id)transitionZoomViewToItem:(id)arg1;
- (_Bool)shouldZoomToTransition;
- (void)keyboardObserver:(id)arg1 keyboardWillShowWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (void)_incrementCreationUpsellSeenCount;
- (long long)_creationUpsellSeenCount;
- (void)creationUpsellDidTapCreateGuide:(id)arg1;
- (void)addItemFlowControllerDidCancel:(id)arg1;
- (void)_scrollToGuideItemPk:(id)arg1 animated:(_Bool)arg2;
- (void)_addGuideItems:(id)arg1;
- (id)_guideItemWithMedia:(id)arg1 attachment:(id)arg2;
- (void)addItemFlowController:(id)arg1 didFinishWithSelectedItems:(id)arg2 guideType:(long long)arg3;
- (void)coverMediaPickerDidCancel:(id)arg1;
- (void)coverMediaPicker:(id)arg1 didSelectPHAsset:(id)arg2;
- (void)coverMediaPicker:(id)arg1 didSelectGuideMedia:(id)arg2;
- (void)guideItemReorderViewControllerDidCancel:(id)arg1;
- (void)guideItemReorderViewController:(id)arg1 didFinishWithItems:(id)arg2;
- (void)_handleMediaPickerCancel;
- (void)_updateMediaItems:(id)arg1 forListItemId:(id)arg2;
- (id)_guideItemForMedia:(id)arg1;
- (void)_addCreationSelectionItems:(id)arg1;
- (void)tabbedMediaPicker:(id)arg1 didSelectItems:(id)arg2 initialGuideTitle:(id)arg3;
- (void)guideItemSectionController:(id)arg1 didSelectPlaceInfo:(id)arg2;
- (void)guideItemSectionController:(id)arg1 wantsUpdateToAttachment:(id)arg2;
- (void)_removeGuideItem:(id)arg1;
- (void)guideItemSectionControllerDidTapRemoveItem:(id)arg1;
- (void)_deleteCollection;
- (void)_showDeleteCollectionConfirmation;
- (void)_updateGuideLocallyWithRemovedProduct:(id)arg1;
- (void)_removeProduct:(id)arg1 fromGuideItem:(id)arg2;
- (void)guideItemSectionController:(id)arg1 didTapRemoveProduct:(id)arg2;
- (void)_updateGuideLocallyWithRemovedMediaItem:(id)arg1;
- (void)_removeMediaItemFromGuide:(id)arg1;
- (void)guideItemSectionController:(id)arg1 didTapRemoveMediaItem:(id)arg2;
- (void)guideItemSectionContorller:(id)arg1 didTapAccount:(id)arg2;
- (void)guideItemSectionControllerDidEndEditingText:(id)arg1;
- (void)guideItemSectionControllerDidTapReorderItems:(id)arg1;
- (void)guideItemSectionControllerDidTapEditSettings:(id)arg1;
- (void)guideItemSectionControllerDidTapAddOrEditMedia:(id)arg1;
- (void)_updateItemsWithItem:(id)arg1;
- (void)guideItemSectionController:(id)arg1 didUpdateToDetailText:(id)arg2;
- (void)guideItemSectionController:(id)arg1 didUpdateToTitle:(id)arg2;
- (void)guideItemSectionController:(id)arg1 didTapMedia:(id)arg2;
- (_Bool)guideDetailSectionController:(id)arg1 shouldChangeText:(id)arg2 inRange:(struct _NSRange)arg3 replacementText:(id)arg4;
- (void)guideDetailSectionControllerDidEndEditing:(id)arg1;
- (void)guideDetailSectionController:(id)arg1 didUpdateToDetailText:(id)arg2;
- (void)guideHeaderDidTapEditCoverPhoto:(id)arg1;
- (void)_navigateToProfileForUser:(id)arg1;
- (_Bool)guideHeader:(id)arg1 shouldChangeText:(id)arg2 inRange:(struct _NSRange)arg3 replacementText:(id)arg4 numberOfLines:(long long)arg5;
- (void)guideHeaderDidTapOwnerAttribution:(id)arg1;
- (void)guideHeaderDidEndEditingTitle:(id)arg1;
- (void)guideHeader:(id)arg1 didUpdateToTitle:(id)arg2;
- (void)guideShareSheetDidTapSaveAsDraft:(id)arg1;
- (void)guideShareSheetDidTapShare:(id)arg1 shouldShareToFeed:(_Bool)arg2;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewWillScrollNearTop:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 finalizedTargetContentOffset:(struct CGPoint)arg3;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillScrollNearBottom:(id)arg1;
- (void)listAdapter:(id)arg1 didEndDisplayingObject:(id)arg2 atIndex:(long long)arg3;
- (void)listAdapter:(id)arg1 willDisplayObject:(id)arg2 atIndex:(long long)arg3;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (void)_updateBarElements;
- (_Bool)_canPublishGuide;
- (_Bool)_guideHasEdits;
- (void)directShareSheetController:(id)arg1 didTapRecipient:(id)arg2 selected:(_Bool)arg3;
- (void)directShareSheetControllerDidSelect:(id)arg1 sender:(id)arg2 directRecipients:(id)arg3 externalServices:(id)arg4 text:(id)arg5 selectedPostPk:(id)arg6;
- (void)directShareSheetControllerWillPresentConfirmationToast:(id)arg1;
- (void)directShareSheetControllerDidDismissConfirmationToast:(id)arg1;
- (void)directShareSheetControllerDidDismissReshareSheet:(id)arg1 willPresentConfirmationToast:(_Bool)arg2 hasShared:(_Bool)arg3;
- (void)_presentLikeSheet;
- (void)_presentCommentSheetWithKeyboard:(_Bool)arg1;
- (void)_presentDirectSheet;
- (void)_updateUFIAnimated:(_Bool)arg1;
- (void)UFIButtonBarDidTapOnCoWatch:(id)arg1;
- (void)UFIButtonBarDidTapOnRelatedPosts:(id)arg1;
- (void)UFIButtonBarDidTapOnExternalShare:(id)arg1;
- (void)UFIButtonBarDidLongPressOnSave:(id)arg1;
- (void)UFIButtonBarDidTapOnSave:(id)arg1;
- (void)UFIButtonBarDidTapOnLike:(id)arg1;
- (void)UFIButtonBarDidTapOnComment:(id)arg1;
- (void)UFIButtonBarDidLongPressOnSend:(id)arg1 gestureRecognizer:(id)arg2;
- (void)UFIButtonBarDidTapOnSend:(id)arg1;
- (void)_handlePublishError;
- (void)_handlePublishSuccessWithResponse:(id)arg1 didShareToFeed:(_Bool)arg2;
- (void)_publishGuideAsDraft:(_Bool)arg1 withShareToFeed:(_Bool)arg2;
- (void)_publishButtonTapped;
- (void)_closeButtonTapped;
- (void)_discardChangesAndEndEditing;
- (void)_handleShareViaSystemSheet;
- (void)_handleCopyLink;
- (void)_handleReportGuideFinishedWithTag:(unsigned long long)arg1;
- (void)_handleReportGuide;
- (void)_handleSetLikeCountDisabled:(_Bool)arg1;
- (void)_handleSetCommentingEnabled:(_Bool)arg1;
- (void)_handleEditGuideAction;
- (void)_moreButtonTapped;
- (void)_cancelButtonTapped;
- (void)_productsButtonTapped;
- (void)_mapButtonTapped;
- (void)_saveButtonTapped;
- (void)_updateFeedbackCounts;
- (void)mediaWasUpdated:(id)arg1 withChange:(long long)arg2;
- (void)_showMaxItemsToast;
- (void)guideFooterViewDidTapCommentCount:(id)arg1;
- (void)guideFooterViewDidTapLikeCount:(id)arg1;
- (id)_newGeneralAddItemPickerWithLastChosenLocation:(id)arg1;
- (void)guideFooterViewDidTapAddButton:(id)arg1;
- (_Bool)_footerViewShouldEnableEditing;
- (struct UIEdgeInsets)preferredContentInsets;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersNavigationBarHidden;
- (_Bool)wantsLayoutOnKeyboardChanges;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)_scrollToInitialGuideItemIfNeededAnimated:(_Bool)arg1;
- (void)_scrollToInitialGuideItemIfNeeded;
- (void)guideItemsNetworkSourceDidUpdate:(id)arg1;
- (void)_updateFeedbackListener;
- (void)_updateFooterViewVisibility;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithUserSession:(id)arg1 guide:(id)arg2 initialItemsResponse:(id)arg3 entryPoint:(unsigned long long)arg4 shoppingNavigationInfo:(id)arg5 shoppingSessionTracker:(id)arg6 initialGuideItemPk:(id)arg7;
- (id)initWithUserSession:(id)arg1 guide:(id)arg2 entryPoint:(unsigned long long)arg3 shoppingNavigationInfo:(id)arg4 shoppingSessionTracker:(id)arg5 initialGuideItemPk:(id)arg6;
- (id)initForCreationWithUserSession:(id)arg1 guideType:(long long)arg2 initialItems:(id)arg3 initialGuideTitle:(id)arg4 logger:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

