//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGInfoCenterConfiguration, IGUserSession, NSDate, NSMutableSet;

@interface IGInfoCenterLogger : NSObject
{
    IGUserSession *_userSession;
    NSMutableSet *_impressedIdentifiers;
    NSDate *_entryDate;
    IGInfoCenterConfiguration *_configuration;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGInfoCenterConfiguration *configuration; // @synthesize configuration=_configuration;
- (void)logStep:(long long)arg1 unitContainerModel:(id)arg2;
- (void)logStep:(long long)arg1;
- (id)initWithUserSession:(id)arg1 configuration:(id)arg2;

@end

