//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NSObject;

@interface IGIXTBloksEnvironment : NSObject
{
    id <NSObject> _clientContext;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <NSObject> clientContext; // @synthesize clientContext=_clientContext;
- (id)initWithClientContext:(id)arg1;

@end

