//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IGKragleMosaicGridController : NSObject
{
    struct __RSMosaicGridApi *_mosaicGridApi;
    _Bool _mosaicGridEnabled;
    _Bool _arloGridEnabled;
}

- (const struct __RSFeature *)createFeatureWithDataApi:(struct __RSDataApi *)arg1 dispatchHandler:(CDUnknownFunctionPointerType)arg2 dispatchContext:(void *)arg3 initialVideoSize:(struct CGSize)arg4;
- (void)sendCurrentVideoSize:(struct CGSize)arg1;
- (id)initWithLauncherSet:(id)arg1;
- (void)dealloc;

@end

