//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class CAGradientLayer, CALayer, CAShapeLayer, IGCoreTextView, IGLiveQuestionModel, IGLiveUserPayBadgeCountView, IGLiveUserPaySupporterBadgeView, IGProfilePictureImageView, IGStackLayout, IGUser, NSString, UIButton, UIImage, UITapGestureRecognizer, UIView, UIVisualEffectView;
@protocol IGLiveUpvoteableQuestionCellDelegate;

@interface IGLiveUpvoteableQuestionCell : UICollectionViewCell <UIGestureRecognizerDelegate>
{
    IGLiveQuestionModel *_model;
    UIView *_backgroundView;
    CALayer *_progressBarLayer;
    IGProfilePictureImageView *_profilePic;
    IGCoreTextView *_commentCoreTextView;
    UIButton *_likeCountLabel;
    UIButton *_deleteButton;
    UIButton *_reportButton;
    UIButton *_likeButton;
    UIVisualEffectView *_blurEffectView;
    CAShapeLayer *_blurEffectMask;
    IGStackLayout *_stackLayout;
    CAGradientLayer *_gradientLayer;
    CALayer *_backgroundColorLayer;
    long long _likeCount;
    long long _maxLikeCount;
    double _likeCountRatio;
    _Bool _isActive;
    long long _index;
    UITapGestureRecognizer *_tapGesture;
    IGLiveUserPaySupporterBadgeView *_supporterBadgeView;
    IGLiveUserPayBadgeCountView *_badgeCountView;
    UIImage *_supporterBadgeImage;
    UIImage *_badgeCountImage;
    _Bool _shouldUseBranding2021;
    unsigned long long _entryPoint;
    IGUser *_user;
    id <IGLiveUpvoteableQuestionCellDelegate> _delegate;
}

+ (double)preferredHeightForCellWithViewModel:(id)arg1 width:(double)arg2;
- (void).cxx_destruct;
@property(nonatomic) __weak id <IGLiveUpvoteableQuestionCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IGUser *user; // @synthesize user=_user;
@property(nonatomic) unsigned long long entryPoint; // @synthesize entryPoint=_entryPoint;
- (void)_accessibilityToggledLikeButton:(id)arg1;
- (id)accessibilityCustomActions;
- (id)accessibilityHint;
- (struct CGPoint)accessibilityActivationPoint;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (void)prepareForReuse;
- (void)setSelected:(_Bool)arg1;
- (void)configureWithViewModel:(id)arg1 shouldUseBranding2021:(_Bool)arg2;
- (void)_handleTapGesture:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_deleteButtonTapped:(id)arg1;
- (void)_reportButtonTapped:(id)arg1;
- (void)_toggledLikeButton;
- (void)_updateProfilePicView;
- (void)_updateLikeCountText;
- (void)_updateCoreTextView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

