//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGCache;

@interface IGLiveMediaCoverImageGenerator : NSObject
{
    IGCache *_imageCache;
    id _imageDownloadToken;
}

- (void).cxx_destruct;
- (void)cleanCachedMediaCoverImages;
- (void)_processDownloadedImage:(id)arg1 centerImageSize:(struct CGSize)arg2 targetImageSize:(struct CGSize)arg3 cacheKey:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)generateMediaCoverImageForUser:(id)arg1 centerImageSize:(struct CGSize)arg2 targetImageSize:(struct CGSize)arg3 completion:(CDUnknownBlockType)arg4;
- (id)init;

@end

