//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGGestureHandler-Protocol.h"
#import "IGLiveModeratorActionsDataSourceDelegate-Protocol.h"
#import "IGPartialModalSheetListener-Protocol.h"

@class IGListAdapter, IGLiveBroadcastLogger, IGLiveModeratorActionsDataSource, IGLiveModeratorActionsSheetView, IGUserSession, NSString;

@interface IGLiveModeratorActionsViewController : IGViewController <IGLiveModeratorActionsDataSourceDelegate, IGGestureHandler, IGPartialModalSheetListener>
{
    IGUserSession *_userSession;
    IGLiveBroadcastLogger *_logger;
    IGListAdapter *_listAdapter;
    IGLiveModeratorActionsDataSource *_dataSource;
    IGLiveModeratorActionsSheetView *_moderatorActionsSheetView;
    NSString *_broadcastId;
}

- (void).cxx_destruct;
- (void)_fetchModeratorActions;
- (id)_blockActionWithUser:(id)arg1 module:(id)arg2;
- (id)_followActionWithUser:(id)arg1 module:(id)arg2;
- (id)_hideLiveFromActionWithUser:(id)arg1;
- (void)_presentActionSheetModeratorActions:(id)arg1 module:(id)arg2;
- (void)liveModeratorActionsDataSource:(id)arg1 onUser:(id)arg2;
- (void)partialModalSheet:(id)arg1 didChangeState:(unsigned long long)arg2;
- (void)partialModalSheet:(id)arg1 willChangeState:(unsigned long long)arg2;
- (void)partialModalSheet:(id)arg1 didUpdateOffset:(double)arg2 presentationProgress:(double)arg3;
- (void)partialModalSheetDidDismiss:(id)arg1;
- (_Bool)canRespondToGesture:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 broadcastId:(id)arg2 logger:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

