//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class IGLiveCommentModel, IGProfilePictureImageView, IGTapButton, UIImageView, UILabel;

@interface IGLiveWaveCommentCellV2 : UICollectionViewCell
{
    IGLiveCommentModel *_comment;
    CDUnknownBlockType _waveButtonCallback;
    IGProfilePictureImageView *_profileImageView;
    UILabel *_commentHeadingLabel;
    UILabel *_commentBodyLabel;
    UIImageView *_waveProfileImageOverlay;
    IGTapButton *_waveTapButton;
    _Bool _isAnimating;
    _Bool _isSystemCommentV2Enabled;
}

+ (double)cellHeightForCommentWithUserName:(id)arg1 thatFits:(struct CGSize)arg2 isHeadingHidden:(_Bool)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) IGLiveCommentModel *comment; // @synthesize comment=_comment;
- (void)_animateWaveGrowWithCompletion:(CDUnknownBlockType)arg1;
- (void)_animateWaveShrinkWithCompletion:(CDUnknownBlockType)arg1;
- (void)_animateCommentLabelsSlide;
- (void)_animateProfilePhotoWaveWithCompletion:(CDUnknownBlockType)arg1;
- (void)_animateHideWaveButton;
- (void)_waveButtonTapped:(id)arg1;
- (void)animateHasWavedUpdateForCommentIsBroadcaster:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)configureWithComment:(id)arg1 isBroadcaster:(_Bool)arg2 module:(id)arg3 isSystemCommentV2Enabled:(_Bool)arg4 waveButtonCallback:(CDUnknownBlockType)arg5;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

