//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class IGLiveRealtimeSubmitQuestionBroadcasterGradientView, IGProfilePictureImageView, UIImageView;

@interface IGLiveRealtimeSubmitQuestionBroadcasterView : UIView
{
    IGLiveRealtimeSubmitQuestionBroadcasterGradientView *_gradientView;
    UIImageView *_questionIconImageView;
    UIView *_profilePictureImageViewContainer;
    IGProfilePictureImageView *_profilePictureImageView;
}

- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setBroadcaster:(id)arg1 analyticsModule:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

