//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGLiveBroadcastCharityUpdate, IGUser, IGUserSession, NSArray, NSString;
@protocol IGLiveDonationsDataSourceAnnouncer, IGRequestToken;

@interface IGLiveDonationsDataSource : NSObject
{
    IGUserSession *_userSession;
    NSString *_broadcastId;
    NSString *_analyticsModule;
    IGLiveBroadcastCharityUpdate *_latestUpdate;
    id <IGLiveDonationsDataSourceAnnouncer> _announcer;
    id <IGRequestToken> _listRequest;
    IGUser *_fundraiserCharity;
    NSArray *_donations;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *donations; // @synthesize donations=_donations;
@property(readonly, nonatomic) IGUser *fundraiserCharity; // @synthesize fundraiserCharity=_fundraiserCharity;
- (void)_announceListFetchFinished;
- (void)_handleFetchFailure;
- (void)_handleFetchSuccessWithResponse:(id)arg1;
- (void)addListener:(id)arg1;
- (void)handleUpdate:(id)arg1;
- (_Bool)isLoading;
- (void)fetchDonationsList;
- (id)liveFundraiserId;
- (id)formattedAmountRaised;
- (id)formattedDonationsCount;
- (long long)numberOfDonations;
- (id)currentSessionFormattedAmountRaised;
- (id)currentSessionFormattedDonationsCount;
- (long long)currentSessionNumberOfDonations;
- (id)initWithUserSession:(id)arg1 fundraiserCharity:(id)arg2 broadcastId:(id)arg3 analyticsModule:(id)arg4;

@end

