//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBIvarBasedEqualityObject.h>

@class NSString;

@interface IGLiveUserKey : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    NSString *_igid_igid;
    NSString *_eimu_eimu;
}

+ (id)igidWithIgid:(id)arg1;
+ (id)eimuWithEimu:(id)arg1;
- (void).cxx_destruct;
- (void)matchIgid:(CDUnknownBlockType)arg1 eimu:(CDUnknownBlockType)arg2;

@end

