//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGLiveBroadcastShoppingPinnedProductEvent, IGLiveShoppingPinnedProductService, IGLiveShoppingPinnedProductViewModel, NSString;

@protocol IGLiveShoppingPinnedProductServiceDelegate <NSObject>
- (void)shoppingPinnedProductService:(IGLiveShoppingPinnedProductService *)arg1 didRequestPresentCheckoutWithViewModel:(IGLiveShoppingPinnedProductViewModel *)arg2;
- (void)shoppingPinnedProductServiceDidRequestPresentShoppingEntrypoint:(IGLiveShoppingPinnedProductService *)arg1;
- (void)shoppingPinnedProductService:(IGLiveShoppingPinnedProductService *)arg1 didLaunchPinnedProductWithViewModel:(IGLiveShoppingPinnedProductViewModel *)arg2;
- (void)shoppingPinnedProductService:(IGLiveShoppingPinnedProductService *)arg1 didRequestPresentShoppingCartWithMerchantPk:(NSString *)arg2;
- (void)shoppingPinnedProductService:(IGLiveShoppingPinnedProductService *)arg1 didRequestPresentPinnedProductPickerWithViewModel:(IGLiveShoppingPinnedProductViewModel *)arg2;
- (void)shoppingPinnedProductService:(IGLiveShoppingPinnedProductService *)arg1 didUpdatePinnedProductWithViewModel:(IGLiveShoppingPinnedProductViewModel *)arg2 previousViewModel:(IGLiveShoppingPinnedProductViewModel *)arg3;
- (void)shoppingPinnedProductService:(IGLiveShoppingPinnedProductService *)arg1 didReceivePinnedProductEvent:(IGLiveBroadcastShoppingPinnedProductEvent *)arg2;
@end

