//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGRealtimeServerPayloadHandler-Protocol.h"

@class IGRealtimeMqttClient, IGRealtimeRetriableSubscription, IGUserSession, NSMutableArray, NSString;
@protocol IGLiveInteractivityServiceDelegate;

@interface IGLiveInteractivityService : NSObject <IGRealtimeServerPayloadHandler>
{
    IGUserSession *_userSession;
    IGRealtimeMqttClient *_mqttClient;
    IGRealtimeRetriableSubscription *_qaRealtimeSubscription;
    IGRealtimeRetriableSubscription *_badgesRealtimeSubscription;
    NSString *_broadcastId;
    _Bool _useRSClient;
    NSMutableArray *_qaStreamIDs;
    NSMutableArray *_badgesStreamIDs;
    id <IGLiveInteractivityServiceDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGLiveInteractivityServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_handleBadgesStatusEvent:(id)arg1;
- (void)_handleQuestionSubmissionStatusEvent:(id)arg1;
- (void)_handleActiveQuestionEventPayload:(id)arg1;
- (void)handlePayload:(id)arg1;
- (void)fetchPostLiveQuestionEventsWithCompletion:(CDUnknownBlockType)arg1;
- (void)unsubscribeFromBadgesStatus;
- (void)_subscribeToBadgesRSClient;
- (void)_subscribeToBadgesRawMQTT;
- (void)subscribeToBadgesStatus;
- (void)submitQuestion:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)enableQuestionSubmission:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)unsubscribeFromQAInteractivity;
- (void)_subscribeToQAInteractivityRSClient;
- (void)_subscribeToQAInteractivityRawMQTT;
- (void)subscribeToQAInteractivity;
- (void)_updateQuestionWithQuestion:(id)arg1 selectionState:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeQuestion:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)publishQuestion:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithBroadcastId:(id)arg1 userSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

