//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGContentFilterClientProtocol-Protocol.h"
#import "IGMessageFilterClientProtocol-Protocol.h"
#import "IGUserUpdatedListener-Protocol.h"

@class IGMessageFilterLogger, IGObjectDiskStorage, IGUser, NSArray, NSHashTable, NSMutableDictionary, NSNumber, NSString;
@protocol IGContentFilterManagerProtocol, IGMessageFilterCustomDictionaryProtocol, IGUserLauncherSetProviding, IGUserUpdatedAnnouncer;

@interface IGMessageFilterClient : NSObject <IGContentFilterClientProtocol, IGUserUpdatedListener, IGMessageFilterClientProtocol>
{
    id <IGContentFilterManagerProtocol> _contentFilterManager;
    id <IGUserLauncherSetProviding> _launcherSetProvider;
    id <IGUserUpdatedAnnouncer> _userUpdatedAnnouncer;
    IGUser *_user;
    id <IGMessageFilterCustomDictionaryProtocol> _customDictionary;
    NSHashTable *_subscribers;
    NSHashTable *_dictionaries;
    IGObjectDiskStorage *_settingsStorage;
    NSMutableDictionary *_settings;
    IGMessageFilterLogger *_logger;
}

- (void).cxx_destruct;
- (_Bool)_globalDictionariesEnabled;
- (_Bool)_customDictionaryEnabled;
- (void)_setSettingsObject:(id)arg1 forKey:(id)arg2;
- (void)_syncDictionaryStatuses;
- (void)_updateCustomDictionary:(id)arg1;
- (void)userWasUpdated:(id)arg1;
- (void)markEndThreadsGroupFilteringWithNumberOfThreads:(long long)arg1 numberOfMessages:(long long)arg2 numberOfScannedMessages:(long long)arg3;
- (void)startThreadsGroupFiltering;
- (void)removeCustomDictionarySubscriber:(id)arg1;
- (void)addCustomDictionarySubscriber:(id)arg1;
- (id)findAllFilteredMatchesForInput:(id)arg1;
- (id)findFirstFilteredMatchForInput:(id)arg1;
- (void)preloadCustomDictionary;
- (void)_setDictionariesEnabled:(_Bool)arg1 predicate:(CDUnknownBlockType)arg2;
- (void)setGlobalDictionaryIsEnabled:(_Bool)arg1;
- (void)setCustomDictionaryIsEnabled:(_Bool)arg1;
- (void)onDictionaryReady:(id)arg1;
@property(readonly, nonatomic) _Bool isEnabled;
@property(readonly, nonatomic) NSArray *locales;
@property(readonly, nonatomic) NSNumber *clientId;
- (void)setup;
- (void)dealloc;
- (id)initWithContentFilterManager:(id)arg1 launcherSetProvider:(id)arg2 userUpdatedAnnouncer:(id)arg3 logger:(id)arg4 user:(id)arg5 diskManager:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

