//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class IGMonetizationPlatformMultiLineViewModel, IGStackLayout;

@interface IGMonetizationPlatformMultiLineView : UIView
{
    IGStackLayout *_titleStackLayout;
    UIView *_separator;
    IGMonetizationPlatformMultiLineViewModel *_viewModel;
}

+ (double)preferredHeightForCellWithWidth:(double)arg1 titles:(id)arg2 showSeparator:(_Bool)arg3;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithViewModel:(id)arg1;

@end

