//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGMonetizationEligibilityEligibleViewDelegate-Protocol.h"
#import "IGMonetizationEligibilityNotEligibleViewDelegate-Protocol.h"

@class IGMonetizationEligibilityEligibleView, IGMonetizationEligibilityNotEligibleView, IGMonetizationEligibilityStatusDataSource, IGMonetizationEligibilityStatusViewModel, IGUserSession, NSString, UIActivityIndicatorView;

@interface IGMonetizationEligibilityStatusViewController : IGViewController <IGMonetizationEligibilityEligibleViewDelegate, IGMonetizationEligibilityNotEligibleViewDelegate>
{
    IGUserSession *_userSession;
    IGMonetizationEligibilityStatusDataSource *_dataSource;
    IGMonetizationEligibilityStatusViewModel *_viewModel;
    IGMonetizationEligibilityEligibleView *_eligibleView;
    IGMonetizationEligibilityNotEligibleView *_ineligibleView;
    UIActivityIndicatorView *_loadingIndicatorView;
}

- (void).cxx_destruct;
- (void)_presentBrowserForUrl:(id)arg1;
- (void)_handleAppealsDataRequestFailure;
- (void)_updateViewWithAppealsData:(id)arg1;
- (void)_handleViolationsRequestFailure;
- (void)_updateViewWithViolations:(id)arg1;
- (void)_fetchIneligibilityData;
- (void)_displayRefreshFailure;
- (void)_displayActivityIndicatorView:(_Bool)arg1;
- (void)_showEligiblityView;
- (long long)_appealSourceType;
- (void)monetizationEligibilityNotEligibleViewDidTapViolationHelpCenterLink:(id)arg1 violationType:(id)arg2;
- (void)monetizationEligibilityNotEligibleViewDidTapHelpCenterLink:(id)arg1;
- (void)monetizationEligibilityNotEligibleViewDidTapAppealButton;
- (void)_requestAppealData;
- (void)_requestViolationData;
- (void)_fetchEligibilityStatus;
- (void)monetizationEligibilityEligibleViewDidTapPrimaryButton;
- (void)monetizationEligibilityEligibleViewDidTapLearnMoreButton:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 analyticsModule:(id)arg2 dataSource:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

