//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGRealtimeServerPayloadHandler-Protocol.h"

@class IGMwsMessageConfirmHelper, IGVideoCallStartupHelper, NSMutableSet, NSString;

@interface IGMwsRealtimeTopicHandlingService : NSObject <IGRealtimeServerPayloadHandler>
{
    NSMutableSet *_subscriptions;
    IGVideoCallStartupHelper *_videoCallStartupHelper;
    IGMwsMessageConfirmHelper *_liveWithConfirmHelper;
}

- (void).cxx_destruct;
- (void)removeSubscription:(id)arg1;
- (id)registerHandler:(id)arg1 payloadType:(long long)arg2 sessionId:(id)arg3;
- (void)handlePayload:(id)arg1;
- (id)initWithStartupHelper:(id)arg1 networker:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

