//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol IGAnalyticsEventLoggingProtocol;

@interface IGNotificationSettingsLogger : NSObject
{
    NSString *_module;
    id <IGAnalyticsEventLoggingProtocol> _analyticsLogger;
}

- (void).cxx_destruct;
- (void)logChangeNotificationSettingWithRenderType:(id)arg1 contentType:(id)arg2 settingValue:(id)arg3;
- (void)logChangeNotificationSettingRequestMadeWithSuccess:(_Bool)arg1 uiType:(id)arg2 contentType:(id)arg3 settingValue:(id)arg4;
- (void)logFetchNotificationSettingsRequestMadeWithSuccess:(_Bool)arg1;
- (id)initWithAnalyticsLogger:(id)arg1 module:(id)arg2;

@end

