//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGDirectDebitCredentialFields, NSArray;

@protocol IGPayoutOnboardingPayoutMethodViewControllerDelegate <NSObject>
- (void)payoutOnboardingPayoutMethodViewControllerDidTapSkip;
- (void)payoutOnboardingPayoutMethodViewControllerDidTapNext:(IGDirectDebitCredentialFields *)arg1 payoutMethod:(long long)arg2 onboardingTypes:(NSArray *)arg3 subtypes:(NSArray *)arg4;
@end

