//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIButton, UILabel;
@protocol IGPendingRequestInFeedBannerCellDelegate;

@interface IGPendingRequestInFeedBannerCell : UICollectionViewCell
{
    UILabel *_titleLabel;
    UIButton *_actionButton;
    UIButton *_moreButton;
    UILabel *_dotSeparator;
    id <IGPendingRequestInFeedBannerCellDelegate> _delegate;
}

+ (double)_maxTitleLabelWidthWithCellWidth:(double)arg1;
+ (double)heightForCellWithWidth:(double)arg1 title:(id)arg2 actionLabel:(id)arg3 smallerBottomPadding:(_Bool)arg4;
- (void).cxx_destruct;
@property(nonatomic) __weak id <IGPendingRequestInFeedBannerCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_didTapMoreButton;
- (void)_didTapActionButton;
- (void)configureWithTitle:(id)arg1 actionLabel:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

