//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IGPromoteViewController.h"

#import "IGActionRowSectionControllerDelegate-Protocol.h"
#import "IGListAdapterDataSource-Protocol.h"
#import "IGPartialModalSheetListener-Protocol.h"
#import "IGPromoteBillingWizardReactEventListener-Protocol.h"
#import "IGPromoteCheckMarkSectionControllerDeleagate-Protocol.h"
#import "IGPromoteChevronSectionControllerDelegate-Protocol.h"
#import "IGPromoteHeaderSectionControllerDelegate-Protocol.h"
#import "IGPromoteReviewPaymentCardSectionControllerDelegate-Protocol.h"
#import "IGPromoteTitleSubtitleSectionControllerDelegate-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class IGBoostPostLogger, IGBottomButtonsView, IGListAdapter, IGPromoteDataStore, IGPromoteErrorDataModel, IGPromoteReviewViewModel, IGUserSession, NSString, UIActivityIndicatorView, UICollectionView;
@protocol IGPromoteReviewViewControllerDelegate;

@interface IGPromoteReviewViewController : IGPromoteViewController <IGListAdapterDataSource, UICollectionViewDelegate, IGPromoteTitleSubtitleSectionControllerDelegate, IGPromoteCheckMarkSectionControllerDeleagate, IGPromoteReviewPaymentCardSectionControllerDelegate, IGPromoteHeaderSectionControllerDelegate, IGPromoteChevronSectionControllerDelegate, IGPartialModalSheetListener, IGActionRowSectionControllerDelegate, IGPromoteBillingWizardReactEventListener>
{
    IGBottomButtonsView *_createPromotionButton;
    UICollectionView *_collectionView;
    IGListAdapter *_adapter;
    IGUserSession *_session;
    IGBoostPostLogger *_logger;
    long long _viewState;
    UIActivityIndicatorView *_spinner;
    _Bool _isFetching;
    IGPromoteErrorDataModel *_errorDataModel;
    _Bool _setCreationPrimaryButtonEnabled;
    _Bool _didLaunchBillingWizardWhenCreatingPromotion;
    _Bool _shouldSubmitPromotionCreationAfterCompletingBillingWizard;
    _Bool _isDestinationRefreshEnabled;
    unsigned long long _rebrandTestGroup;
    id <IGPromoteReviewViewControllerDelegate> _delegate;
    IGPromoteReviewViewModel *_reviewViewModel;
    IGPromoteDataStore *_dataStore;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGPromoteDataStore *dataStore; // @synthesize dataStore=_dataStore;
@property(copy, nonatomic) IGPromoteReviewViewModel *reviewViewModel; // @synthesize reviewViewModel=_reviewViewModel;
@property(nonatomic) __weak id <IGPromoteReviewViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)reloadView;
- (void)_blockCreationIfNeeded;
- (void)_didFinishCreatePromote;
- (void)_onDiscardDraftTapped;
- (void)_showDiscardDraftActionSheet;
- (void)_validateAndLogCachedBUAT;
- (void)_openPaymentsVC;
- (void)_openAdPreview;
- (_Bool)_shouldBlockCreateWithNonDiscriminationPolicy;
- (void)_pushRequiredWizardViewControllerWithWizardName:(id)arg1;
- (void)_pushAddPaymentViewController;
- (void)_fetchData;
- (void)_openWebViewWithURL:(id)arg1 loggingComponent:(id)arg2;
- (void)_setUpNavigationBar;
- (void)_setUpPromotionButtonView;
- (void)_setUpContentViews;
- (void)_setBackButtonEnabled:(_Bool)arg1;
- (id)_flowTypeStringForLogging:(long long)arg1;
- (void)_updateViewModel;
- (void)_refreshMedia;
- (void)_updateMediaAfterCreationSuccess;
- (void)_setViewState:(long long)arg1;
- (void)billingWizardDidReturnWithWizardName:(id)arg1 returnCode:(id)arg2;
- (void)partialModalSheet:(id)arg1 didChangeState:(unsigned long long)arg2;
- (void)partialModalSheet:(id)arg1 willChangeState:(unsigned long long)arg2;
- (void)partialModalSheet:(id)arg1 didUpdateOffset:(double)arg2 presentationProgress:(double)arg3;
- (void)partialModalSheetDidDismiss:(id)arg1;
- (void)actionRowSectionControllerDidTapActionButton:(id)arg1 viewModel:(id)arg2;
- (void)promoteHeaderSectionController:(id)arg1 didTapSubtitle:(id)arg2;
- (void)promoteHeaderSectionController:(id)arg1 didTapURL:(id)arg2;
- (void)promoteReviewPaymentCardSectionController:(id)arg1 didTapSubtitleWithViewModel:(id)arg2;
- (void)promoteChevronSectionController:(id)arg1 didTapCellWithViewModel:(id)arg2;
- (void)promoteCheckMarkSectionController:(id)arg1 didTapCheckMarkWithViewModel:(id)arg2;
- (void)promoteCheckMarkSectionController:(id)arg1 didTapSubtitleWithViewModel:(id)arg2;
- (void)promoteTitleSubtitleSectionController:(id)arg1 didTapSubtitleLink:(id)arg2;
- (void)promoteTitleSubtitleSectionController:(id)arg1 didTapCellTitleWithViewModel:(id)arg2;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (_Bool)_isPoliticalAd;
- (void)_didExitReviewScreenInDraftFlow;
- (void)_onNormalPromoteCancelBarButtonTapped;
- (void)_onBackBarButtonTapped;
- (void)_submitPromotionCreation;
- (void)_onCreatePromotionPressed;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithSession:(id)arg1 logger:(id)arg2 dataStore:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

