//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol IGPromoteAdPreviewDataStoreProviding <NSObject>
@property(readonly, copy, nonatomic) NSString *mediaId;
@property(nonatomic) _Bool isReelsPlacementEligible;
@property(nonatomic) _Bool isExplorePlacementEligible;
@property(nonatomic) _Bool isStoryPlacementEligible;
@property(nonatomic) _Bool isFeedPlacementEligible;
- (long long)promotionType;
@end

