//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGBadgeListener-Protocol.h"
#import "IGPartialModalSheetListener-Protocol.h"
#import "IGSwitchUsersControllerDelegate-Protocol.h"
#import "IGSwitchUsersControllerDisplayDelegate-Protocol.h"
#import "IGSwitchUsersControllerFavoritesDelegate-Protocol.h"

@class IGBadgingLogger, IGChevronTitleButton, IGFavoritesPresentationManager, IGOneTapLoginSwitchErrorManager, IGPartialModalSheetViewController, IGSwitchUsersController, IGUserSession, NSString, UIViewController;
@protocol IGAccountSwitcherPresenting, IGProfileTitleViewControllerDelegate, IGSwitchUsersControllerDelegate;

@interface IGProfileTitleViewController : NSObject <IGSwitchUsersControllerDelegate, IGSwitchUsersControllerFavoritesDelegate, IGSwitchUsersControllerDisplayDelegate, IGBadgeListener, IGPartialModalSheetListener>
{
    IGUserSession *_userSession;
    UIViewController *_viewController;
    id <IGAccountSwitcherPresenting> _accountSwitcherPresenter;
    IGOneTapLoginSwitchErrorManager *_accountSwitcherErrorManager;
    _Bool _isMainProfileSurface;
    unsigned long long _entryPoint;
    _Bool _shouldShowChevron;
    _Bool _shouldShowAvatar;
    unsigned long long _badgeType;
    unsigned long long _switchUsersMode;
    _Bool _enableAddAccount;
    NSString *_module;
    _Bool _canShowCloseFriends;
    NSString *_title;
    NSString *_subtitle;
    _Bool _canShowMultipleAccountsUpsell;
    IGChevronTitleButton *_titleButton;
    IGSwitchUsersController *_switchUsersController;
    IGPartialModalSheetViewController *_halfSheetViewController;
    IGBadgingLogger *_badgingLogger;
    _Bool _showCustomNavBar;
    IGFavoritesPresentationManager *_favoritesPresentationManager;
    _Bool _hasFeaturedAccounts;
    id <IGProfileTitleViewControllerDelegate> _delegate;
    id <IGSwitchUsersControllerDelegate> _switchUserDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hasFeaturedAccounts; // @synthesize hasFeaturedAccounts=_hasFeaturedAccounts;
@property(nonatomic) __weak id <IGSwitchUsersControllerDelegate> switchUserDelegate; // @synthesize switchUserDelegate=_switchUserDelegate;
@property(nonatomic) __weak id <IGProfileTitleViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didUpdateBadge:(id)arg1;
- (void)switchUsersControllerDidAppear:(id)arg1 users:(id)arg2;
- (void)switchUserController:(id)arg1 didTapCloseFriendsButtonForUser:(id)arg2;
- (void)switchUserController:(id)arg1 didTapFollowersButtonForUser:(id)arg2;
- (void)switchUsersControllerDidSelectRowWithCurrentUser:(id)arg1;
- (void)switchUsersControllerDidSelectAddAccountRow:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)switchUsersController:(id)arg1 tableViewDidSelectRowWithOneTapLoginSwitchAccount:(id)arg2;
- (void)switchUsersController:(id)arg1 tableViewDidSelectRowWithUser:(id)arg2;
- (void)partialModalSheet:(id)arg1 didChangeState:(unsigned long long)arg2;
- (void)partialModalSheet:(id)arg1 willChangeState:(unsigned long long)arg2;
- (void)partialModalSheet:(id)arg1 didUpdateOffset:(double)arg2 presentationProgress:(double)arg3;
- (void)partialModalSheetDidDismiss:(id)arg1;
- (void)_showBadgeView:(_Bool)arg1 count:(long long)arg2;
- (void)_onMultipleAccountsTapped:(id)arg1;
- (void)_onTitleLabelTapped:(id)arg1;
- (void)_presentSwitchUsersTableViewAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_displaySwitchUsersTableView:(_Bool)arg1 animated:(_Bool)arg2 transitionDuration:(double)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_displaySwitchUsersTableView:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_newMultipleAccountsTitleButtonWithTitle:(id)arg1 showLock:(_Bool)arg2 user:(id)arg3 maxWidth:(double)arg4;
- (id)_newSingleUserTitleViewWithTitle:(id)arg1 showLock:(_Bool)arg2 showVerifiedBadge:(_Bool)arg3 showCloseFriendsBadge:(_Bool)arg4;
- (void)willAppear;
- (void)removeTabBarOverlay;
- (void)hideSwitchControlWithCompletion:(CDUnknownBlockType)arg1;
- (void)_toggleSwitchUsersControl;
- (void)_updateFrameForTitleView:(id)arg1;
- (void)updateSelectedUser:(id)arg1;
- (void)_updateTitleViewForUser:(id)arg1;
- (id)generateTitleViewWithRightBarButtonItems:(id)arg1 leftBarButtonItems:(id)arg2 user:(id)arg3;
- (void)updateTitleForUser:(id)arg1;
- (id)initWithUserSession:(id)arg1 viewController:(id)arg2 configuration:(id)arg3 accountSwitcherPresenter:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

