//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGPromoteTextInputCheckMarkCellViewModel, IGPromoteTextInputCheckMarkSectionController;

@protocol IGPromoteTextInputCheckMarkSectionControllerDelegate <NSObject>
- (_Bool)promoteTextInputCheckMarkSectionController:(IGPromoteTextInputCheckMarkSectionController *)arg1 shouldUpdateCheckMarkStatusInModel:(IGPromoteTextInputCheckMarkCellViewModel *)arg2;
- (void)promoteTextInputCheckMarkSectionController:(IGPromoteTextInputCheckMarkSectionController *)arg1 didChangeTextFieldInModel:(IGPromoteTextInputCheckMarkCellViewModel *)arg2;
@end

