//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IGRegistrationDoBSupportContainerViewModel : NSObject
{
    NSString *_title;
    NSString *_subtitle;
    NSString *_actionText;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *actionText; // @synthesize actionText=_actionText;
@property(readonly, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 actionText:(id)arg3;

@end

