//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGUserSessionEndingObject-Protocol.h"

@class IGRealtimePatchEventForwarder, IGRequestStreamRollout, IGRequestStreamSubscription, NSMutableArray, NSString, THStatusService;

@interface IGRequestStreamSubscriptions : NSObject <IGUserSessionEndingObject>
{
    NSObject *_lock;
    IGRequestStreamRollout *_requestStreamRollout;
    IGRequestStreamSubscription *_requestStreamSubscription;
    NSMutableArray *_streamIDs;
    NSString *_userPK;
    IGRealtimePatchEventForwarder *_realtimePatchEventForwarder;
    THStatusService *_statusService;
}

- (void).cxx_destruct;
- (void)userSessionWillEnd;
- (void)subscribe;
- (void)_handleStatusPayload:(id)arg1;
- (void)_handleTypingIndicatorPayload:(id)arg1;
- (id)initWithSession:(id)arg1;

@end

