//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;

@protocol IGReshareHubLogging <NSObject>
- (void)logSendWithRecipientIDs:(NSArray *)arg1 mediaID:(NSString *)arg2;
- (void)logSelectMediaWithID:(NSString *)arg1 tab:(long long)arg2;
- (void)logReshareHubOpenWithInitialTab:(long long)arg1;
@end

