//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AVAudioSession, IGRTCVideoCallConfiguration, IGRTCVideoCallJoinContext, IGRTCVideoCallJoinInfo, IGVideoCallCapabilities, NSArray, NSString;
@protocol IGRTCVideoCallControllerConnectionDelegate, IGRTCVideoCallControllerParticipantDelegate;

@protocol IGRTCVideoCallControllerIntf <NSObject>
- (void)callKitDidDeactivateAudioSession:(AVAudioSession *)arg1;
- (void)callKitDidActivateAudioSession:(AVAudioSession *)arg1;
- (void)restartAudioDevice;
- (void)captureVideoChangedToSize:(struct CGSize)arg1;
- (void)processVideo:(struct __CVBuffer *)arg1;
- (void)leaveWithReason:(long long)arg1;
- (void)answerDropInCallWithAudioOnly:(_Bool)arg1;
- (void)joinCall:(IGRTCVideoCallJoinInfo *)arg1 joinContext:(IGRTCVideoCallJoinContext *)arg2 waterfallId:(NSString *)arg3 manualAudio:(_Bool)arg4 configuration:(IGRTCVideoCallConfiguration *)arg5 threadId:(NSString *)arg6 threadIdV2:(NSString *)arg7 isE2eeMandated:(_Bool)arg8 inNetworkRoomPrefix:(_Bool)arg9 threadUsers:(NSArray *)arg10 capabilities:(IGVideoCallCapabilities *)arg11 completion:(void (^)(IGRTCKragleCall *))arg12;
- (void)setVideoEnabled:(_Bool)arg1;
- (_Bool)videoEnabled;
- (void)setAudioEnabled:(_Bool)arg1;
- (_Bool)audioEnabled;
- (void)setConnectionDelegate:(id <IGRTCVideoCallControllerConnectionDelegate>)arg1;
- (void)setVideoDelegate:(id <IGRTCVideoCallControllerParticipantDelegate>)arg1;
@end

