//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGListDiffable-Protocol.h"

@class IGEmptyFeedText, NSString, UIImage;

@interface IGSavedProductsCollectionEmptyViewModel : NSObject <IGListDiffable>
{
    NSString *_identifier;
    UIImage *_icon;
    IGEmptyFeedText *_title;
    IGEmptyFeedText *_subtitle;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGEmptyFeedText *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) IGEmptyFeedText *title; // @synthesize title=_title;
@property(readonly, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithListKitIdentifier:(id)arg1 icon:(id)arg2 title:(id)arg3 subtitle:(id)arg4;

@end

