//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGMediaUploaderDelegate-Protocol.h"

@class IGMediaUploader, NSString;

@interface IGSharedCanvasImageUploadManager : NSObject <IGMediaUploaderDelegate>
{
    IGMediaUploader *_mediaUploader;
    NSString *_uploadID;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failureBlock;
}

- (void).cxx_destruct;
- (void)mediaUploader:(id)arg1 didChangeProgress:(double)arg2;
- (void)mediaUploader:(id)arg1 didFailWithReason:(id)arg2;
- (void)mediaUploaderDidSucceed:(id)arg1 withResponse:(id)arg2;
- (void)_cancelInFlightUploadIfNecessary;
- (void)uploadCustomImage:(id)arg1 canvasId:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

