//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "IGLiveShoppingIncentiveTimerDelegate-Protocol.h"

@class IGCoreTextView, IGLiveShoppingIncentiveTimer, IGShoppingIGFundedIncentive, IGUserSession, NSString, UIView;
@protocol IGCoreTextLinkHandler, IGShoppingIGFundedIncentivesMegaphoneOptimizationVariant1CellDelegate;

@interface IGShoppingIGFundedIncentivesMegaphoneOptimizationVariant1Cell : UICollectionViewCell <IGLiveShoppingIncentiveTimerDelegate>
{
    IGShoppingIGFundedIncentive *_incentive;
    IGCoreTextView *_firstTextView;
    IGCoreTextView *_secondTextView;
    UIView *_giftCardImageView;
    IGLiveShoppingIncentiveTimer *_incentiveTimer;
    _Bool _isCountdownEnabled;
    IGUserSession *_userSession;
    id <IGShoppingIGFundedIncentivesMegaphoneOptimizationVariant1CellDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGShoppingIGFundedIncentivesMegaphoneOptimizationVariant1CellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)liveShoppingIncentiveTimerDidFire:(id)arg1 withTimerState:(long long)arg2;
@property(nonatomic) __weak id <IGCoreTextLinkHandler> linkHandler;
- (void)configureWithIncentive:(id)arg1 isCountdownEnabled:(_Bool)arg2 session:(id)arg3;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

