//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGListSectionController.h>

#import "IGListAdapterDataSource-Protocol.h"

@class IGListAdapter, IGSessionTracker, IGShoppingMerchantCarouselViewModel, IGUserSession, NSString;
@protocol IGShoppingMerchantCarouselLoggingProvider;

@interface IGShoppingMerchantCarouselSectionController : IGListSectionController <IGListAdapterDataSource>
{
    IGUserSession *_userSession;
    id <IGShoppingMerchantCarouselLoggingProvider> _loggingProvider;
    IGSessionTracker *_shoppingSessionTracker;
    IGListAdapter *_listAdapter;
    IGShoppingMerchantCarouselViewModel *_viewModel;
}

- (void).cxx_destruct;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (void)didUpdateToObject:(id)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (long long)numberOfItems;
- (id)initWithUserSession:(id)arg1 loggingProvider:(id)arg2 shoppingSessionTracker:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

