//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGPartialModalSheetListener-Protocol.h"
#import "IGResultsFilterViewControllerDelegate-Protocol.h"

@class IGPartialModalSheetViewController, IGResultsFilterModelsMetadata, IGSearchSession, IGSessionTracker, IGUserSession, NSString;
@protocol IGResultsFilterServiceManagerType, IGShoppingHomeFilterManagerDelegate;

@interface IGShoppingHomeFilterManager : NSObject <IGPartialModalSheetListener, IGResultsFilterViewControllerDelegate>
{
    IGUserSession *_userSession;
    IGSearchSession *_searchSession;
    IGSessionTracker *_shoppingSessionTracker;
    NSString *_analyticsModule;
    NSString *_submodule;
    struct UIEdgeInsets _preferredContentInsets;
    long long _destinationType;
    long long _filterDisplayType;
    IGResultsFilterModelsMetadata *_resultsFilterMetadata;
    id <IGResultsFilterServiceManagerType> _filterServiceManager;
    IGPartialModalSheetViewController *_shoppingFilterPartialModalSheetVC;
    id <IGShoppingHomeFilterManagerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGShoppingHomeFilterManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)partialModalSheet:(id)arg1 didChangeState:(unsigned long long)arg2;
- (void)partialModalSheet:(id)arg1 willChangeState:(unsigned long long)arg2;
- (void)partialModalSheet:(id)arg1 didUpdateOffset:(double)arg2 presentationProgress:(double)arg3;
- (void)partialModalSheetDidDismiss:(id)arg1;
- (double)resultsFilterSearchBarTopInset:(id)arg1;
- (void)resultsFilterViewControllerShouldPartiallyCollapse:(id)arg1;
- (void)resultsFilterViewController:(id)arg1 didFocusOnSearchBar:(id)arg2;
- (_Bool)resultsFilterViewControllerIsInFullyDisplayedState;
- (_Bool)resultsFilterViewController:(id)arg1 hasUnappliedFiltersMetaData:(id)arg2;
- (void)resultsFilterViewControllerDidApplyFilters:(id)arg1 selectedFiltersMetadata:(id)arg2 searchText:(id)arg3;
- (_Bool)_shouldRefreshViewInlineForSelectedFiltersMetadata:(id)arg1;
- (void)_setUpFilterServiceManager;
- (id)_taxonomySurfaceConfigFromFilterConfigs;
- (void)updateWithFilterConfigs:(id)arg1;
- (void)presentRangeFilterHalfSheetWithNavigationController:(id)arg1 config:(id)arg2 navigationInfo:(id)arg3 loggingExtras:(id)arg4;
- (void)presentListFilterHalfSheetWithNavigationController:(id)arg1 config:(id)arg2 navigationInfo:(id)arg3 loggingExtras:(id)arg4;
- (void)presentCategoryHalfSheetWithNavigationController:(id)arg1 taxonomyConfig:(id)arg2 filterDisplayType:(long long)arg3 navigationInfo:(id)arg4 loggingExtras:(id)arg5 shouldEnableSearch:(_Bool)arg6;
- (void)presentFilterHalfSheetWithMetadata:(id)arg1 navigationController:(id)arg2 navigationInfo:(id)arg3 loggingExtras:(id)arg4;
- (void)prefetchFilters;
- (id)initWithUserSession:(id)arg1 searchSession:(id)arg2 shoppingSessionTracker:(id)arg3 resultsFilterModelsMetadata:(id)arg4 analyticsModule:(id)arg5 preferredContentInsets:(struct UIEdgeInsets)arg6 destinationType:(long long)arg7 filterDisplayType:(long long)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

