//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGShoppingProductTileCoverMedia, IGShoppingProductTileMediaCarouselView;

@protocol IGShoppingProductTileMediaCarouselViewDelegate <NSObject>
- (void)shoppingProductTileMediaCarouselView:(IGShoppingProductTileMediaCarouselView *)arg1 didSwipeToMedia:(IGShoppingProductTileCoverMedia *)arg2;
- (void)shoppingProductTileMediaCarouselView:(IGShoppingProductTileMediaCarouselView *)arg1 didTapMedia:(IGShoppingProductTileCoverMedia *)arg2;
@end

