//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGUserSession;

@interface IGShoppingCartBridgeController : NSObject
{
    IGUserSession *_userSession;
    long long _prefetchAttemptCount;
}

- (void).cxx_destruct;
- (_Bool)isBloksCartPrefetchEnabled;
- (void)invalidateBloksPrefetechedData:(id)arg1;
- (void)preloadCartInformationIGBloks:(id)arg1;
- (id)initWithUserSession:(id)arg1;

@end

