//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol IGAnalyticsEventLoggingProtocol;

@interface IGStatusLogger : NSObject
{
    id <IGAnalyticsEventLoggingProtocol> _analyticsLogger;
    NSString *_analyticsModule;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *analyticsModule; // @synthesize analyticsModule=_analyticsModule;
- (void)logIGStatusSuggestionTapAtPosition:(long long)arg1 statusText:(id)arg2 emoji:(id)arg3;
- (void)logIGStatusHomeTapWithMediaID:(id)arg1 entryPoint:(long long)arg2;
- (void)logIGStatusComposerTapWithMediaID:(id)arg1;
- (void)logIGStatusComposerFinishWithMediaID:(id)arg1 statusText:(id)arg2 emoji:(id)arg3;
- (void)logIGStatusComposerClearMediaID:(id)arg1;
- (void)logIGStatusClickWithMediaID:(id)arg1 authorID:(id)arg2;
- (void)logImpressionForIGStatusWithMediaID:(id)arg1 authorID:(id)arg2 isFullStatus:(_Bool)arg3;
- (void)logIGStatusNUXPreference:(long long)arg1;
- (void)logImpressionForIGStatusNUX;
- (id)initWithAnalyticsLogger:(id)arg1 analyticsModule:(id)arg2;

@end

