//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGAREffectAttributionStoryViewModel, IGStoryAttributionBottomSheetCreatedWithListSectionController, IGStoryExpressiveFormatsAttributionModel;

@protocol IGStoryAttributionBottomSheetCreatedWithListSectionControllerDelegate <NSObject>
- (void)attributionCreatedWithListSectionController:(IGStoryAttributionBottomSheetCreatedWithListSectionController *)arg1 didTapExpressiveFormat:(IGStoryExpressiveFormatsAttributionModel *)arg2;
- (void)attributionCreatedWithListSectionControllerDidTapWearable:(IGStoryAttributionBottomSheetCreatedWithListSectionController *)arg1;
- (void)attributionCreatedWithListSectionControllerDidTapEffectStories:(IGStoryAttributionBottomSheetCreatedWithListSectionController *)arg1;
- (void)attributionCreatedWithListSectionControllerDidTapCameraFormat:(IGStoryAttributionBottomSheetCreatedWithListSectionController *)arg1;
- (void)attributionCreatedWithListSectionControllerDidTapMusic:(IGStoryAttributionBottomSheetCreatedWithListSectionController *)arg1;
- (void)attributionCreatedWithListSectionController:(IGStoryAttributionBottomSheetCreatedWithListSectionController *)arg1 didTapEffectModel:(IGAREffectAttributionStoryViewModel *)arg2;
@end

