//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGImageProcessor-Protocol.h"

@class NSString;

@interface IGStoryPhotoViewCroppingImageProcessor : NSObject <IGImageProcessor>
{
    struct CGRect _croppingRect;
}

- (_Bool)doesDecodeImage;
- (id)cacheKeyURLFromURL:(id)arg1;
- (id)cacheKeyFragment;
- (id)processedImageFromImage:(id)arg1;
- (id)initWithCroppingRect:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

