//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IGGestureHandler-Protocol.h"

@class IGAREffectTargetModel, IGAsyncTask, IGAudioTrackClip, IGCameraTargetModel, IGStoryCameraViewController, NSArray, NSString, UIViewController;
@protocol IGStoryCreationViewControllerNavigationDelegate, IGStoryCreationViewControllerSundialEventDelegate, IGStoryFormatViewControllerProtocol, IGSundialCameraPreloadingLatencyLoggingDelegate, IGSundialCreationViewControllerNavigationDelegate;

@protocol IGStoryCreationViewControllerType <IGGestureHandler>
@property(retain, nonatomic) IGAREffectTargetModel *effectTargetModelFromReel;
@property(nonatomic) _Bool showPreloadingSettingsToast;
@property(copy, nonatomic) NSString *sourceMediaAuthorUsername;
@property(copy, nonatomic) NSString *pivotPageSeededMediaId;
@property(copy, nonatomic) NSString *sourceMediaAuthorPk;
@property(copy, nonatomic) NSString *preloadedMediaID;
@property(copy, nonatomic) NSString *sourceMediaPk;
@property(readonly, nonatomic) IGStoryCameraViewController *cameraViewController;
@property(readonly, nonatomic) UIViewController<IGStoryFormatViewControllerProtocol> *currentCameraFormatViewController;
@property(nonatomic) long long entryPoint;
@property(readonly, nonatomic, getter=isActive) _Bool active;
@property(readonly, nonatomic) long long creationStyle;
@property(nonatomic) __weak IGAsyncTask *loadingAudioAsset;
@property(nonatomic) __weak id <IGSundialCameraPreloadingLatencyLoggingDelegate> latencyLoggingDelegate;
@property(nonatomic) __weak id <IGStoryCreationViewControllerSundialEventDelegate> sundialEventDelegate;
@property(nonatomic) __weak id <IGSundialCreationViewControllerNavigationDelegate> sundialNavigationDelegate;
@property(nonatomic) __weak id <IGStoryCreationViewControllerNavigationDelegate> storyNavigationDelegate;
- (void)willEnterAppForeground;
- (void)willEnterAppBackground;
- (void)setCameraPosition:(long long)arg1;
- (void)setCameraEffectListWithIDs:(NSArray *)arg1;
- (void)setTargetStickerId:(NSString *)arg1 targetStickerType:(long long)arg2 actionSourceType:(long long)arg3;
- (void)setCameraTarget:(IGCameraTargetModel *)arg1;
- (void)willBecomeInactiveWithExitPoint:(long long)arg1;
- (void)didBecomeActiveWithEntryPoint:(long long)arg1;
- (void)willBecomeActiveFromEntryPoint:(long long)arg1;
- (void)presentSavedEffectGallery;
- (void)presentEffectGallery;
- (void)presentSundialAudioBrowserIfPossible;
- (void)showPromptToApplyAudioTrack:(IGAudioTrackClip *)arg1 effectModel:(IGAREffectTargetModel *)arg2;
@end

