//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGAudioBrowserArtistCellModel, IGStoryMusicModelsListViewController, NSString;
@protocol IGAudioModelProtocol;

@protocol IGStoryMusicModelsListViewControllerDelegate <NSObject>
- (void)musicModelsPaginatedListDidUpdateModels:(IGStoryMusicModelsListViewController *)arg1;
- (void)modelsListViewControllerDidTapClearAllForRecentSearches:(IGStoryMusicModelsListViewController *)arg1;
- (void)modelsListViewController:(IGStoryMusicModelsListViewController *)arg1 didTapArtist:(IGAudioBrowserArtistCellModel *)arg2 category:(unsigned long long)arg3;
- (void)modelsListViewController:(IGStoryMusicModelsListViewController *)arg1 didTapAudioPageForAudioTrack:(id <IGAudioModelProtocol>)arg2 pivotPageSessionId:(NSString *)arg3;
- (void)modelsListViewController:(IGStoryMusicModelsListViewController *)arg1 didTapAudioTrack:(id <IGAudioModelProtocol>)arg2 context:(CDStruct_61bbf500)arg3 category_DEPRECATED:(unsigned long long)arg4;
@end

