//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGSundialComposition, IGSundialPostCaptureAudioController;

@protocol IGSundialPostCaptureAudioControllerDelegate <NSObject>
- (void)sundialPostCaptureAudioController:(IGSundialPostCaptureAudioController *)arg1 didChangeCompositionVoiceoverAudioClips:(IGSundialComposition *)arg2;
- (void)sundialPostCaptureAudioControllerDidUpdateSoundboardAudioTrack:(IGSundialPostCaptureAudioController *)arg1;
- (void)sundialPostCaptureAudioControllerDidChangeCompositionVideoVolume:(IGSundialPostCaptureAudioController *)arg1 fromVolume:(double)arg2 toVolume:(double)arg3;
- (void)sundialPostCaptureAudioControllerDidUpdateCompositionSelectedAudioVolume:(IGSundialPostCaptureAudioController *)arg1;
- (void)sundialPostCaptureAudioControllerDidUpdateCompositionSelectedAudio:(IGSundialPostCaptureAudioController *)arg1;
@end

