//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IGPlaybackTimelineDelegate-Protocol.h"

@class IGPlaybackTimeline, IGSundialAnimatedGradientView, IGUserSession, NSMutableArray, NSString, UILabel;

@interface IGSundialRecordingProgressIndicator : UIView <IGPlaybackTimelineDelegate>
{
    NSMutableArray *_recordedClipEndpoints;
    IGPlaybackTimeline *_recordingTimeline;
    UIView *_contentWrapperView;
    UIView *_backgroundView;
    IGSundialAnimatedGradientView *_recordingProgressView;
    IGSundialAnimatedGradientView *_retakeProgressView;
    NSMutableArray *_clipEndpointMarkers;
    UILabel *_currentTimeLabel;
    IGUserSession *_userSession;
    UIView *_lastRecordedClipDurationView;
    _Bool _isRecordingVideoLayout;
    long long _videoLayoutSegment;
    _Bool _isRecordingClip;
    double _maxRecordingDuration;
    double _clipRecordingRate;
    double _videoLayoutClipDuration;
    long long _retakeIndex;
    double _totalRecordedDuration;
    double _expansionPercentage;
}

- (void).cxx_destruct;
@property(nonatomic) double expansionPercentage; // @synthesize expansionPercentage=_expansionPercentage;
@property(nonatomic) double totalRecordedDuration; // @synthesize totalRecordedDuration=_totalRecordedDuration;
@property(nonatomic) long long retakeIndex; // @synthesize retakeIndex=_retakeIndex;
@property(nonatomic) double videoLayoutClipDuration; // @synthesize videoLayoutClipDuration=_videoLayoutClipDuration;
@property(readonly, nonatomic) double clipRecordingRate; // @synthesize clipRecordingRate=_clipRecordingRate;
@property(readonly, nonatomic) _Bool isRecordingClip; // @synthesize isRecordingClip=_isRecordingClip;
@property(nonatomic) double maxRecordingDuration; // @synthesize maxRecordingDuration=_maxRecordingDuration;
- (void)stopVideoLayoutRecording;
- (void)setRecordingVideoLayoutSegment:(long long)arg1;
- (void)_setExpansionPercentage:(double)arg1 animated:(_Bool)arg2;
@property(nonatomic) double lastClipDuration;
@property(readonly, nonatomic) double lastClipEndpoint;
- (void)_setTotalRecordedDuration:(double)arg1 recording:(_Bool)arg2;
- (void)appendNewClipWithEndpoint:(double)arg1;
- (void)removeAllRecordedSegmentsAnimated:(_Bool)arg1;
- (void)playbackTimeline:(id)arg1 didUpdateCurrentTime:(double)arg2;
- (void)stopRecordingClip;
- (void)updateClipRecordingRate:(double)arg1;
- (void)startRecordingClipAtRate:(double)arg1 atHostTime:(double)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

