//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGListAdapterDataSource-Protocol.h"
#import "IGSupportInboxEmptyViewDelegate-Protocol.h"
#import "IGSupportInboxListViewControllerDelegate-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class IGListAdapter, IGRefreshControl, IGSupportInboxEmptyView, IGSupportInboxHubModel, IGSupportInboxLogger, IGUserSession, NSString, UIActivityIndicatorView, UICollectionView;

@interface IGSupportInboxListViewController : IGViewController <IGSupportInboxEmptyViewDelegate, UICollectionViewDelegate, IGListAdapterDataSource, IGSupportInboxListViewControllerDelegate>
{
    IGUserSession *_userSession;
    IGSupportInboxHubModel *_dataModel;
    _Bool _isFetching;
    unsigned long long _inboxType;
    UIActivityIndicatorView *_spinner;
    IGRefreshControl *_refreshControl;
    IGSupportInboxEmptyView *_emptyView;
    IGListAdapter *_adapter;
    UICollectionView *_collectionView;
    IGSupportInboxLogger *_logger;
}

- (void).cxx_destruct;
- (long long)preferredTabBarBehavior;
- (void)supportInboxEmptyViewDidTapButton:(id)arg1;
- (void)_setupCollectionView;
- (void)_updateViewStopFetchingFromPullToRefresh:(_Bool)arg1;
- (void)_updateViewIsFetchingFromPullToRefresh:(_Bool)arg1;
- (void)_fetchSupportInboxListFromPullToRefresh:(_Bool)arg1;
- (void)_reloadDataFromPullToRefresh;
- (void)refreshList;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 inboxType:(unsigned long long)arg2 logger:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

