//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGSundialComposition, IGSundialDraftsCameraViewController;

@protocol IGSundialDraftsCameraViewControllerDelegate <NSObject>
- (void)sundialDraftsCameraViewController:(IGSundialDraftsCameraViewController *)arg1 didTapConfirmEditsForDraftComposition:(IGSundialComposition *)arg2;
- (void)sundialDraftsCameraViewControllerDidTapCloseButton:(IGSundialDraftsCameraViewController *)arg1;
@end

