//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IGStoryViewerTapTargetDelegate-Protocol.h"

@class BKContext, IGStoryStickerManager, IGUserSession, NSString;
@protocol IGSundialStickerOverlayViewDelegate;

@interface IGSundialStickerOverlayView : UIView <IGStoryViewerTapTargetDelegate>
{
    IGUserSession *_userSession;
    struct CGSize _mediaSize;
    NSString *_module;
    long long _storyEntrypoint;
    BKContext *_bloksContext;
    id <IGSundialStickerOverlayViewDelegate> _delegate;
    IGStoryStickerManager *_stickerManager;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGStoryStickerManager *stickerManager; // @synthesize stickerManager=_stickerManager;
@property(nonatomic) __weak id <IGSundialStickerOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTapOverlayTapTarget:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)setTappableOverlayDelegate:(id)arg1;
- (void)configureWithTappableOverlays:(id)arg1 mediaSize:(struct CGSize)arg2 isCurrentUser:(_Bool)arg3 module:(id)arg4 container:(id)arg5;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 userSession:(id)arg2 bloksContext:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

