//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGMainFeedNetworkSourceController, IGNavigationController, IGShoppingHomePrefetchController, IGUserSession, IGViewController;
@protocol IGAccountSwitcherPresenting, IGActivityFeedViewControllerType, IGExploreViewControllerType, IGNewsPresentationDelegate, IGProfileViewControllerType;

@interface IGTabBarViewControllerManager : NSObject
{
    IGUserSession *_userSession;
    IGMainFeedNetworkSourceController *_mainFeedNetworkSourceController;
    id <IGNewsPresentationDelegate> _newsPresentationDelegate;
    id <IGAccountSwitcherPresenting> _accountSwitcherPresenter;
    IGShoppingHomePrefetchController *_shoppingHomePrefetchController;
    IGNavigationController *_feedNavigationController;
    IGNavigationController *_exploreNavigationController;
    IGNavigationController *_discoverVideoNavigationController;
    IGNavigationController *_activityFeedNavigationController;
    IGNavigationController *_shoppingNavigationController;
    IGViewController<IGActivityFeedViewControllerType> *_activityFeedViewController;
    IGNavigationController *_profileNavigationController;
    IGViewController<IGProfileViewControllerType> *_profileViewController;
    IGNavigationController *_directInboxNavigationController;
    IGViewController<IGExploreViewControllerType> *_exploreViewController;
    IGViewController *_mainFeedViewController;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGViewController *mainFeedViewController; // @synthesize mainFeedViewController=_mainFeedViewController;
- (void)destroyCurrentDirectInboxNavigationController;
@property(readonly, nonatomic) IGNavigationController *directInboxNavigationController; // @synthesize directInboxNavigationController=_directInboxNavigationController;
@property(readonly, nonatomic) IGViewController<IGProfileViewControllerType> *profileViewController; // @synthesize profileViewController=_profileViewController;
@property(readonly, nonatomic) IGNavigationController *profileNavigationController; // @synthesize profileNavigationController=_profileNavigationController;
@property(readonly, nonatomic) IGViewController<IGActivityFeedViewControllerType> *activityFeedViewController; // @synthesize activityFeedViewController=_activityFeedViewController;
@property(readonly, nonatomic) IGNavigationController *shoppingNavigationController; // @synthesize shoppingNavigationController=_shoppingNavigationController;
@property(readonly, nonatomic) IGNavigationController *activityFeedNavigationController; // @synthesize activityFeedNavigationController=_activityFeedNavigationController;
@property(readonly, nonatomic) IGNavigationController *postNavigationController;
@property(readonly, nonatomic) IGNavigationController *discoverVideoNavigationController; // @synthesize discoverVideoNavigationController=_discoverVideoNavigationController;
@property(readonly, nonatomic) IGNavigationController *exploreNavigationController; // @synthesize exploreNavigationController=_exploreNavigationController;
@property(readonly, nonatomic) IGViewController<IGExploreViewControllerType> *exploreViewController; // @synthesize exploreViewController=_exploreViewController;
- (id)_mainFeedViewController;
@property(readonly, nonatomic) IGNavigationController *feedNavigationController; // @synthesize feedNavigationController=_feedNavigationController;
- (id)initWithUserSession:(id)arg1 networkSourceController:(id)arg2 newsPresentationDelegate:(id)arg3 accountSwitcherPresenter:(id)arg4;

@end

