//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGGestureHandler-Protocol.h"

@class IGNavigationBar, NSString, UINavigationItem, UIViewController;
@protocol IGGestureHandler;

@interface IGTVViewerPartialModalContentViewController : IGViewController <IGGestureHandler>
{
    UIViewController<IGGestureHandler> *_contentViewController;
    IGNavigationBar *_navigationBar;
    UINavigationItem *_navigationItem;
}

- (void).cxx_destruct;
- (void)keyboardObserver:(id)arg1 keyboardFrameWillChangeWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (_Bool)canRespondToGesture:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithContentViewController:(id)arg1 navigationBarTitle:(id)arg2 prefersNavigationBarHidden:(_Bool)arg3 analyticsModule:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

