//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGGroupedTableViewCell.h>

@class IGListHeaderView, UICollectionView;

@interface IGTVStoryLinkSelectionCell : IGGroupedTableViewCell
{
    IGListHeaderView *_headerView;
    UICollectionView *_userChannelCollectionView;
}

+ (double)height;
- (void).cxx_destruct;
@property(readonly, nonatomic) UICollectionView *userChannelCollectionView; // @synthesize userChannelCollectionView=_userChannelCollectionView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)arg1 title:(id)arg2;

@end

