//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGDiskDirectory, IGDiskManager, IGObjectDiskStorage, NSArray, NSMutableDictionary;
@protocol IGTVDraftsManagerEventAnnouncer, OS_dispatch_group;

@interface IGTVDraftsManager : NSObject
{
    IGDiskManager *_diskManager;
    IGObjectDiskStorage *_savedDraftsMetadataFile;
    NSMutableDictionary *_resourceDirectoryForDraft;
    NSMutableDictionary *_savedDrafts;
    id _lock;
    NSObject<OS_dispatch_group> *_savedDraftsDoneLoading;
    id <IGTVDraftsManagerEventAnnouncer> _eventAnnouncer;
    IGDiskDirectory *_draftsDirectory;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGDiskDirectory *draftsDirectory; // @synthesize draftsDirectory=_draftsDirectory;
- (void)_removeDraftsWithIdentifiers:(id)arg1;
- (void)removeDrafts:(id)arg1;
- (void)removeDraft:(id)arg1;
- (void)removeDraftWithIdentifier:(id)arg1;
- (id)loadCompositionForDraft:(id)arg1;
- (void)saveDraftWithIGTVComposition:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *savedDrafts;
- (id)initWithDiskManager:(id)arg1 eventAnnouncer:(id)arg2;

@end

