//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "IGHeartAnimatable-Protocol.h"
#import "IGTVShoppingPinnedProductViewV2Delegate-Protocol.h"
#import "IGTVVideoPlaybackControlsViewDelegate-Protocol.h"
#import "IGTVVideoPlaybackMetadataViewDelegate-Protocol.h"
#import "IGTVVideoPlaybackViewDelegate-Protocol.h"

@class IGPassthroughView, IGTVBlurredOverlayDetailedView, IGTVShoppingPinnedProductViewV2, IGTVVideoPlaybackCaptionsView, IGTVVideoPlaybackCellViewModel, IGTVVideoPlaybackControlsView, IGTVVideoPlaybackMetadataView, IGTVVideoPlaybackView, NSString, UIView;
@protocol IGTVVideoPlaybackCellDelegate;

@interface IGTVVideoPlaybackCell : UICollectionViewCell <IGTVShoppingPinnedProductViewV2Delegate, IGTVVideoPlaybackControlsViewDelegate, IGTVVideoPlaybackMetadataViewDelegate, IGTVVideoPlaybackViewDelegate, IGHeartAnimatable>
{
    IGTVVideoPlaybackView *_videoPlaybackView;
    IGPassthroughView *_overlayContainerView;
    IGTVVideoPlaybackCaptionsView *_captionsView;
    IGTVBlurredOverlayDetailedView *_blurOverlayView;
    double _chromeFadeAnimationToken;
    _Bool _isDisplayingChrome;
    _Bool _requiresPinnedProductAnimation;
    id <IGTVVideoPlaybackCellDelegate> _delegate;
    IGTVVideoPlaybackCellViewModel *_viewModel;
    IGTVVideoPlaybackMetadataView *_metadataView;
    IGTVShoppingPinnedProductViewV2 *_pinnedProductView;
    double _maxChromeAlpha;
}

- (void).cxx_destruct;
@property(nonatomic) double maxChromeAlpha; // @synthesize maxChromeAlpha=_maxChromeAlpha;
@property(readonly, nonatomic) IGTVShoppingPinnedProductViewV2 *pinnedProductView; // @synthesize pinnedProductView=_pinnedProductView;
@property(readonly, nonatomic) IGTVVideoPlaybackMetadataView *metadataView; // @synthesize metadataView=_metadataView;
- (void)_captionsViewTapped;
- (_Bool)_canFadeChrome;
- (void)_cancelPendingChromeFade;
- (void)_tryFadeChromeAfterDelay;
- (void)_resetOverlaysToDefaults;
- (void)_updateChromeDisplay:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_setShouldDisplayChrome:(_Bool)arg1;
- (double)relativeProgressPointForVideoPlaybackView:(id)arg1;
- (void)videoPlaybackView:(id)arg1 didReceiveLongPressGesture:(long long)arg2 translationProgress:(double)arg3;
- (void)videoPlaybackView:(id)arg1 didReceiveQuickGesture:(long long)arg2;
- (void)videoPlaybackViewDidTapSwitchOrientationButton:(id)arg1;
- (void)videoPlaybackMetadataView:(id)arg1 didTapURL:(id)arg2 hashtagText:(id)arg3;
- (void)videoPlaybackMetadataViewDidTapLiveRing:(id)arg1;
- (void)videoPlaybackMetadataViewDidToggleDetailsDisplay:(id)arg1;
- (void)videoPlaybackViewDidTapBrandPartners:(id)arg1;
- (void)videoPlaybackViewDidTapLocationButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapPeopleTagsButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapViewProductsButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapSeriesButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapOrientationButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapDismissButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapOverflowButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapDirectButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapCommentButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapLikeCountButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapRemixButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapLikeButton:(id)arg1;
- (void)videoPlaybackMetadataViewDidTapUsernameButton:(id)arg1;
- (_Bool)playbackControlsViewShouldUpdateThumbnailProgress;
- (void)playbackControlsViewDidEndScrubbing:(id)arg1 progress:(double)arg2;
- (void)playbackControlsViewDidChangeScrubbing:(id)arg1 progress:(double)arg2;
- (void)playbackControlsViewDidBeginScrubbing:(id)arg1 progress:(double)arg2;
- (_Bool)playbackControlsViewIsScrubbingEnabled:(id)arg1;
- (void)playbackControlsViewDidTapPlayPauseButton:(id)arg1;
- (void)didTapShoppingPinnedProductCTA:(id)arg1 withViewModel:(id)arg2;
- (void)didTapShoppingPinnedProductView:(id)arg1 withViewModel:(id)arg2;
- (id)contentViewForHeartAnimation;
- (void)updateChromeVisibility:(_Bool)arg1;
- (void)configureWithViewModel:(id)arg1 animated:(_Bool)arg2 delegate:(id)arg3;
- (void)configureWithViewModel:(id)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) IGTVVideoPlaybackControlsView *controlsView;
@property(readonly, nonatomic) UIView *playbackView;
- (void)prepareForReuse;
- (void)applyLayoutAttributes:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

