//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGTVThumbnailChannelViewControllerDelegate-Protocol.h"

@class IGTVDestinationLoggingContext, IGTVThumbnailChannelViewController, IGUserSession, NSString;
@protocol IGTVChannelDataSourceType;

@interface IGTVCollectionViewController : IGViewController <IGTVThumbnailChannelViewControllerDelegate>
{
    IGUserSession *_userSession;
    NSString *_title;
    id <IGTVChannelDataSourceType> _channelDataSource;
    IGTVDestinationLoggingContext *_loggingContext;
    IGTVThumbnailChannelViewController *_thumbnailChannelViewController;
}

- (void).cxx_destruct;
- (void)thumbnailChannelViewControllerDidFinishUpdate:(id)arg1 fromChannelDataSourceInitialLoad:(id)arg2;
- (void)thumbnailChannelViewController:(id)arg1 channelDataSourceDidFail:(id)arg2 withError:(id)arg3;
- (void)thumbnailChannelViewController:(id)arg1 channelDataSourceDidInitialLoad:(id)arg2;
- (_Bool)isThumbnailFirstItem;
- (double)adjustedInsetForTopContentInset:(double)arg1;
- (long long)loggingPositionOffsetForThumbnailSectionController;
- (id)listAdapter:(id)arg1 otherSectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1 channelDataSource:(id)arg2 refreshControlState:(long long)arg3;
- (long long)preferredTabBarBehavior;
- (id)analyticsModule;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 title:(id)arg2 channelDataSource:(id)arg3 loggingContext:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

