//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGUser, NSError;

@protocol IGTVProfileDataSourceDelegate <NSObject>
- (void)profileDataSourceDidUpdateState:(long long)arg1 withError:(NSError *)arg2;
- (void)profileDataSourceDidUpdateChannelDataSource;
- (void)profileDataSourceDidUpdateUser:(IGUser *)arg1;
- (void)profileDataSourceWillFetchForFirstTime;
@end

