//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import "IGTwoFactorRequestViewDelegate-Protocol.h"

@class IGTwoFactorRequestView, NSString, UIButton;
@protocol IGTwoFactorRequestViewControllerDelegate;

@interface IGTwoFactorRequestViewController : IGViewController <IGTwoFactorRequestViewDelegate>
{
    IGTwoFactorRequestView *_requestView;
    UIButton *_backButton;
    UIButton *_dismissButton;
    _Bool _showBackButton;
    _Bool _showDismissButton;
    id <IGTwoFactorRequestViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGTwoFactorRequestViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_didTapDismissButton;
- (void)_backButtonPressed;
- (void)twoFactorRequestViewDidSwitchToAnotherWay:(id)arg1;
- (void)twoFactorRequestViewDidTapContinueButton:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (_Bool)prefersNavigationBarHidden;
- (id)initWithShowBackButton:(_Bool)arg1 showDismissButton:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

