//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IGCoreTextLinkHandler-Protocol.h"
#import "IGLoginActivityMapInfoViewDelegate-Protocol.h"

@class IGCoreTextView, IGLoginActivityMapInfoView, NSString, UILabel;
@protocol IGTwoFactorLoginApprovalViewDelegate;

@interface IGTwoFactorLoginApprovalView : UIView <IGCoreTextLinkHandler, IGLoginActivityMapInfoViewDelegate>
{
    UILabel *_title;
    IGCoreTextView *_descriptionView;
    IGLoginActivityMapInfoView *_mapInfoView;
    IGCoreTextView *_footerView;
    id <IGTwoFactorLoginApprovalViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGTwoFactorLoginApprovalViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)configureWithLoginApprovalModel:(id)arg1 reviewStatus:(unsigned long long)arg2 lastUpdateStatusTime:(id)arg3;
- (void)loginActivityMapInfoViewDidRevertConfirmLoginActivity:(id)arg1;
- (void)loginActivityMapInfoViewDidDisavowLoginActivity:(id)arg1;
- (void)loginActivityMapInfoViewDidAvowLoginActivity:(id)arg1;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

