//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGShoppingProductTileLoggingProviderType-Protocol.h"

@class IGSessionTracker, IGShoppingFiltersAnalyticsContext, IGShoppingGuideAnalyticsContext, IGShoppingLiveAnalyticsContext, IGShoppingMediaCarouselAnalyticsContext, IGShoppingNavigationAnalyticsContext, IGShoppingPDPAnalyticsContext, IGShoppingProductCollectionProperties, IGShoppingUpcomingEventAnalyticsContext, IGUserSession, NSString;

@interface IGUpcomingEventShoppingProductTileLoggingProvider : NSObject <IGShoppingProductTileLoggingProviderType>
{
    IGUserSession *_userSession;
    IGShoppingUpcomingEventAnalyticsContext *_upcomingEventInfo;
    IGShoppingNavigationAnalyticsContext *_navigationInfo;
    IGSessionTracker *_shoppingSessionTracker;
    IGShoppingFiltersAnalyticsContext *filtersInfo;
    IGShoppingPDPAnalyticsContext *pdpInfo;
    IGShoppingGuideAnalyticsContext *guideInfo;
    IGShoppingLiveAnalyticsContext *liveInfo;
    IGShoppingMediaCarouselAnalyticsContext *mediaCarouselInfo;
    IGShoppingProductCollectionProperties *_productCollectionProperties;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGShoppingProductCollectionProperties *productCollectionProperties; // @synthesize productCollectionProperties=_productCollectionProperties;
@property(readonly, nonatomic) IGShoppingMediaCarouselAnalyticsContext *mediaCarouselInfo; // @synthesize mediaCarouselInfo;
@property(readonly, nonatomic) IGShoppingLiveAnalyticsContext *liveInfo; // @synthesize liveInfo;
@property(readonly, nonatomic) IGShoppingGuideAnalyticsContext *guideInfo; // @synthesize guideInfo;
@property(readonly, nonatomic) IGShoppingPDPAnalyticsContext *pdpInfo; // @synthesize pdpInfo;
@property(readonly, nonatomic) IGShoppingFiltersAnalyticsContext *filtersInfo; // @synthesize filtersInfo;
@property(readonly, nonatomic) IGShoppingUpcomingEventAnalyticsContext *upcomingEventInfo; // @synthesize upcomingEventInfo=_upcomingEventInfo;
@property(readonly, nonatomic) IGSessionTracker *shoppingSessionTracker; // @synthesize shoppingSessionTracker=_shoppingSessionTracker;
@property(readonly, nonatomic) IGShoppingNavigationAnalyticsContext *navigationInfo; // @synthesize navigationInfo=_navigationInfo;
- (id)_chainingContext;
- (void)logProductCardCoverSwipeToCoverMedia:(id)arg1 withViewModel:(id)arg2;
- (void)logProductCardDismissForViewModel:(id)arg1 extras:(id)arg2;
- (void)logProductCardTapForViewModel:(id)arg1 entryPoint:(id)arg2 scrollDepth:(id)arg3 extras:(id)arg4;
- (long long)levelForImpression;
- (void)logProductCardSubImpressionForViewModel:(id)arg1 scrollDepth:(id)arg2 extras:(id)arg3;
- (void)logProductCardImpressionForViewModel:(id)arg1 scrollDepth:(id)arg2 extras:(id)arg3;
- (id)initWithUserSession:(id)arg1 upcomingEventInfo:(id)arg2 navigationAnalyticsContext:(id)arg3 productCollectionProperties:(id)arg4 shoppingSessionTracker:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

