//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IGUserListSectionController, UINavigationController;

@protocol IGUserListSectionControllerTapDelegate <NSObject>
- (UINavigationController *)userListSectionControllerNavigationController:(IGUserListSectionController *)arg1;
- (_Bool)userListSectionControllerShouldNavigateToProfileOnTap:(IGUserListSectionController *)arg1;
- (void)userListSectionControllerCellWasTapped:(IGUserListSectionController *)arg1;
@end

