//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIButton, UIScrollView;

@interface IGVideoShareToView : UIView
{
    _Bool _useRoundedButton;
    UIScrollView *_scrollView;
    NSArray *_destinationControls;
    UIButton *_continueButton;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIButton *continueButton; // @synthesize continueButton=_continueButton;
@property(readonly, copy, nonatomic) NSArray *destinationControls; // @synthesize destinationControls=_destinationControls;
- (void)_updateContinueButtonBackgroundImages;
- (void)traitCollectionDidChange:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithUseRoundedButton:(_Bool)arg1;

@end

