//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "IGAnalyticsModule-Protocol.h"
#import "IGDirectRecipientListViewControllerDelegate-Protocol.h"
#import "IGGestureHandler-Protocol.h"
#import "IGListAdapterDataSource-Protocol.h"
#import "IGVideoCallInviteListHeaderViewSectionControllerDelegate-Protocol.h"
#import "IGVideoCallInviteListHeaderViewViewModelDelegate-Protocol.h"

@class IGDirectThreadService, IGListAdapter, IGUserSession, IGVideoCallAddUsersRecipientListWrapper, IGVideoCallAddUsersView, IGVideoCallInviteListHeaderViewDataSource, IGVideoCallSession, NSMutableSet, NSSet, NSString;
@protocol FBCancelable, IGVideoCallAddUsersViewControllerDelegate;

@interface IGVideoCallAddUsersViewController : UIViewController <IGDirectRecipientListViewControllerDelegate, IGListAdapterDataSource, IGVideoCallInviteListHeaderViewViewModelDelegate, IGVideoCallInviteListHeaderViewSectionControllerDelegate, IGAnalyticsModule, IGGestureHandler>
{
    IGVideoCallAddUsersView *_addUsersView;
    IGUserSession *_userSession;
    IGVideoCallSession *_videoCallSession;
    id <IGVideoCallAddUsersViewControllerDelegate> _delegate;
    IGVideoCallInviteListHeaderViewDataSource *_headerViewDataSource;
    IGListAdapter *_headerViewListAdapter;
    IGVideoCallAddUsersRecipientListWrapper *_nonInteropRecipientListWrapper;
    IGVideoCallAddUsersRecipientListWrapper *_interopRecipientListWrapper;
    IGVideoCallAddUsersRecipientListWrapper *_currentRecipientListWrapper;
    IGDirectThreadService *_directThreadService;
    NSMutableSet *_recipientsManuallyMarkedAsAdded;
    id <FBCancelable> _groupExpansionSubscriptionToken;
    long long _groupExpansionState;
    _Bool _isRoom;
    NSSet *_excludedDirectShareRecipients;
}

- (void).cxx_destruct;
- (void)didTapOnParticipant:(id)arg1;
- (void)_sendRoomLinkToDirectRecipients:(id)arg1;
- (void)videoCallInviteListHeaderViewDataSource:(id)arg1 failedToAddItems:(id)arg2;
- (void)videoCallInviteListHeaderViewDidUpdateDataSource:(id)arg1 withAddedItems:(id)arg2;
- (void)selectRecipientViewController:(id)arg1 didTapSendToGroupButtonWithSelectedRecipients:(id)arg2 sender:(id)arg3 text:(id)arg4 externalServices:(id)arg5 storyViewerViewModel:(id)arg6 storyViewerLoggingContext:(id)arg7 currentStoryItem:(id)arg8 loggingProvider:(id)arg9 media:(id)arg10 selectedPost:(id)arg11;
- (void)selectRecipientViewController:(id)arg1 willShowPrivacyBanner:(_Bool)arg2;
- (void)selectRecipientViewController:(id)arg1 willToggleFullScreenOn:(_Bool)arg2;
- (void)selectRecipientViewController:(id)arg1 didTapRecipient:(id)arg2 selected:(_Bool)arg3;
- (void)selectRecipientViewController:(id)arg1 didUpdateSelectedRecipients:(id)arg2;
- (void)selectRecipientViewControllerDidTapBackButton:(id)arg1;
- (void)selectRecipientViewControllerDidDismissRecipientList:(id)arg1 recipientsFromSearch:(id)arg2 bumpedRecipients:(id)arg3;
- (void)selectRecipientViewControllerDidTapFinishButton:(id)arg1 storySendTarget:(long long)arg2 sender:(id)arg3 directRecipients:(id)arg4 externalServices:(id)arg5 text:(id)arg6 fromOneTap:(_Bool)arg7 storyViewerViewModel:(id)arg8 storyViewerLoggingContext:(id)arg9 currentStoryItem:(id)arg10 loggingProvider:(id)arg11 media:(id)arg12 selectedPost:(id)arg13;
- (id)selectedRecipientsSoFarFromOneTapping:(id)arg1;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToCollabStoriesRecipient:(id)arg2;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToGroupStoriesRecipient:(id)arg2;
- (void)selectRecipientViewController:(id)arg1;
- (void)selectRecipientViewControllerDidTapPromote:(id)arg1;
- (void)selectRecipientViewControllerDidTapAddToHighlight:(id)arg1;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToBlastList:(id)arg2;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToDirectRecipient:(id)arg2 messageText:(id)arg3;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToExternalService:(long long)arg2 willShareToFbWithYourStoryButton:(_Bool)arg3;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToStoryTarget:(long long)arg2 willShareToFbWithYourStoryButton:(_Bool)arg3;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (void)_setupRecipientListViewController;
- (id)_createRecipientListViewControllerExcludeInteropThreads:(_Bool)arg1;
- (void)_prepareViewControllerBeforeSettingItUp:(id)arg1;
- (_Bool)canRespondToGesture:(id)arg1;
- (id)analyticsModule;
- (void)addUsersToVideoCall:(id)arg1;
- (void)setIncludeInteropUsers:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithUserSession:(id)arg1 videoCallSession:(id)arg2 excludeParticipants:(id)arg3 delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

