//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGDirectCacheListener-Protocol.h"

@class IGDirectCache, IGVideoCallKey, NSString;
@protocol IGVideoCallDirectThreadMigrationObserverDelegate;

@interface IGVideoCallDirectThreadMigrationObserver : NSObject <IGDirectCacheListener>
{
    id <IGVideoCallDirectThreadMigrationObserverDelegate> _delgate;
    IGDirectCache *_directCache;
    IGVideoCallKey *_videoCallKey;
    NSString *_threadId;
}

- (void).cxx_destruct;
- (void)directCacheDidUpdateInboxMetadata;
- (void)directCacheDidUpdateThreads:(id)arg1;
- (void)directCacheDidUpdateThread:(id)arg1 withAppliedUpdates:(id)arg2;
- (void)directCacheDidRemoveThreadsWithIds:(id)arg1;
- (void)stopObserving;
- (void)startObservingWithDelegate:(id)arg1 videoCallKey:(id)arg2 threadId:(id)arg3;
- (void)_detectIfCallHasMovedThreads:(id)arg1;
- (id)initWithCache:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

