//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGListSectionController.h>

@class IGMedia, IGUserSession, NSString;

@interface IGVideoViewCountAndLikeCountSectionController : IGListSectionController
{
    IGUserSession *_userSession;
    IGMedia *_media;
    NSString *_disclaimerText;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool shouldDisplayPlayCount;
- (void)didUpdateToObject:(id)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (id)initWithUserSession:(id)arg1 disclaimerText:(id)arg2;

@end

