//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGFXCALManager, NSMutableDictionary, NSMutableSet, NSString;
@protocol FBAnalyticsLogging, IGUserLauncherSetProviding;

@interface IGVideoCallRoomLogger : NSObject
{
    id <FBAnalyticsLogging> _structuredLogger;
    id <IGUserLauncherSetProviding> _launcherSet;
    IGFXCALManager *_FXCALManager;
    unsigned long long _source;
    unsigned long long _surface;
    unsigned long long _creationVersion;
    long long _linkId;
    NSString *_linkHash;
    struct RoomssessionidsTypeNoBuilder _sessionIds;
    _Bool _isIGNativeRoomsEnabled;
    _Bool _isAudioOnly;
    NSMutableSet *_nonRoomsImpressionSet;
    NSMutableDictionary *_roomsImpressionDict;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)logRoomJoinRequestsWaitingRoomImpression:(id)arg1;
- (void)logRoomJoinRequestsJoinerAccepted:(id)arg1;
- (void)logRoomJoinRequestsDenyTap:(id)arg1 linkURL:(id)arg2;
- (void)logRoomJoinRequestsAcceptTap:(id)arg1 linkURL:(id)arg2;
- (void)logRoomPendingApprovalsImpression:(id)arg1;
- (void)logRoomJoinRequestsEnabled:(id)arg1;
- (void)logRoomAppUpdateImpression;
- (void)logRoomEncryptionFailure;
- (void)logRoomAlreadyEncrypted;
- (void)logUpdateInstagramDialogCancelTapped;
- (void)logUpdateInstagramDialogUpdateTapped;
- (void)logEncryptRoomDialogCancelTapped;
- (void)logEncryptRoomButtonTapped;
- (void)logRoomsRingDeclinedWithLocalCallId:(id)arg1;
- (void)logRoomsRingAcceptedWithLocalCallId:(id)arg1;
- (void)logRoomsRingReceivedWithRoomURL:(id)arg1 localCallId:(id)arg2;
- (void)logScheduleRoomForLaterButtonTapped;
- (void)logScheduleRoomButtonTapped:(id)arg1;
- (void)logNativeRoomsSkipLobby;
- (void)logNativeRoomsLeaveLobby;
- (void)logNativeRoomsTapLobbyCameraPreview;
- (void)logNativeRoomsJoinRoomFailureWithRoomURL:(id)arg1 errorDetails:(id)arg2;
- (void)logNativeRoomsSuccessfullyJoinCallWithLocalCallId:(id)arg1;
- (void)logNativeRoomsCallJoinTap;
- (void)logNativeRoomsLobbyImpression;
- (void)logNativeRoomsJoinStartWithRoomURL:(id)arg1;
- (void)resetRoomsTabImpressionDicts;
- (void)logRoomsListRelinkButtonTap;
- (void)logManageSheetEndRoomActionSheetCancelTap:(id)arg1;
- (void)logManageSheetEndRoomActionSheetEndRoomTap:(id)arg1;
- (void)logManageSheetCancelButtonTap:(id)arg1;
- (void)logManageSheetEndRoomButtonTap:(id)arg1;
- (void)logManageSheetShareLinkButtonTap:(id)arg1;
- (void)logManageSheetCopyLinkButtonTap:(id)arg1;
- (void)logRoomsSettingsTappedEditRoomName;
- (void)logRoomsSettingsDidEditRoomName;
- (void)logRoomsSettingsButtonTapped;
- (void)logManageRoomButtonTap:(id)arg1;
- (void)logAccountLinkSuccess;
- (void)logAccountLinkButtonTapCancel;
- (void)logAccountLinkPrompt;
- (void)logAccountLinkScreen;
- (void)logSharedOnExternalShareSheetWithActivityType:(id)arg1 roomModel:(id)arg2;
- (void)logSharedOnExternalShareSheetWithActivityType:(id)arg1;
- (void)logJoinRoomDialogInviteFriendsButtonTapped;
- (void)logJoinRoomDialogShareLinkButtonTapped;
- (void)logCancelDialogInviteFriendsButtonTapped;
- (void)logCancelDialogEndRoomButtonTapped;
- (void)logClientLinkViewLinkingSuccess;
- (void)logClientLinkViewLinkingStarted;
- (void)logClientLinkViewLinkAccountButtonTapped;
- (void)logClientLinkViewImpression;
- (void)logAppSwitchTapped:(_Bool)arg1 messengerInstalled:(_Bool)arg2 roomURL:(id)arg3;
- (void)logNativeRoomJoinTappedWithLinkURL:(id)arg1;
- (void)logJoinTapped:(_Bool)arg1 linkURL:(id)arg2;
- (void)logJoinFromNonCreationFlow:(_Bool)arg1 linkURL:(id)arg2;
- (void)logInviteFriendsCancelButtonTapped;
- (void)logRoomShareButtonTapWithParticipantCount:(long long)arg1 isScheduledRooms:(_Bool)arg2;
- (void)logShareLinkButtonTapped;
- (void)logInviteFriendsDoneButtonTapped;
- (void)logShareSheetImpression;
- (void)logCreateRoomFailed;
- (void)logCreateRoomImpression;
- (void)logCreateRoomCancelButtonTapped;
- (void)logCreateTapped;
- (void)logNUXTappedWithRoomCreated:(_Bool)arg1;
- (void)logNUXImpression;
- (void)logRoomsTabItemTappedAtPosition:(unsigned long long)arg1 positionInSection:(long long)arg2 source:(unsigned long long)arg3 contentId:(id)arg4 isRooms:(_Bool)arg5;
- (void)logRoomsTabItemImpressionAtPosition:(unsigned long long)arg1 positionInSection:(long long)arg2 source:(unsigned long long)arg3 contentId:(id)arg4 isRooms:(_Bool)arg5;
- (void)logRoomsTabItemImpressionAtPosition:(unsigned long long)arg1 source:(unsigned long long)arg2 isRooms:(_Bool)arg3;
- (void)_logRoomsTabItemImpressionAtPosition:(unsigned long long)arg1 positionInSection:(long long)arg2 source:(unsigned long long)arg3 contentId:(id)arg4 isRooms:(_Bool)arg5;
- (void)_logRoomsTabImpression;
- (void)logRoomsTabImpression;
- (void)logCreationStart:(unsigned long long)arg1;
- (void)resetSessionIds;
- (id)funnelSessionId;
- (unsigned long long)source;
- (void)setIsAudioOnly:(_Bool)arg1;
- (void)setLinkId:(id)arg1;
- (id)initWithAnalyticsLogger:(id)arg1 launcherSet:(id)arg2 FXCALManager:(id)arg3 source:(unsigned long long)arg4 surface:(unsigned long long)arg5;
- (id)initWithAnalyticsLogger:(id)arg1 launcherSet:(id)arg2 FXCALManager:(id)arg3 source:(unsigned long long)arg4;

@end

