//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "OCMComponentPersistable-Protocol.h"
#import "OCMComponentPreviewProtocol-Protocol.h"

@class NSString, UIImageView, UIView;
@protocol FBCameraPreviewing, OCMControllerProtocol;

@interface OCMComponentDefaultPreview : NSObject <OCMComponentPersistable, OCMComponentPreviewProtocol>
{
    id <OCMControllerProtocol> _context;
    UIView *_previewWrapperView;
    UIView<FBCameraPreviewing> *_internalPreviewView;
    UIImageView *_lastFrameImageView;
    _Bool _shouldBlurLastFrame;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool shouldBlurLastFrame; // @synthesize shouldBlurLastFrame=_shouldBlurLastFrame;
- (id)previewView;
- (void)_updateBlurImage;
- (void)_reloadInternalPreviewView;
- (void)willDetachWithContext:(id)arg1;
- (void)didAttachWithContext:(id)arg1;
- (long long)supportedControllerStates;
- (id)dependentComponentIDs;
- (id)componentID;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

