//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCTEvent-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface RCTComponentEvent : NSObject <RCTEvent>
{
    NSArray *_arguments;
    NSString *_eventName;
    NSNumber *_viewTag;
}

+ (id)moduleDotMethod;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *viewTag; // @synthesize viewTag=_viewTag;
@property(readonly, copy, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
- (_Bool)canCoalesce;
- (id)arguments;
- (id)init;
- (id)initWithName:(id)arg1 viewTag:(id)arg2 body:(id)arg3;

// Remaining properties
@property(readonly, nonatomic) unsigned short coalescingKey;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

