//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NativeImagePickerIOSSpec-Protocol.h"
#import "RCTBridgeModule-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, RCTBridge, RCTBundleManager, RCTCallableJSModules, RCTModuleRegistry, RCTViewRegistry;
@protocol OS_dispatch_queue;

@interface RCTImagePickerManager : NSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate, NativeImagePickerIOSSpec, RCTBridgeModule>
{
    NSMutableArray *_pickers;
    NSMutableArray *_pickerCallbacks;
    NSMutableArray *_pickerCancelCallbacks;
    NSMutableDictionary *_pendingVideoInfo;
    RCTModuleRegistry *_moduleRegistry;
}

+ (const struct RCTMethodInfo *)__rct_export__1435;
+ (const struct RCTMethodInfo *)__rct_export__1334;
+ (const struct RCTMethodInfo *)__rct_export__1043;
+ (const struct RCTMethodInfo *)__rct_export__772;
+ (const struct RCTMethodInfo *)__rct_export__681;
+ (const struct RCTMethodInfo *)__rct_export__620;
+ (_Bool)requiresMainQueueSetup;
+ (void)load;
+ (id)moduleName;
- (void).cxx_destruct;
@property(nonatomic) __weak RCTModuleRegistry *moduleRegistry; // @synthesize moduleRegistry=_moduleRegistry;
- (shared_ptr_3725e3cd)getTurboModule:(const void *)arg1;
- (void)cameraChanged:(id)arg1;
- (void)_dismissPicker:(id)arg1 args:(id)arg2;
- (void)_presentPicker:(id)arg1 successCallback:(CDUnknownBlockType)arg2 cancelCallback:(CDUnknownBlockType)arg3;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)removePendingVideo:(id)arg1;
- (void)clearAllPendingVideos;
- (void)openSelectDialog:(struct SpecOpenSelectDialogConfig *)arg1 successCallback:(CDUnknownBlockType)arg2 cancelCallback:(CDUnknownBlockType)arg3;
- (void)openCameraDialog:(struct SpecOpenCameraDialogConfig *)arg1 successCallback:(CDUnknownBlockType)arg2 cancelCallback:(CDUnknownBlockType)arg3;
- (void)canUseCamera:(CDUnknownBlockType)arg1;
- (void)canRecordVideos:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(nonatomic) __weak RCTBundleManager *bundleManager;
@property(nonatomic) __weak RCTCallableJSModules *callableJSModules;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) __weak RCTViewRegistry *viewRegistry_DEPRECATED;

@end

