//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RCTViewManager.h"

#import "RCTInvalidating-Protocol.h"
#import "RCTModalFullscreenHostDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface RCTModalFullscreenViewManager : RCTViewManager <RCTInvalidating, RCTModalFullscreenHostDelegate>
{
    NSMutableArray *_modalHostArray;
}

+ (_Bool)requiresMainQueueSetup;
+ (id)moduleName;
- (void).cxx_destruct;
- (id)getConstants;
- (id)constantsToExport;
- (void)modalFullscreenHostDidHide:(id)arg1;
- (void)invalidate;
- (id)view;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

