//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IGBackgroundGradient, _TtC31IGStoryPostCaptureColorPickerUI43IGStoryPostCaptureColorPickerViewController;

@protocol _TtP31IGStoryPostCaptureColorPickerUI39IGStoryPostCaptureColorPickerUIDelegate_
- (void)storyPostCaptureColorPickerViewController:(_TtC31IGStoryPostCaptureColorPickerUI43IGStoryPostCaptureColorPickerViewController *)arg1 didSelectGradient:(IGBackgroundGradient *)arg2;
@end

