//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CAMediaTimingFunction.h>

@interface CAMediaTimingFunction (Util)
- (struct CGPoint)pointAtTime:(double)arg1;
- (double)approximateTValueForX:(double)arg1;
- (double)easingValueAtTime:(double)arg1;
@end

