//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/TBaseStruct.h>

#import <FBSharedFramework/NSCoding-Protocol.h>
#import <FBSharedFramework/TBase-Protocol.h>

@class NSString;

@interface FacebookContextualPresenceSubscriptionMutation : TBaseStruct <TBase, NSCoding>
{
    int __thrift_useCase;
    int __thrift_actionType;
    _Bool __thrift_useCase_set;
    _Bool __thrift_actionType_set;
}

- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (_Bool)makeImmutable;
- (id)toDict;
@property(readonly, copy) NSString *description;
- (void)validate;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetActionType;
- (_Bool)actionTypeIsSet;
@property(nonatomic) int actionType;
- (void)unsetUseCase;
- (_Bool)useCaseIsSet;
@property(nonatomic) int useCase;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUseCase:(int)arg1 actionType:(int)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

