//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@class FBAnalyticsBatch, FBAnalyticsEvent;

@protocol FBAnalyticsStoreProvider <NSObject>
- (void)closeAnalyticsEventStore;
- (void)removeAllAnalyticsEventsInStore;
- (FBAnalyticsBatch *)fetchAllAnalyticsEvents;
- (long long)numberOfAnalyticsEventsInStore;
- (void)removeEventsFromLastFetch;
- (FBAnalyticsBatch *)fetchAnalyticsEventsWithMaxEventCount:(unsigned long long)arg1 removeOnFetch:(_Bool)arg2;
- (FBAnalyticsBatch *)fetchAnalyticsEventsWithMaxEventCount:(unsigned long long)arg1;
- (void)insertAnalyticsEvent:(FBAnalyticsEvent *)arg1;
@end

