//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/FBARPersistenceServiceDelegateProvider-Protocol.h>

@class NSDictionary, NSString;
@protocol FBARCaptureScopePersistenceDelegate;

@interface FBARCaptureScopePersistenceDelegateProvider : NSObject <FBARPersistenceServiceDelegateProvider>
{
    id <FBARCaptureScopePersistenceDelegate> _delegate;
    NSDictionary *_initialState;
    shared_ptr_5e1d7b9d _cxxDelegate;
}

+ (_Bool)supportsSecureCoding;
+ (id)newWithDelegate:(id)arg1 initialState:(id)arg2;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *initialState; // @synthesize initialState=_initialState;
@property(readonly, nonatomic) __weak id <FBARCaptureScopePersistenceDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) shared_ptr_5e1d7b9d cxxDelegate; // @synthesize cxxDelegate=_cxxDelegate;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDelegate:(id)arg1 initialState:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

