//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FBMPBaseProducerPort, NSArray;

@interface FBAVVideoDataProducer : NSObject
{
    NSArray *_framePerformanceTrackers;
    unsigned long long _dataCounter;
    FBMPBaseProducerPort *_producerPort;
}

+ (id)newWithProducerPort:(id)arg1 framePerformanceTrackers:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) FBMPBaseProducerPort *producerPort; // @synthesize producerPort=_producerPort;
- (void)_notifyPerformanceTrackersRenderingStarted;
- (void)produceVideoDataWithSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 depthData:(id)arg2 fromConnection:(id)arg3 videoDeviceInput:(id)arg4 videoBufferTransform:(unsigned long long)arg5 skipFilterRendering:(_Bool)arg6;
- (id)initWithProducerPort:(id)arg1 framePerformanceTrackers:(id)arg2;

@end

