//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AVCaptureDevice;
@protocol OS_dispatch_queue;

@interface FBCameraCaptureImageAction : NSObject
{
    _Bool _highResolution;
    _Bool _rotatedToVideoOrientation;
    NSObject<OS_dispatch_queue> *_completionQueue;
    CDUnknownBlockType _completion;
    CDUnknownBlockType _livePhotoCompletion;
    AVCaptureDevice *_captureDevice;
}

+ (id)newLivePhotoCaptureWithHighResolutionCaptureEnabled:(_Bool)arg1 captureDevice:(id)arg2 rotatedToVideoOrientation:(_Bool)arg3 completionQueue:(id)arg4 completion:(CDUnknownBlockType)arg5 livePhotoCompletion:(CDUnknownBlockType)arg6;
+ (id)newWithHighResolutionCaptureEnabled:(_Bool)arg1 captureDevice:(id)arg2 rotatedToVideoOrientation:(_Bool)arg3 completionQueue:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (id)newWithHighResolutionCaptureEnabled:(_Bool)arg1 rotatedToVideoOrientation:(_Bool)arg2 completionQueue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void).cxx_destruct;
@property(readonly, nonatomic) AVCaptureDevice *captureDevice; // @synthesize captureDevice=_captureDevice;
@property(readonly, copy, nonatomic) CDUnknownBlockType livePhotoCompletion; // @synthesize livePhotoCompletion=_livePhotoCompletion;
@property(readonly, copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *completionQueue; // @synthesize completionQueue=_completionQueue;
@property(readonly, nonatomic) _Bool rotatedToVideoOrientation; // @synthesize rotatedToVideoOrientation=_rotatedToVideoOrientation;
@property(readonly, nonatomic) _Bool highResolution; // @synthesize highResolution=_highResolution;
- (id)initWithHighResolutionCaptureEnabled:(_Bool)arg1 captureDevice:(id)arg2 rotatedToVideoOrientation:(_Bool)arg3 completionQueue:(id)arg4 completion:(CDUnknownBlockType)arg5 livePhotoCompletion:(CDUnknownBlockType)arg6;

@end

