//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/AVCaptureMetadataOutputObjectsDelegate-Protocol.h>
#import <FBSharedFramework/FBCapturePOIProcessing-Protocol.h>

@class AVCaptureConnection, AVCaptureMetadataOutput, NSString;
@protocol FBCapturePOIProcessingDelegate;

@interface FBCapturePOIAVProcessor : NSObject <AVCaptureMetadataOutputObjectsDelegate, FBCapturePOIProcessing>
{
    AVCaptureMetadataOutput *_metadataOutput;
    AVCaptureConnection *_connection;
    _Bool _enabled;
    long long _currentDevicePosition;
    id <FBCapturePOIProcessingDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <FBCapturePOIProcessingDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long currentDevicePosition; // @synthesize currentDevicePosition=_currentDevicePosition;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (void)_updateMetadataObjectTypesWithDetectionType:(long long)arg1;
- (void)_addOutputWithDisabledConnectionToCaptureSession:(id)arg1 enableAfterDelay:(double)arg2 queue:(id)arg3;
- (void)_addOutputToCaptureSession:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (_Bool)isDogObject:(id)arg1;
- (_Bool)isCatObject:(id)arg1;
- (_Bool)isHumanBodyObject:(id)arg1;
- (_Bool)isCodeObject:(id)arg1;
- (_Bool)isFaceObject:(id)arg1;
- (double)timeFromObject:(id)arg1;
- (id)dataFromObject:(id)arg1;
- (id)codeFromObject:(id)arg1;
- (struct CGRect)boundsFromObject:(id)arg1;
@property(readonly, nonatomic) _Bool acceptsSampleBuffer;
- (void)detectPOIInSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 orientation:(unsigned int)arg2;
- (void)configureWithCaptureSession:(id)arg1 detectionType:(long long)arg2 enableAfterDelay:(double)arg3 queue:(id)arg4;
- (id)initWithQueue:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

