//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@protocol FBCaptureSessionRuntimeControlling <NSObject>
- (void)updatePreviewOrientation;
- (_Bool)isRunning;
- (void)startAudioCaptureWithEchoCancellation:(_Bool)arg1 completion:(void (^)(NSError *))arg2;
- (void)stopSessionWithCompletion:(void (^)(void))arg1;
- (void)startSessionWithCompletion:(void (^)(void))arg1;
@end

