//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@protocol FBCameraAudioLevelOutput;

@protocol FBCameraAudioLevelListener <NSObject>
- (void)cameraAudioLevelOutput:(id <FBCameraAudioLevelOutput>)arg1 didChangeAudioLevelTo:(double)arg2;
@end

