//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface FBMQTTListener : NSObject
{
    NSString *_pattern;
    unsigned long long _backgroundPolicy;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    CDUnknownBlockType _jsonMessageBlock;
    CDUnknownBlockType _encodedMessageBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType encodedMessageBlock; // @synthesize encodedMessageBlock=_encodedMessageBlock;
@property(copy, nonatomic) CDUnknownBlockType jsonMessageBlock; // @synthesize jsonMessageBlock=_jsonMessageBlock;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(readonly, nonatomic) unsigned long long backgroundPolicy; // @synthesize backgroundPolicy=_backgroundPolicy;
@property(readonly, copy, nonatomic) NSString *pattern; // @synthesize pattern=_pattern;
- (id)description;
- (id)initWithTopic:(id)arg1 backgroundPolicy:(unsigned long long)arg2 callbackQueue:(id)arg3 jsonMessageBlock:(CDUnknownBlockType)arg4 encodedMessageBlock:(CDUnknownBlockType)arg5;
- (id)initWithTopic:(id)arg1 backgroundPolicy:(unsigned long long)arg2 callbackQueue:(id)arg3 encodedMessageBlock:(CDUnknownBlockType)arg4;
- (id)initWithTopic:(id)arg1 backgroundPolicy:(unsigned long long)arg2 callbackQueue:(id)arg3 jsonMessageBlock:(CDUnknownBlockType)arg4;
- (id)initWithPattern:(id)arg1 backgroundPolicy:(unsigned long long)arg2 callbackQueue:(id)arg3;

@end

