//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBValueObject.h>

#import <FBSharedFramework/NSCoding-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>

@class FBPayDefaultCardInfo, NSArray, NSDictionary, NSString;

@interface FBPayPaymentMethodViewModel : FBValueObject <NSCopying, NSCoding>
{
    _Bool _isExpired;
    long long _paymentType;
    NSString *_paymentLogoImageURL;
    NSString *_mainLabelText;
    NSString *_secondaryLabelText;
    NSArray *_availableCardCategories;
    NSArray *_availableCardTypes;
    NSArray *_additionalFieldsInfo;
    NSDictionary *_cardDetailsInfo;
    NSDictionary *_payPalAccountData;
    NSDictionary *_shopPayAccountDetails;
    FBPayDefaultCardInfo *_defaultInfo;
    NSString *_optionalWebLinkURL;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isExpired; // @synthesize isExpired=_isExpired;
@property(readonly, copy, nonatomic) NSString *optionalWebLinkURL; // @synthesize optionalWebLinkURL=_optionalWebLinkURL;
@property(readonly, copy, nonatomic) FBPayDefaultCardInfo *defaultInfo; // @synthesize defaultInfo=_defaultInfo;
@property(readonly, copy, nonatomic) NSDictionary *shopPayAccountDetails; // @synthesize shopPayAccountDetails=_shopPayAccountDetails;
@property(readonly, copy, nonatomic) NSDictionary *payPalAccountData; // @synthesize payPalAccountData=_payPalAccountData;
@property(readonly, copy, nonatomic) NSDictionary *cardDetailsInfo; // @synthesize cardDetailsInfo=_cardDetailsInfo;
@property(readonly, copy, nonatomic) NSArray *additionalFieldsInfo; // @synthesize additionalFieldsInfo=_additionalFieldsInfo;
@property(readonly, copy, nonatomic) NSArray *availableCardTypes; // @synthesize availableCardTypes=_availableCardTypes;
@property(readonly, copy, nonatomic) NSArray *availableCardCategories; // @synthesize availableCardCategories=_availableCardCategories;
@property(readonly, copy, nonatomic) NSString *secondaryLabelText; // @synthesize secondaryLabelText=_secondaryLabelText;
@property(readonly, copy, nonatomic) NSString *mainLabelText; // @synthesize mainLabelText=_mainLabelText;
@property(readonly, copy, nonatomic) NSString *paymentLogoImageURL; // @synthesize paymentLogoImageURL=_paymentLogoImageURL;
@property(readonly, nonatomic) long long paymentType; // @synthesize paymentType=_paymentType;
- (id)initWithPaymentType:(long long)arg1 paymentLogoImageURL:(id)arg2 mainLabelText:(id)arg3 secondaryLabelText:(id)arg4 availableCardCategories:(id)arg5 availableCardTypes:(id)arg6 additionalFieldsInfo:(id)arg7 cardDetailsInfo:(id)arg8 payPalAccountData:(id)arg9 shopPayAccountDetails:(id)arg10 defaultInfo:(id)arg11 optionalWebLinkURL:(id)arg12 isExpired:(_Bool)arg13;

@end

