//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBPayLoadingAnimationView, FBTimer, NSLayoutConstraint, NSString, UIActivityIndicatorView, UIButton, UILabel;
@protocol FBPayLoadingAnimationButtonDelegate;

@interface FBPayLoadingAnimationButton : UIView
{
    UIButton *_button;
    UILabel *_buttonLabel;
    NSString *_buttonTitle;
    _Bool _didBeginSlowProcessingAnimation;
    FBTimer *_timer;
    UILabel *_slowProcessingLabel;
    FBPayLoadingAnimationView *_loadingAnimationView;
    UIView *_shimmerOverlayView;
    _Bool _isButtonEnabled;
    NSLayoutConstraint *_buttonViewWidthConstraint;
    UIActivityIndicatorView *_activityIndicatorView;
    struct FBPayAccessibilityDataModel _accessibilityModel;
    id <FBPayLoadingAnimationButtonDelegate> _delegate;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) __weak id <FBPayLoadingAnimationButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (id)_constraintsForSlowProcessingLabel;
- (id)_constraintsForLoadingAnimationView;
- (id)_constraintsForButtonLabel;
- (id)_constraintsForButtonView;
- (void)_setupConstraints;
- (void)_restoreSlowProcessingAnimationIfNeeded;
- (void)_beginSlowProcessingAnimation;
- (void)_beginSpinningLockAnimation;
- (void)_hideButtonView;
- (void)_shrinkButtonView;
- (void)_onButtonTapped;
- (void)_setupSlowProcessingLabel;
- (void)_setupLoadingAnimationView;
- (void)_setupButtonLabel;
- (void)_setupButtonView;
- (void)finishProcessingAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)startPaymentProcessingAnimation;
- (void)dismissSystemSpinnerOnButton;
- (void)showSystemSpinnerOnButton;
- (void)setButtonEnabled:(_Bool)arg1;
- (void)dismissShimmer;
- (void)showShimmer;
- (void)updateTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2;

@end

