//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBValueObject.h>

#import <FBSharedFramework/NSCoding-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>

@class NSString;

@interface FBPayTableViewConfiguration : FBValueObject <NSCopying, NSCoding>
{
    long long _tableViewStyle;
    NSString *_title;
    NSString *_subtitle;
    struct UIEdgeInsets _contentInsets;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(readonly, nonatomic) long long tableViewStyle; // @synthesize tableViewStyle=_tableViewStyle;
- (id)initWithTableViewStyle:(long long)arg1 contentInsets:(struct UIEdgeInsets)arg2 title:(id)arg3 subtitle:(id)arg4;

@end

