//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBVideoProcessorDiscardDrawsUntilLoaded : NSObject
{
    float _delay;
    CDUnknownBlockType _condition;
}

- (void).cxx_destruct;
- (_Bool)renderWithTime:(CDStruct_1b6d18a9)arg1 block:(CDUnknownBlockType)arg2;
- (_Bool)_shouldDiscard;
- (void)setSlowLoading:(_Bool)arg1 condition:(CDUnknownBlockType)arg2;

@end

