//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/NSCopying-Protocol.h>

@class NSDictionary, NSString;

@interface FBVideoConfig : NSObject <NSCopying>
{
    NSDictionary *_config;
    unsigned int _resolution;
    unsigned int _width;
    unsigned int _height;
    NSString *_codec;
    double _bitrate;
    double _keyframeInterval;
    CDUnknownBlockType _assetReaderOutputFactory;
    NSDictionary *_additionalWriterInputParams;
    NSDictionary *_additionalReaderOutputParams;
    NSDictionary *_additionalSourcePixelBufferAttributes;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *additionalSourcePixelBufferAttributes; // @synthesize additionalSourcePixelBufferAttributes=_additionalSourcePixelBufferAttributes;
@property(readonly, copy, nonatomic) NSDictionary *additionalReaderOutputParams; // @synthesize additionalReaderOutputParams=_additionalReaderOutputParams;
@property(readonly, copy, nonatomic) NSDictionary *additionalWriterInputParams; // @synthesize additionalWriterInputParams=_additionalWriterInputParams;
@property(readonly, copy, nonatomic) CDUnknownBlockType assetReaderOutputFactory; // @synthesize assetReaderOutputFactory=_assetReaderOutputFactory;
@property(readonly, nonatomic) double keyframeInterval; // @synthesize keyframeInterval=_keyframeInterval;
@property(readonly, nonatomic) double bitrate; // @synthesize bitrate=_bitrate;
@property(readonly, nonatomic) unsigned int height; // @synthesize height=_height;
@property(readonly, nonatomic) unsigned int width; // @synthesize width=_width;
@property(readonly, nonatomic) unsigned int resolution; // @synthesize resolution=_resolution;
@property(readonly, copy, nonatomic) NSString *codec; // @synthesize codec=_codec;
- (id)toDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDictionary:(id)arg1;

@end

