//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FNFDashFetchable-Protocol.h>

@class FNFDashBaseDecodeContainer, FNFDashChunkHeader, NSArray, NSError, NSString;
@protocol FNFDashHeading;

@protocol FNFDashFraming <FNFDashFetchable>
@property(readonly, nonatomic) struct opaqueCMFormatDescription *videoFormatDescription;
@property(nonatomic) _Bool allFramesRetrieved;
@property(readonly, nonatomic) unsigned char parseState;
@property(readonly, nonatomic) CDStruct_1b6d18a9 duration;
@property(readonly, nonatomic) double segmentEndTimestamp;
@property(readonly, nonatomic) double segmentStartTimestamp;
@property(readonly, nonatomic) int sequenceIndex;
- (NSString *)fetchUrl;
- (int)emsgCount;
- (NSArray *)emsgs;
- (_Bool)enableEmsgParsingV2;
- (double)extraMessageEndTime;
- (double)extraMessageStartTime;
- (unsigned char)extraMessageType;
- (NSString *)extraMessage;
- (void)setHeader:(id <FNFDashHeading>)arg1;
- (FNFDashChunkHeader *)rawChunkHeader;
- (FNFDashBaseDecodeContainer *)endBaseDecodeTime;
- (unsigned long long)codecFormat;
- (_Bool)shouldResetToBeginning;
- (_Bool)hasMoreFrames;
- (void)advanceFrame;
- (const char *)currentFrameData;
- (CDStruct_72d0e578)currentFrameMetadata;
- (CDStruct_1b6d18a9)latestTimeLoaded;
- (NSError *)parseError;
- (_Bool)parseSucceeded;
@end

