//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate;
@protocol FXMasterAccountCacheHelper;

@interface FXMasterAccountCache : NSObject
{
    id <FXMasterAccountCacheHelper> _helper;
    NSArray *_linkedAccounts;
    NSDate *_timestamp;
}

- (void).cxx_destruct;
- (void)logCacheEvent_INTERNAL_ONLY:(id)arg1 withCallerName:(id)arg2 callerClass:(id)arg3 serviceNames:(id)arg4 errorMessage:(id)arg5;
- (void)_populateCacheFromDataOnDisk;
- (void)cacheLinkedAccounts_INTERNAL_ONLY:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (void)fetchInfoFromServerWithCallerName:(id)arg1 fromClass:(id)arg2 WithSuccessBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (id)getLinkedAccountsWithAccountType:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (id)getLinkedAccountsWithCallerName:(id)arg1 fromClass:(id)arg2;
- (id)initWithHelper:(id)arg1;

@end

