//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FXMasterAccountCache, NSMutableDictionary;
@protocol FXServiceCacheHelper;

@interface FXServiceCache : NSObject
{
    NSMutableDictionary *_services;
    NSMutableDictionary *_timestamps;
    FXMasterAccountCache *_masterAccountCache;
    id <FXServiceCacheHelper> _helper;
}

- (void).cxx_destruct;
- (void)_populateCacheFromDisk;
- (void)removeServiceConfigs_INTERNAL_ONLY:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (void)cacheServiceConfigs_INTERNAL_ONLY:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (void)refreshServicesFromServer:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3 withSuccessBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (id)getIdentityMappings:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (id)getIdentityMapping:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (id)getServiceStatuses:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (id)getServiceStatus:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (id)_getServices:(id)arg1 withCallerName:(id)arg2 fromClass:(id)arg3;
- (id)initWithHelper:(id)arg1 andAccountCache:(id)arg2;

@end

