//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGViewController.h>

#import <FBSharedFramework/IGAccountTypeCellSectionControllerDelegate-Protocol.h>
#import <FBSharedFramework/IGDismissableViewController-Protocol.h>
#import <FBSharedFramework/IGListAdapterDataSource-Protocol.h>

@class IGListAdapter, IGProHeaderViewModel, NSMutableArray, NSString, UICollectionView;
@protocol IGAccountTypeSelectionViewControllerDelegate, IGInterestAccountLoggingProviding, IGListDiffable;

@interface IGAccountTypeSelectionViewController : IGViewController <IGAccountTypeCellSectionControllerDelegate, IGDismissableViewController, IGListAdapterDataSource>
{
    IGListAdapter *_listAdapter;
    UICollectionView *_collectionView;
    NSMutableArray<IGListDiffable> *_viewModels;
    id <IGAccountTypeSelectionViewControllerDelegate> _delegate;
    IGProHeaderViewModel *_headerViewModel;
    id <IGInterestAccountLoggingProviding> _loggingProvider;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGInterestAccountLoggingProviding> loggingProvider; // @synthesize loggingProvider=_loggingProvider;
- (void)didDismissViewController;
- (void)accountTypeCellSectionController:(id)arg1 didTapSelectButtonWithViewModel:(id)arg2;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (_Bool)allowsNavigationGestureForGestureOrigin:(struct CGPoint)arg1;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (_Bool)prefersNavigationBarDividerHidden;
- (_Bool)prefersNavigationBarHidden;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)_initializeViewModels;
- (void)_setupCollectionView;
- (void)_setupNavigationBar;
- (id)initWithDelegate:(id)arg1 headerViewModel:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

