//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@class IGPartialModalSheetViewController;

@protocol IGAccountSwitcherPresenting <NSObject>
- (void)didDismissAccountSwitcher;
- (void)dismissAccountSwitcherPartialSheet:(IGPartialModalSheetViewController *)arg1 animated:(_Bool)arg2 completion:(void (^)(void))arg3;
- (void)showAccountSwitcherPartialSheet:(IGPartialModalSheetViewController *)arg1 completion:(void (^)(void))arg2;
@end

