//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/NSCopying-Protocol.h>
#import <FBSharedFramework/NSSecureCoding-Protocol.h>

@class NSArray, NSMutableArray;

@interface IGAnimationCurve : NSObject <NSCopying, NSSecureCoding>
{
    NSMutableArray *_keyFrames;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *keyFrames; // @synthesize keyFrames=_keyFrames;
- (_Bool)isEqualToAnimationCurve:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (double)valueAtTime:(double)arg1;
- (void)addKeyFrame:(id)arg1;
- (void)addLinearKeyFrameAtTime:(double)arg1 value:(double)arg2;
- (void)addHoldKeyFrameAtTime:(double)arg1 value:(double)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithKeyFrames:(id)arg1;
- (id)init;

@end

