//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class IGARDownloadStorage, IGRequestPolicy, IGURLRequest, NSObject;
@protocol IGAPIClient, IGRequestToken, OS_dispatch_queue;

@interface IGARDownloadOperation : NSOperation
{
    id <IGAPIClient> _networker;
    IGURLRequest *_request;
    IGRequestPolicy *_policy;
    IGARDownloadStorage *_storage;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _completionBlock;
    CDUnknownBlockType _errorBlock;
    id <IGRequestToken> _requestToken;
    NSObject<OS_dispatch_queue> *_executionQueue;
    _Bool _finished;
    _Bool _executing;
}

- (void).cxx_destruct;
- (void)_assetDownloadOperationDidFinishExecuting;
- (void)_assetDownloadOperationDidStartExecuting;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (void)_handleFailure:(id)arg1;
- (void)_handleStorageFailure:(id)arg1;
- (void)_handleRequestSuccess:(id)arg1;
- (void)_handleBytesReceived:(const char *)arg1 length:(unsigned long long)arg2 totalBytesExpectedToReceive:(long long)arg3;
- (void)_handleReceivedResponse:(id)arg1;
- (void)_cancel;
- (void)cancel;
- (void)start;
- (id)initWithNetworker:(id)arg1 storage:(id)arg2 remoteURL:(id)arg3 priority:(long long)arg4 executionQueue:(id)arg5 callbackQueue:(id)arg6 progressBlock:(CDUnknownBlockType)arg7 completionBlock:(CDUnknownBlockType)arg8 errorBlock:(CDUnknownBlockType)arg9;

@end

