//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBValueObject.h>

#import <FBSharedFramework/NSCoding-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>

@class NSString, NSURL;

@interface IGAudio : FBValueObject <NSCopying, NSCoding>
{
    NSString *_mediaId;
    NSString *_userPk;
    NSString *_organicTrackingToken;
    NSURL *_playbackURL;
    unsigned long long _durationMs;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long durationMs; // @synthesize durationMs=_durationMs;
@property(readonly, copy, nonatomic) NSURL *playbackURL; // @synthesize playbackURL=_playbackURL;
@property(readonly, copy, nonatomic) NSString *organicTrackingToken; // @synthesize organicTrackingToken=_organicTrackingToken;
@property(readonly, copy, nonatomic) NSString *userPk; // @synthesize userPk=_userPk;
@property(readonly, copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithMediaId:(id)arg1 userPk:(id)arg2 organicTrackingToken:(id)arg3 playbackURL:(id)arg4 durationMs:(unsigned long long)arg5;
- (id)initWithCoder:(id)arg1;

@end

