//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import <FBSharedFramework/IGCoreTextLinkHandler-Protocol.h>

@class IGBottomButtonsViewStyle, IGCoreTextView, IGTextButton, NSString, UIActivityIndicatorView;

@interface IGBottomButtonsView : UIView <IGCoreTextLinkHandler>
{
    NSString *_annotatedFooterString;
    IGBottomButtonsViewStyle *_style;
    IGTextButton *_primaryButton;
    NSString *_primaryButtonTitle;
    IGTextButton *_secondaryButton;
    IGCoreTextView *_footerTextView;
    UIActivityIndicatorView *_spinner;
    UIView *_separator;
    _Bool _isPrimaryButtonFullWidth;
    _Bool _isOnMedia;
    _Bool _separatorLineHidden;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool separatorLineHidden; // @synthesize separatorLineHidden=_separatorLineHidden;
- (double)_layoutFooterViewAtYOrigin:(double)arg1;
- (double)_layoutSecondaryButtonAtYOrigin:(double)arg1;
- (double)_layoutPrimaryButtonAtYOrigin:(double)arg1;
- (struct CGSize)_footerViewSize:(struct CGSize)arg1;
- (struct CGSize)_footerViewSize;
- (struct CGSize)_secondaryButtonSize:(struct CGSize)arg1;
- (struct CGSize)_secondaryButtonSize;
- (struct CGSize)_primaryButtonSize:(struct CGSize)arg1;
- (struct CGSize)_primaryButtonSize;
- (void)_secondaryButtonTapped:(id)arg1;
- (void)_primaryButtonTapped:(id)arg1;
- (id)_footerStyledString:(id)arg1;
- (void)_setupFooterViewForAnnotatedString:(id)arg1 isOnMediaStyleEnabled:(_Bool)arg2;
- (void)_setupSecondaryButtonWithTitle:(id)arg1 isDestructive:(_Bool)arg2;
- (void)_setupPrimaryButtonWithTitle:(id)arg1 style:(long long)arg2;
- (void)_setupPrimaryButtonWithTitle:(id)arg1;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)setTitle:(id)arg1;
- (void)setSecondaryButtonPressed_SNAPSHOT_TEST_ONLY:(_Bool)arg1;
- (void)setPrimaryButtonPressed_SNAPSHOT_TEST_ONLY:(_Bool)arg1;
- (void)dockToBottomOfHostView:(id)arg1;
- (void)setSecondaryButtonHidden:(_Bool)arg1;
- (void)setPrimaryButtonHidden:(_Bool)arg1;
- (void)setAnnotatedFooterString:(id)arg1;
- (void)enabledOnMediaStyle;
- (_Bool)isPrimaryButtonEnabled;
- (void)setSecondaryButtonEnabled:(_Bool)arg1;
- (void)setPrimaryButtonEnabled:(_Bool)arg1;
- (void)setButtonsEnabled:(_Bool)arg1;
- (void)setLoading:(_Bool)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

