//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGVideoTimelineThumbnailProvider-Protocol.h>

@class IGStoryBoomerangCaptureResult, NSString;
@protocol IGVideoTimelineThumbnailProviderDelegate;

@interface IGBoomerangThumbnailProvider : NSObject <IGVideoTimelineThumbnailProvider>
{
    IGStoryBoomerangCaptureResult *_boomerangCaptureResult;
    id <IGVideoTimelineThumbnailProviderDelegate> _delegate;
    long long _thumbnailCount;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long thumbnailCount; // @synthesize thumbnailCount=_thumbnailCount;
@property(nonatomic) __weak id <IGVideoTimelineThumbnailProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)cancel;
- (void)generateThumbnailsWithCount:(long long)arg1 displaySize:(struct CGSize)arg2 launcherSetProvider:(id)arg3;
- (id)initWithBoomerangCaptureResult:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

