//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGListDiffable-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>
#import <FBSharedFramework/NSSecureCoding-Protocol.h>

@class IGBrowserRatingsAndReviewsInfo, IGBrowserSessionLoggingInfoModel, IGUserSession, NSNumber, NSString, NSURL, NSURLRequest;
@protocol IGBrowserPresentationDelegate, IGInstantExperienceScriptMessageHandling;

@interface IGBrowserSession : NSObject <NSSecureCoding, NSCopying, IGListDiffable>
{
    _Bool _forceFreshLoad;
    _Bool _useURLSafetyCheck;
    NSString *_sessionID;
    NSURLRequest *_urlRequest;
    unsigned long long _urlSource;
    IGUserSession *_userSession;
    unsigned long long _options;
    id <IGBrowserPresentationDelegate> _presentationDelegate;
    id <IGInstantExperienceScriptMessageHandling> _scriptMessageHandler;
    NSURL *_redirectURL;
    NSString *_presenterModule;
    IGBrowserSessionLoggingInfoModel *_loggingInfoModel;
    IGBrowserRatingsAndReviewsInfo *_ratingsAndReviewsInfo;
}

+ (_Bool)supportsSecureCoding;
+ (id)createBrowserSessionFromBrowserPreservationModel:(id)arg1 userSession:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) IGBrowserRatingsAndReviewsInfo *ratingsAndReviewsInfo; // @synthesize ratingsAndReviewsInfo=_ratingsAndReviewsInfo;
@property(readonly, nonatomic) _Bool useURLSafetyCheck; // @synthesize useURLSafetyCheck=_useURLSafetyCheck;
@property(readonly, nonatomic) _Bool forceFreshLoad; // @synthesize forceFreshLoad=_forceFreshLoad;
@property(readonly, nonatomic) IGBrowserSessionLoggingInfoModel *loggingInfoModel; // @synthesize loggingInfoModel=_loggingInfoModel;
@property(readonly, copy, nonatomic) NSString *presenterModule; // @synthesize presenterModule=_presenterModule;
@property(readonly, copy, nonatomic) NSURL *redirectURL; // @synthesize redirectURL=_redirectURL;
@property(readonly, nonatomic) id <IGInstantExperienceScriptMessageHandling> scriptMessageHandler; // @synthesize scriptMessageHandler=_scriptMessageHandler;
@property(readonly, nonatomic) __weak id <IGBrowserPresentationDelegate> presentationDelegate; // @synthesize presentationDelegate=_presentationDelegate;
@property(readonly, nonatomic) unsigned long long options; // @synthesize options=_options;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) unsigned long long urlSource; // @synthesize urlSource=_urlSource;
@property(readonly, nonatomic) NSURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
@property(readonly, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
@property(readonly, copy, nonatomic) NSNumber *campaignId;
@property(readonly, copy, nonatomic) NSString *adDestination;
@property(readonly, copy, nonatomic) NSString *adTrackingToken;
- (id)browserLoggingExtra;
- (id)initWithURLRequest:(id)arg1 urlSource:(unsigned long long)arg2 userSession:(id)arg3 options:(unsigned long long)arg4 presentationDelegate:(id)arg5 scriptMessageHandler:(id)arg6 redirectURL:(id)arg7 presenterModule:(id)arg8 loggingInfoModel:(id)arg9 forceFreshLoad:(_Bool)arg10 useURLSafetyCheck:(_Bool)arg11 ratingsAndReviewsInfo:(id)arg12;

@end

