//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGListSectionController.h>

@class IGBusinessConversionEditAddressViewModel;
@protocol IGBusinessConversionEditAddressSectionControllerDelegate;

@interface IGBusinessConversionEditAddressSectionController : IGListSectionController
{
    IGBusinessConversionEditAddressViewModel *_viewModel;
    id <IGBusinessConversionEditAddressSectionControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (id)cellForItemAtIndex:(long long)arg1;
- (void)didSelectItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (void)didUpdateToObject:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

