//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/NSCopying-Protocol.h>

@class NSSet;

@interface IGCameraLoggerAutoCreatedClipLoggingMetadata : NSObject <NSCopying>
{
    NSSet *_storyPks;
    NSSet *_autoCreatedClipSources;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSSet *autoCreatedClipSources; // @synthesize autoCreatedClipSources=_autoCreatedClipSources;
@property(readonly, nonatomic) NSSet *storyPks; // @synthesize storyPks=_storyPks;
- (void)appendMetadata:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSources:(id)arg1 storyPks:(id)arg2;
- (id)initWithSource:(long long)arg1 storyPk:(id)arg2;

@end

