//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBIvarBasedEqualityObject.h>

#import <FBSharedFramework/NSCoding-Protocol.h>

@class NSURL;

@interface IGCommentAttachment : FBIvarBasedEqualityObject <NSCoding>
{
    unsigned long long _subtype;
    NSURL *_image_imageURL;
    _Bool _image_animated;
}

+ (id)unsupported;
+ (id)unavailable;
+ (id)imageWithImageURL:(id)arg1 animated:(_Bool)arg2;
- (void).cxx_destruct;
- (void)matchUnavailable:(CDUnknownBlockType)arg1 unsupported:(CDUnknownBlockType)arg2 image:(CDUnknownBlockType)arg3;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

