//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/NSCopying-Protocol.h>
#import <FBSharedFramework/NSSecureCoding-Protocol.h>

@class IGCompositionFilter, NSArray;

@interface IGCompositionFilterMetadata : NSObject <NSSecureCoding, NSCopying>
{
    NSArray *_gradientColors;
    IGCompositionFilter *_filter;
    struct CGSize _outputSize;
    struct IGCompositionFilterTransform _mediaTransform;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(nonatomic) struct IGCompositionFilterTransform mediaTransform; // @synthesize mediaTransform=_mediaTransform;
@property(readonly, nonatomic) struct CGSize outputSize; // @synthesize outputSize=_outputSize;
@property(readonly, nonatomic) IGCompositionFilter *filter; // @synthesize filter=_filter;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)_initWithGradientColors:(id)arg1 compositionFilter:(id)arg2 outputSize:(struct CGSize)arg3;
- (id)initWithGradientColors:(id)arg1 outputSize:(struct CGSize)arg2;

@end

