//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGCoreGraphicsNode.h>

#import <FBSharedFramework/NSSecureCoding-Protocol.h>

@class UIImage;

@interface IGCoreGraphicsImageNode : IGCoreGraphicsNode <NSSecureCoding>
{
    UIImage *_image;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

