//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBValueObject.h>

#import <FBSharedFramework/NSCoding-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>

@class IGDirectPublishedMessageSharedStoryOrPlaceholder, IGMultiAuthorReelOwner;

@interface IGDirectPublishedMessageSharedStoryShareInfo : FBValueObject <NSCopying, NSCoding>
{
    _Bool _shouldPersistInThread;
    _Bool _isMoment;
    IGDirectPublishedMessageSharedStoryOrPlaceholder *_storyOrPlaceholder;
    IGMultiAuthorReelOwner *_reelOwner;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isMoment; // @synthesize isMoment=_isMoment;
@property(readonly, nonatomic) _Bool shouldPersistInThread; // @synthesize shouldPersistInThread=_shouldPersistInThread;
@property(readonly, copy, nonatomic) IGMultiAuthorReelOwner *reelOwner; // @synthesize reelOwner=_reelOwner;
@property(readonly, copy, nonatomic) IGDirectPublishedMessageSharedStoryOrPlaceholder *storyOrPlaceholder; // @synthesize storyOrPlaceholder=_storyOrPlaceholder;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithStoryOrPlaceholder:(id)arg1 reelOwner:(id)arg2 shouldPersistInThread:(_Bool)arg3 isMoment:(_Bool)arg4;
- (id)initWithCoder:(id)arg1;

@end

