//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import <FBSharedFramework/IGTransitionZoomViewCustomizable-Protocol.h>

@class IGDirectGradientView, IGDirectMessageBubbleLayoutSpec, IGDirectMessageBubbleStyle, NSString, UIImage;

@interface IGDirectMessageBubbleView : UIView <IGTransitionZoomViewCustomizable>
{
    IGDirectGradientView *_gradientBackgroundView;
    IGDirectMessageBubbleStyle *_bubbleStyle;
    IGDirectMessageBubbleLayoutSpec *_bubbleLayoutSpec;
    UIImage *_cornerMaskImage;
    double _maxCornerRadius;
}

- (void).cxx_destruct;
- (double)zoomTransitionViewCornerRadius;
- (void)traitCollectionDidChange:(id)arg1;
- (void)removeBubbleStyle;
- (void)applyBubbleStyle:(id)arg1;
- (void)_setupGradientBackgroundViewIfNeeded;
- (void)removeBubbleLayoutSpec;
- (void)applyBubbleLayoutSpec:(id)arg1;
- (void)_updateCornerMaskImageWithLayoutSpec:(id)arg1;
- (_Bool)hasStaticGradient;
- (void)layoutSubviews;
- (void)hideGradientViewIfNecessary;
@property(readonly, nonatomic) IGDirectGradientView *gradientView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

