//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGDirectDataSubscriptionPublishing-Protocol.h>
#import <FBSharedFramework/IGDirectMutationOptimisticStateUpdatingListener-Protocol.h>

@class IGDirectMutationManager, NSString;
@protocol IGDirectDataSubscriptionPublishingDelegate;

@interface IGDirectOptimisticStateSubscriptionPublisher : NSObject <IGDirectMutationOptimisticStateUpdatingListener, IGDirectDataSubscriptionPublishing>
{
    IGDirectMutationManager *_mutationManager;
    id <IGDirectDataSubscriptionPublishingDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_handleUpdateForOptimisticStateInfo:(id)arg1;
- (void)mutationOptimisticUpdateInfoWasDropped:(id)arg1;
- (void)mutationOptimisticUpdateInfoWasUpdated:(id)arg1;
- (void)mutationOptimisticUpdateInfoWasInserted:(id)arg1;
- (id)publisherInputsForDebugging;
- (void)stopListeningForUpdates;
- (void)startListeningForUpdatesWithDelegate:(id)arg1;
- (id)initWithMutationManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

