//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBIvarBasedEqualityObject.h>

@class IGDirectAvatarNoStoryState;

@interface IGDirectAvatarStoryState : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    IGDirectAvatarNoStoryState *_noStory;
    unsigned long long _seenStory_dotType;
    long long _unseenStory_type;
}

+ (id)unseenStoryWithType:(long long)arg1;
+ (id)seenStoryWithDotType:(unsigned long long)arg1;
+ (id)noStory:(id)arg1;
+ (id)failedUpload;
- (void).cxx_destruct;
- (void)matchNoStory:(CDUnknownBlockType)arg1 seenStory:(CDUnknownBlockType)arg2 unseenStory:(CDUnknownBlockType)arg3 failedUpload:(CDUnknownBlockType)arg4;
- (_Bool)matchBooleanNoStory:(CDUnknownBlockType)arg1 seenStory:(CDUnknownBlockType)arg2 unseenStory:(CDUnknownBlockType)arg3 failedUpload:(CDUnknownBlockType)arg4;

@end

