//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGDirectMessageFetching-Protocol.h>

@class IGDirectCache, IGObjectStores;
@protocol IGAPIClient, IGDirectInteropFeatureGating, IGUserLauncherSetProviding;

@interface IGDirectDjangoMessageNetworker : NSObject <IGDirectMessageFetching>
{
    IGDirectCache *_directCache;
    id <IGAPIClient> _networker;
    id <IGDirectInteropFeatureGating> _interopFeatureGating;
    IGObjectStores *_objectStores;
    id <IGUserLauncherSetProviding> _launcherSetProvider;
}

- (void).cxx_destruct;
- (void)_didFetchVisualMessagesWithResponseObject:(id)arg1 threadId:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchVisualMessagesForThreadId:(id)arg1 cursor:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_publishedThreadWithId:(id)arg1;
- (void)_didFetchMessages:(id)arg1 threadId:(id)arg2 successBlock:(CDUnknownBlockType)arg3;
- (void)fetchExistingMessagesWithIds:(id)arg1 clientContexts:(id)arg2 threadId:(id)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (id)initWithUserSession:(id)arg1;

@end

