//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGDirectMutationRequestStateStoreListener-Protocol.h>
#import <FBSharedFramework/IGUserSessionEndingObject-Protocol.h>

@class IGDirectMutationExternalSystemEventHandler, IGDirectMutationOptimisticUpdateInfoCache, IGDirectMutationRealtimeDeltaHandlingDelayer, IGDirectMutationRequestCoordinationCache, IGDirectMutationRequestInitiator, IGDirectMutationRequestPreparer, IGDirectMutationRequestStateStore, IGDirectMutationRequestStateStoreListeningForwarder, IGDirectMutationRequestStoreHistoricalDebugLogger, NSString;
@protocol IGAnalyticsEventLoggingProtocol, IGDirectMutationManagerAnnouncer, IGDirectMutationOptimisticStateUpdatingAnnouncer, IGDirectMutationRequestStateDiskRestoring, OS_dispatch_queue;

@interface IGDirectMutationManager : NSObject <IGDirectMutationRequestStateStoreListener, IGUserSessionEndingObject>
{
    IGDirectMutationRequestPreparer *_preparer;
    IGDirectMutationRequestInitiator *_initiator;
    id <IGDirectMutationManagerAnnouncer> _mutationManagerAnnouncer;
    id <IGDirectMutationOptimisticStateUpdatingAnnouncer> _optimisicStateUpdateAnnouncer;
    IGDirectMutationRequestStateStoreListeningForwarder *_requestStateStoreListeningForwarder;
    id <IGDirectMutationRequestStateDiskRestoring> _diskRestorer;
    IGDirectMutationRequestCoordinationCache *_requestCoordinationCache;
    IGDirectMutationOptimisticUpdateInfoCache *_optimisticStateCache;
    IGDirectMutationRequestStateStore *_requestStateStore;
    IGDirectMutationExternalSystemEventHandler *_externalEventHandler;
    IGDirectMutationRequestStoreHistoricalDebugLogger *_requestStoreHistoricalDebugLogger;
    IGDirectMutationRealtimeDeltaHandlingDelayer *_realtimeDeltaHandlerDelayer;
    id <IGAnalyticsEventLoggingProtocol> _logger;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (void)_mutationsRestoredFromDisk:(id)arg1;
- (void)_shutdown;
- (void)userSessionWillEnd;
- (void)mutationRequestStoreDidDropMutationWithId:(id)arg1 withReason:(id)arg2;
- (void)mutationRequestStoreDidEnqueueMutation:(id)arg1 withInitialExecutionState:(id)arg2;
- (void)mutationRequestStoreDidUpdateMutation:(id)arg1 fromExecutionState:(id)arg2 toExecutionState:(id)arg3;
- (id)serializableLogPackage;
- (void)removeOptimisticStateUpdateListener:(id)arg1;
- (void)addOptimisticStateUpdateListener:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (id)optimisticUpdateInfos;
- (void)startService;
- (void)manuallyRetryMutationWithId:(id)arg1;
- (void)cancelMutationWithId:(id)arg1;
- (id)runMutationWithData:(id)arg1;
- (id)initWithMutationProcessingToolboxProvider:(id)arg1 diskHandler:(id)arg2 notificationCenter:(id)arg3 networkConnectionManager:(id)arg4 directCache:(id)arg5 logger:(id)arg6 featureSets:(id)arg7 diskManager:(id)arg8 inboxService:(id)arg9 realtimeServiceAnnouncer:(id)arg10 userPk:(id)arg11 queue:(id)arg12;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

