//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGDirectThreadViewModelGenerationOutput, IGListIndexSetResult;

@interface IGDirectThreadViewModelGenerationOutputAndListDiff : NSObject
{
    IGDirectThreadViewModelGenerationOutput *_output;
    IGListIndexSetResult *_diffResult;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGListIndexSetResult *diffResult; // @synthesize diffResult=_diffResult;
@property(readonly, nonatomic) IGDirectThreadViewModelGenerationOutput *output; // @synthesize output=_output;
- (id)initWithOutput:(id)arg1 diffResult:(id)arg2;

@end

