//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGDirectResponseLogging-Protocol.h>

@class IGMediaMetricsLogger, NSString;
@protocol FBAnalyticsLogging, IGAnalyticsEventLoggingProtocol, IGFeedItemDirectResponseLoggingProviderDelegate;

@interface IGDirectResponseLogger : NSObject <IGDirectResponseLogging>
{
    id <IGAnalyticsEventLoggingProtocol> _analyticsLogger;
    IGMediaMetricsLogger *_mediaMetricsLogger;
    id <FBAnalyticsLogging> _structuredLogger;
    id <IGFeedItemDirectResponseLoggingProviderDelegate> _loggingDelegate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) __weak id <IGFeedItemDirectResponseLoggingProviderDelegate> loggingDelegate; // @synthesize loggingDelegate=_loggingDelegate;
- (void)logShoppingSheetActionForMedia:(id)arg1 userSession:(id)arg2 ctaContext:(unsigned long long)arg3 action:(id)arg4 url:(id)arg5 adMetadata:(id)arg6 module:(id)arg7;
- (void)logActionFailedForMedia:(id)arg1 feedItemTracker:(id)arg2 directResponseInfo:(id)arg3 ctaContext:(unsigned long long)arg4 analyticsModule:(id)arg5 openTarget:(id)arg6 action:(id)arg7 url:(id)arg8 sponsoredInfoProvider:(id)arg9;
- (void)logActionForMedia:(id)arg1 feedItemTracker:(id)arg2 directResponseInfo:(id)arg3 ctaContext:(unsigned long long)arg4 analyticsModule:(id)arg5 action:(id)arg6 url:(id)arg7 extraFields:(id)arg8 sponsoredInfoProvider:(id)arg9;
- (id)initWithLoggingDelegate:(id)arg1 analyticsLogger:(id)arg2 mediaMetricsLogger:(id)arg3 structuredLogger:(id)arg4;
- (id)initWithLoggingDelegate:(id)arg1 analyticsLogger:(id)arg2 mediaMetricsLogger:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

