//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IGDirectRealtimeMessageOperation : NSObject
{
    CDUnknownBlockType _successHandler;
    CDUnknownBlockType _failureHandler;
    NSString *_messageKey;
    NSString *_message;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(readonly, copy, nonatomic) NSString *messageKey; // @synthesize messageKey=_messageKey;
@property(readonly, copy, nonatomic) CDUnknownBlockType failureHandler; // @synthesize failureHandler=_failureHandler;
@property(readonly, copy, nonatomic) CDUnknownBlockType successHandler; // @synthesize successHandler=_successHandler;
- (id)initWithMessageKey:(id)arg1 message:(id)arg2 successHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;

@end

