//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGDrawBrushMark-Protocol.h>

@class IGDrawBrushBaseIGL, NSString;
@protocol IGDrawBrushCommon;

@interface IGDrawMarkFillIGL : NSObject <IGDrawBrushMark>
{
    IGDrawBrushBaseIGL *_brush;
    struct shared_ptr<iglu::drawable::Drawable> _fullScreenQuad;
    shared_ptr_8b9aca12 _material;
    struct NameHandle _colorUniformName;
    _Bool _hadToStopDueToFullBuffer;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) _Bool hadToStopDueToFullBuffer; // @synthesize hadToStopDueToFullBuffer=_hadToStopDueToFullBuffer;
- (void)setColor:(id)arg1;
- (void)idle;
- (void)endWith:(struct _IGDrawTouchSample)arg1;
- (void)addSample:(struct _IGDrawTouchSample)arg1;
- (void)startWith:(struct _IGDrawTouchSample)arg1;
- (void)prepareToDraw;
- (void)drawIncremental;
@property(readonly, nonatomic) _Bool supportsIncrementalDrawing;
- (void)draw;
@property(readonly, nonatomic) id <IGDrawBrushCommon> brush; // @synthesize brush=_brush;
- (id)initWithBrush:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

