//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@class IGSponsoredSupportConfiguration, NSArray, NSString;

@protocol IGFeedFilterType <NSObject>
@property(readonly, nonatomic) _Bool isEditable;
@property(readonly, copy, nonatomic) NSString *title;
- (_Bool)canApplyRemotely;
- (NSArray *)filterIDs;
- (NSString *)identifier;
- (NSString *)typeName;
- (_Bool)matchesItem:(id)arg1 sponsoredSupportConfiguration:(IGSponsoredSupportConfiguration *)arg2;
@end

