//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@class FNFDashSelectionMetadata, FNFDashVideoPlayerMetadata, NSArray, NSString;

@protocol IGFNFVideoProfilerDashEventListener <NSObject>
- (void)chunkFetchCompleted:(FNFDashSelectionMetadata *)arg1 playerMetadata:(FNFDashVideoPlayerMetadata *)arg2 trackType:(long long)arg3;
- (void)chunkFetchStarted:(FNFDashSelectionMetadata *)arg1 playerMetadata:(FNFDashVideoPlayerMetadata *)arg2 trackType:(long long)arg3;
- (void)availableQualitiesChanged:(NSArray *)arg1;
- (void)videoRepresentationIdChanged:(NSString *)arg1;
@end

