//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGContext;

@interface IGGLShader : NSObject
{
    unsigned int _shaderId;
    IGContext *_context;
}

- (void).cxx_destruct;
@property(nonatomic) __weak IGContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) unsigned int shaderId; // @synthesize shaderId=_shaderId;
- (id)initShaderWithSource:(id)arg1 type:(long long)arg2;
- (id)initFragmentShaderWithSource:(id)arg1;
- (id)initVertexShaderWithSource:(id)arg1;
- (void)dealloc;

@end

