//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class IGRefreshSpinner, UIColor, UIImpactFeedbackGenerator, UIScrollView;

@interface IGHorizontalRefreshControl : UIControl
{
    UIScrollView *_scrollView;
    UIImpactFeedbackGenerator *_feedbackGenerator;
    IGRefreshSpinner *_spinner;
    double _refreshBeginTime;
    double _leftContentInset;
    long long _refreshState;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long refreshState; // @synthesize refreshState=_refreshState;
- (void)_adjustContentInsetForLoading;
- (void)reset;
- (void)_animateClosed;
- (void)endRefreshing;
@property(retain, nonatomic) UIColor *color;
- (void)scrollViewDidScroll;
- (void)scrollViewDidEndDragging;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithScrollView:(id)arg1 color:(id)arg2;

@end

