//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGTextButton.h>

@class UIImage, UIImageView;

@interface IGIconAndTextButton : IGTextButton
{
    UIImageView *_iconView;
    double _spacing;
    struct CGSize _iconSize;
}

- (void).cxx_destruct;
@property(nonatomic) double spacing; // @synthesize spacing=_spacing;
@property(nonatomic) struct CGSize iconSize; // @synthesize iconSize=_iconSize;
- (_Bool)_hasIcon;
- (void)_refreshIconColor;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)stopLoading;
- (void)startLoading;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setStyle:(long long)arg1;
@property(copy, nonatomic) UIImage *icon;
- (id)initWithFrame:(struct CGRect)arg1;

@end

