//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/NSCopying-Protocol.h>
#import <FBSharedFramework/NSSecureCoding-Protocol.h>

@interface IGKeyFrame : NSObject <NSCopying, NSSecureCoding>
{
    double _time;
    double _value;
    long long _interpolationMode;
}

+ (_Bool)supportsSecureCoding;
+ (id)newWithTime:(double)arg1 value:(double)arg2 interpolationMode:(long long)arg3;
@property(readonly, nonatomic) long long interpolationMode; // @synthesize interpolationMode=_interpolationMode;
@property(readonly, nonatomic) double value; // @synthesize value=_value;
@property(readonly, nonatomic) double time; // @synthesize time=_time;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)_initWithTime:(double)arg1 value:(double)arg2 interpolationMode:(long long)arg3;

@end

