//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@class NSArray, UIImage, UIView;

@protocol IGMediaCompositionViewDrawingLayer <NSObject>
@property(readonly, nonatomic) _Bool isInitialized;
@property(readonly, nonatomic) UIView *drawingCanvasView;
@property(copy, nonatomic) NSArray *drawingBrushStrokes;
@property(readonly, nonatomic) UIImage *drawingImage;
- (void)clear;
@end

