//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIVisualEffectView.h>

@class IGBlurredImageView, IGCenterLayout, IGStackLayout, IGTapButton, NSArray, UIImageView, UILabel, UIView;
@protocol IGMediaOverlayViewDelegate;

@interface IGMediaOverlayFullView : UIVisualEffectView
{
    IGBlurredImageView *_blurredImageView;
    UIView *_tintView;
    UIImageView *_hiddenIcon;
    UILabel *_titleLabel;
    UILabel *_descriptionLabel;
    UIView *_lineView;
    IGTapButton *_bottomButton;
    IGTapButton *_centerButton;
    IGCenterLayout *_centerLayout;
    IGStackLayout *_centerStack;
    IGStackLayout *_bottomLayout;
    NSArray *_itemsWithoutCenterButton;
    NSArray *_itemsWithCenterButton;
    id <IGMediaOverlayViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IGMediaOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_didTapButton:(id)arg1;
- (id)_createCTAButtonWithSelector:(SEL)arg1;
- (id)_createBottomButtonWithSelector:(SEL)arg1;
- (id)_createLineView;
- (id)_createHiddenIcon;
- (id)_createDescriptionLabel;
- (id)_createTitleLabel;
- (id)_createTintView;
- (void)configureWithMediaOverlayModel:(id)arg1 photoForBlurView:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

