//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGMixiAuthDelegate-Protocol.h>
#import <FBSharedFramework/IGServiceHelperProtocol-Protocol.h>

@class IGUserDefaults, NSString;
@protocol IGAPIClient, IGMixiAuthAnnouncer, IGSharingServiceAuthAnnouncer;

@interface IGMixiHelper : NSObject <IGMixiAuthDelegate, IGServiceHelperProtocol>
{
    _Bool _isKeyChainFixEnabled;
    id <IGSharingServiceAuthAnnouncer> _sharingServiceAuthAnnouncer;
    id <IGMixiAuthAnnouncer> _mixiAuthAnnouncer;
    _Bool _isAvailableForSharing;
    _Bool _wantsToShare;
    _Bool _disabled;
    IGUserDefaults *_sessionUserDefaults;
    id <IGAPIClient> _networker;
    NSString *_accessToken;
}

+ (id)shortServiceName;
+ (id)sharedHelperForUserSession:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(retain, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
@property(retain, nonatomic) IGUserDefaults *sessionUserDefaults; // @synthesize sessionUserDefaults=_sessionUserDefaults;
@property(nonatomic) _Bool disabled; // @synthesize disabled=_disabled;
@property(nonatomic) _Bool wantsToShare; // @synthesize wantsToShare=_wantsToShare;
@property(nonatomic) _Bool isAvailableForSharing; // @synthesize isAvailableForSharing=_isAvailableForSharing;
- (void)_reauthorizationNeedsLogin;
- (void)_fetchTokenFinished:(id)arg1;
- (void)_onFetchTokenFailed;
- (id)_refreshToken;
- (void)_setAccessAndRefreshToken:(id)arg1 expirationInSeconds:(int)arg2 refreshToken:(id)arg3;
- (void)mixiAuthControllerLoginFailed:(id)arg1;
- (void)mixiAuthController:(id)arg1 didLoginWithCode:(id)arg2;
- (_Bool)_hasEverBeenConfigured;
- (id)sharingInfo;
- (id)shareKey;
- (id)serviceName;
- (_Bool)requiresLocationCoordinate;
- (_Bool)supportsCrosspostingWith:(id)arg1 forMediaType:(long long)arg2;
- (_Bool)supportsMediaType:(long long)arg1;
- (_Bool)isAvailableInCurrentLocale;
- (void)setupServerLinkage:(id)arg1;
- (_Bool)needsToReauthorize;
- (void)setNeedsReauthorization;
- (void)reauthorizeIfNeeded;
- (void)_reauthorize;
- (id)detailText;
- (_Bool)isConfiguredForCrossPosting;
- (_Bool)shouldUseSubtitleCellStyle;
- (_Bool)hidden;
- (_Bool)isConfiguredOnlyOnServer;
- (_Bool)isConfigured;
- (void)logout;
- (void)logoutAndUnlink;
- (_Bool)hasSelectedPrivacySetting;
@property(nonatomic) long long currentPrivacySetting;
- (id)getMixiConstantForPrivacySetting:(long long)arg1;
- (id)getLabelForPrivacySetting:(long long)arg1;
- (id)authURLString;
- (id)viewControllerForAdvancedOptionsWithUserSession:(id)arg1;
- (id)callbackURLString;
- (id)clientID;
- (id)initWithSessionUserDefaults:(id)arg1 networker:(id)arg2 mixiAuthAnnouncer:(id)arg3 sharingServiceAuthAnnouncer:(id)arg4 isKeyChainFixEnabled:(_Bool)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

