//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGModuleLayoutRepresentation, NSMutableDictionary;

@interface IGModuleResourceGraphSnapshot : NSObject
{
    NSMutableDictionary *_moduleGraph;
    IGModuleLayoutRepresentation *_currentModule;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGModuleLayoutRepresentation *currentModule; // @synthesize currentModule=_currentModule;
- (id)moduleToGraphScoreMapForItemWithIdentifier:(id)arg1;
- (id)statesContainingIdentifier:(id)arg1;
- (id)initWithCurrentState:(id)arg1 graph:(id)arg2;

@end

