//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class CALayer, CAShapeLayer;

@interface IGProgressRingView : UIView
{
    CAShapeLayer *_progress;
    CALayer *_gradientLayer;
    double _ringWidth;
}

- (void).cxx_destruct;
- (void)updateStrokeEnd:(double)arg1 animated:(_Bool)arg2;
- (void)setGradientHidden:(_Bool)arg1;
- (void)_animateGradientRotation;
- (void)layoutSubviews;
- (id)initWithRingWidth:(double)arg1 frame:(struct CGRect)arg2 ringColor:(id)arg3;
- (id)initWithRingWidth:(double)arg1 frame:(struct CGRect)arg2 gradientLayerConfig:(id)arg3;

@end

