//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class IGImageView, UILabel;

@interface IGResharedVideoStickerHeaderView : UIView
{
    IGImageView *_profilePictureImageView;
    UILabel *_headerUsernameLabel;
    UILabel *_clearHeaderUsernameLabel;
    double _headerHeight;
    double _profilePicturePadding;
}

- (void).cxx_destruct;
@property(nonatomic) double profilePicturePadding; // @synthesize profilePicturePadding=_profilePicturePadding;
@property(nonatomic) double headerHeight; // @synthesize headerHeight=_headerHeight;
- (void)_setupAndAddHeaderUsernameLabel:(id)arg1 isVerified:(_Bool)arg2;
- (void)_setupAndAddProfilePicture:(id)arg1;
- (void)setHeaderUsernameFontSize:(double)arg1;
- (void)setProfilePictureImageViewAlpha:(double)arg1;
- (void)setClearHeaderUsernameLabelAlpha:(double)arg1;
- (void)setHeaderUsernameLabelTextColor:(id)arg1;
- (void)setHeaderUsernameLabelAlpha:(double)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)configureWithProfilePicURL:(id)arg1 username:(id)arg2 isVerified:(_Bool)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithProfilePictureUrl:(id)arg1 username:(id)arg2 isVerified:(_Bool)arg3;

@end

