//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol IGAnalyticsEventLoggingProtocol;

@interface IGRemoveFollowerLogger : NSObject
{
    id <IGAnalyticsEventLoggingProtocol> _analyticsLogger;
    NSString *_module;
    NSString *_targetID;
}

- (void).cxx_destruct;
- (void)logCanceledButtonCancelled;
- (void)logRemoveDialogConfirmed;
- (void)logRemoveButtonClicked;
- (id)initWithModule:(id)arg1 analyticsLogger:(id)arg2 targetID:(id)arg3;

@end

