//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGUserSessionEndingObject-Protocol.h>

@class IGDiskManager, IGObjectDiskStorage, IGRecentSearchStoreTypeConfiguration, NSArray, NSMutableDictionary, NSMutableOrderedSet;

@interface IGRecentSearchStore : NSObject <IGUserSessionEndingObject>
{
    IGDiskManager *_diskManager;
    IGRecentSearchStoreTypeConfiguration *_recentSearchStoreConfiguration;
    NSMutableOrderedSet *_searchResults;
    IGObjectDiskStorage *_storageRecentItems;
    NSMutableDictionary *_searchResultExpirations;
    IGObjectDiskStorage *_storageRecentExpiry;
}

- (void).cxx_destruct;
- (void)userSessionWillEnd;
- (void)_archiveRecentItems:(id)arg1 resultExpirations:(id)arg2;
- (void)_archive;
- (void)_setExpirationForResult:(id)arg1;
- (void)_removeExpiredResults;
- (void)_readRecentItemsFromFile;
- (_Bool)containsItem:(id)arg1;
- (void)removeItem:(id)arg1;
- (void)archiveRecentItems;
- (void)clearHistory;
@property(readonly, nonatomic) NSMutableOrderedSet *setOfAllItems;
@property(readonly, nonatomic) NSArray *recentItems;
@property(readonly, nonatomic) NSArray *allItems;
- (_Bool)addItem:(id)arg1;
- (id)initWithDiskManager:(id)arg1 recentSearchStoreConfiguration:(id)arg2;

@end

