//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UICollectionViewLayout;
@protocol IGScrubberAnnotationDataSource, IGScrubberAnnotationDelegate;

@interface IGScrubberAnnotationState : NSObject
{
    UICollectionViewLayout *_layout;
    id <IGScrubberAnnotationDataSource> _dataSource;
    id <IGScrubberAnnotationDelegate> _delegate;
    NSString *_displayString;
    struct CGRect _viewportFrame;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGRect viewportFrame; // @synthesize viewportFrame=_viewportFrame;
@property(readonly, copy, nonatomic) NSString *displayString; // @synthesize displayString=_displayString;
@property(nonatomic) __weak id <IGScrubberAnnotationDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <IGScrubberAnnotationDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)initWithCollectionViewLayout:(id)arg1;

@end

