//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class CAShapeLayer, IGBlurredImageView, IGImageView, NSURL, UIImageView;

@interface IGShoppingProductThumbnailImageView : UIControl
{
    CAShapeLayer *_soldOutStrikethroughLayer;
    UIImageView *_unavailableIconImageView;
    IGBlurredImageView *_blurredImageView;
    UIImageView *_hiddenIconImageView;
    _Bool _highlightable;
    IGImageView *_imageView;
    NSURL *_blurredImageURL;
    long long _thumbnailState;
}

- (void).cxx_destruct;
@property(nonatomic, getter=isHighlightable) _Bool highlightable; // @synthesize highlightable=_highlightable;
@property(nonatomic) long long thumbnailState; // @synthesize thumbnailState=_thumbnailState;
@property(retain, nonatomic) NSURL *blurredImageURL; // @synthesize blurredImageURL=_blurredImageURL;
@property(readonly, nonatomic) IGImageView *imageView; // @synthesize imageView=_imageView;
- (void)_setupHiddenIconImageViewIfNeeded;
- (void)_setupUnavailableIconImageView18IfNeeded;
- (void)_setupUnavailableIconImageView24IfNeeded;
- (void)_setupSoldoutStrikethroughLayerIfNeeded;
- (void)setContentMode:(long long)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 shouldUseProgressiveJPEG:(_Bool)arg2 placeholderConfig:(id)arg3;

@end

