//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGMediaPreloaderShowreelPreloader-Protocol.h>
#import <FBSharedFramework/SNPlaybackStateListener-Protocol.h>

@class IGGraphQLService, NSMutableDictionary, NSMutableSet, NSString;
@protocol IGUserLauncherSetProviding;

@interface IGShowreelNativePreloader : NSObject <SNPlaybackStateListener, IGMediaPreloaderShowreelPreloader>
{
    IGGraphQLService *_graphQLService;
    id <IGUserLauncherSetProviding> _launcherSetProvider;
    unsigned long long _placement;
    NSMutableDictionary *_snPlaybackItemsToItems;
    NSMutableDictionary *_snPlaybackItemsToControllers;
    NSMutableSet *_snLoadedPlaybackItems;
}

- (void).cxx_destruct;
- (void)_preloadShowreelNativeInfo:(id)arg1 preloaderItem:(id)arg2 module:(id)arg3;
- (void)playerController:(id)arg1 didFailWithError:(id)arg2;
- (void)playerControllerDidLoadAsset:(id)arg1;
- (void)cancelAllRequestsExceptItems:(id)arg1;
- (void)preloadShowreelNativeWithMedia:(id)arg1 module:(id)arg2;
- (id)initWithGraphQLService:(id)arg1 launcherSetProvider:(id)arg2 placement:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

