//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol IGAPIClient;

@interface IGSSOFetcher : NSObject
{
    id <IGAPIClient> _networker;
}

- (void).cxx_destruct;
- (void)fetchSSOAccountsForTokens:(id)arg1 includeSocialContext:(_Bool)arg2 surface:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)initWithNetworker:(id)arg1;

@end

