//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/UIViewControllerAnimatedTransitioning-Protocol.h>
#import <FBSharedFramework/UIViewControllerTransitioningDelegate-Protocol.h>

@class NSString, UIView, UIViewController;
@protocol IGStoryStickerEditingViewControllerProtocol, UIViewControllerContextTransitioning;

@interface IGStoryEditableStickerZoomTransitionController : NSObject <UIViewControllerAnimatedTransitioning, UIViewControllerTransitioningDelegate>
{
    _Bool _isPresentationTransition;
    _Bool _shouldPositionWithNewDefaults;
    struct CGPoint _initialCenterPointInWindowCoordinates;
    double _initialScale;
    double _initialRotation;
    id <UIViewControllerContextTransitioning> _transitionContext;
    UIView *_controlsOverlayView;
    UIView *_stickerContainerView;
    UIViewController<IGStoryStickerEditingViewControllerProtocol> *_stickerEditingViewController;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) __weak UIViewController<IGStoryStickerEditingViewControllerProtocol> *stickerEditingViewController; // @synthesize stickerEditingViewController=_stickerEditingViewController;
@property(readonly, nonatomic) __weak UIView *stickerContainerView; // @synthesize stickerContainerView=_stickerContainerView;
@property(readonly, nonatomic) __weak UIView *controlsOverlayView; // @synthesize controlsOverlayView=_controlsOverlayView;
- (void)animateDismissalTransition:(id)arg1;
- (void)animatePresentationTransition:(id)arg1;
- (void)animateTransition:(id)arg1;
- (void)animationEnded:(_Bool)arg1;
- (double)transitionDuration:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)initWithControlsOverlayView:(id)arg1 stickerContainerView:(id)arg2 stickerEditingViewController:(id)arg3 shouldPositionWithNewDefaults:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

