//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IGStoryCreationAssetPreparer : NSObject
{
}

+ (id)createOverlayImageOfSize:(struct CGSize)arg1 withOverlays:(id)arg2 containerSize:(struct CGSize)arg3;
+ (id)createFinalImageWithEditsForOutputAsset:(id)arg1 creationEdits:(id)arg2;

@end

