//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/IGValueObject.h>

#import <FBSharedFramework/NSCoding-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>

@interface IGStoryFullscreenProgressViewModel : IGValueObject <NSCopying, NSCoding>
{
}

+ (void)initialize;
+ (id)progressAfterConsumingSegmentContinuousViewModel;
+ (id)progressAfterConsumingSegmentViewModel;
+ (id)singleSegmentHighlightWithProgressViewModel;
+ (id)singleSegmentHighlightViewModel;
+ (id)thinWithNoProgress:(double)arg1;
+ (id)defaultWithNoProgress;
+ (id)grabberBarWithSubtleProgressViewModel;
+ (id)grabberBarViewModel;
+ (id)paginatedViewModel;
+ (id)sundialViewModel;
+ (id)topScrubberViewModel;
+ (id)scrubberViewModel;
+ (id)defaultViewModel;

@end

