//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGMediaAsset-Protocol.h>
#import <FBSharedFramework/IGStoryMediaAsset-Protocol.h>

@class IGAsyncTask, IGSampleBuffer, IGStoryPhotoBoothVideoExporter, NSString, UIImage;

@interface IGStoryPhotoBoothCaptureResult : NSObject <IGMediaAsset, IGStoryMediaAsset>
{
    struct CGSize _mediaSize;
    IGAsyncTask *_videoGenerationTask;
    IGStoryPhotoBoothVideoExporter *_videoExporter;
    UIImage *_previewImage;
    IGAsyncTask *_sampleBuffers;
    IGSampleBuffer *_previewSampleBuffer;
    unsigned long long _photoBoothMode;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long photoBoothMode; // @synthesize photoBoothMode=_photoBoothMode;
@property(readonly, nonatomic) IGSampleBuffer *previewSampleBuffer; // @synthesize previewSampleBuffer=_previewSampleBuffer;
@property(readonly, nonatomic) IGAsyncTask *sampleBuffers; // @synthesize sampleBuffers=_sampleBuffers;
- (id)_photoBoothAssetWithSampleBuffers:(id)arg1;
- (void)fetchBoomerangAssetWithResultHandler:(CDUnknownBlockType)arg1;
- (void)fetchVideoWithUserSession:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;
- (void)fetchPhotoBoothAssetWithResultHandler:(CDUnknownBlockType)arg1;
- (void)fetchImageOfSize:(struct CGSize)arg1 atTime:(CDStruct_1b6d18a9)arg2 resultHandler:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) double videoDuration;
@property(readonly, nonatomic) long long assetType;
@property(readonly, nonatomic) struct CGSize mediaSize;
- (id)renderer;
@property(readonly, nonatomic) IGAsyncTask *ig_preferredTransform;
@property(readonly, nonatomic) _Bool ig_isLoopable;
@property(readonly, nonatomic) double ig_mediaDuration;
@property(readonly, nonatomic) struct CGSize ig_mediaSize;
@property(readonly, nonatomic) IGAsyncTask *hasAudio;
- (id)generateVideoWithUserSession:(id)arg1 igglkSession:(id)arg2;
- (id)initWithSampleBuffers:(id)arg1 mediaSize:(struct CGSize)arg2 previewSampleBuffer:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

