//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGAudioConfig, IGSegmentsConfig, IGTranscoderFrameRequest, IGVideoConfig;

@interface IGTranscoderConfig : NSObject
{
    IGSegmentsConfig *_segmentsConfig;
    IGVideoConfig *_videoConfig;
    IGAudioConfig *_audioConfig;
    IGTranscoderFrameRequest *_frameRequest;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGTranscoderFrameRequest *frameRequest; // @synthesize frameRequest=_frameRequest;
@property(readonly, nonatomic) IGAudioConfig *audioConfig; // @synthesize audioConfig=_audioConfig;
@property(readonly, nonatomic) IGVideoConfig *videoConfig; // @synthesize videoConfig=_videoConfig;
@property(readonly, nonatomic) IGSegmentsConfig *segmentsConfig; // @synthesize segmentsConfig=_segmentsConfig;
- (id)initWithSegmentsConfig:(id)arg1 videoConfig:(id)arg2 audioConfig:(id)arg3 frameRequest:(id)arg4;

@end

