//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/IGUserBlockLogging-Protocol.h>

@class IGUser, IGUserSession, NSString;
@protocol IGAnalyticsEventLoggingProtocol;

@interface IGUserBlockLogger : NSObject <IGUserBlockLogging>
{
    id <IGAnalyticsEventLoggingProtocol> _analyticsLogger;
    NSString *_module;
    NSString *_targetID;
    IGUserSession *_userSession;
    IGUser *_targetUser;
    long long _entryPoint;
    NSString *_requestId;
}

- (void).cxx_destruct;
- (void)logBlockDialogConfirmedForState:(long long)arg1;
- (void)logBlockActionFailureForState:(long long)arg1;
- (void)logBlockDialogCancelledForState:(long long)arg1;
- (void)logBlockActionSuccessForState:(long long)arg1;
- (void)logBlockButtonTappedForState:(long long)arg1;
- (void)logBlockImpressionForState:(long long)arg1;
- (void)_logUnblockDialogCancelled;
- (void)_logUnblockActionSuccess;
- (void)_logUnblockButtonTapped;
- (void)_logBlockDialogCancelled;
- (void)_logBlockActionSuccess;
- (void)_logBlockButtonTapped;
- (id)initWithUserSession:(id)arg1 module:(id)arg2 clickPoint:(long long)arg3 targetUser:(id)arg4 requestId:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

