//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IGAudioSession, NSMutableArray, NSString;
@protocol OS_dispatch_queue;

@interface IGVideoReportHelper : NSObject
{
    NSMutableArray *_lastPlayedMediaIds;
    long long _numPlayingVideos;
    NSMutableArray *_recentUploadIds;
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_inMemoryReportVideoId;
    IGAudioSession *_session;
}

+ (id)sharedHelper;
- (void).cxx_destruct;
- (id)recentlyCommittedUploadIds;
- (void)addCommittedUploadId:(id)arg1;
- (id)lastPlayedMediaIds;
- (id)_reportDeviceVolume;
- (id)_reportCreatorId;
- (id)_reportVideoId;
- (void)addPlayedMediaId:(id)arg1;
@property(nonatomic) long long numPlayingVideos;
- (id)init;

@end

