//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface IGViewTreeEventAnnouncingView : UIView
{
    CDUnknownBlockType _onDidAddSubview;
    CDUnknownBlockType _onWillRemoveSubview;
    CDUnknownBlockType _onWillMoveToSuperview;
    CDUnknownBlockType _onDidMoveToSuperview;
    CDUnknownBlockType _onWillMoveToWindow;
    CDUnknownBlockType _onDidMoveToWindow;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType onDidMoveToWindow; // @synthesize onDidMoveToWindow=_onDidMoveToWindow;
@property(copy, nonatomic) CDUnknownBlockType onWillMoveToWindow; // @synthesize onWillMoveToWindow=_onWillMoveToWindow;
@property(copy, nonatomic) CDUnknownBlockType onDidMoveToSuperview; // @synthesize onDidMoveToSuperview=_onDidMoveToSuperview;
@property(copy, nonatomic) CDUnknownBlockType onWillMoveToSuperview; // @synthesize onWillMoveToSuperview=_onWillMoveToSuperview;
@property(copy, nonatomic) CDUnknownBlockType onWillRemoveSubview; // @synthesize onWillRemoveSubview=_onWillRemoveSubview;
@property(copy, nonatomic) CDUnknownBlockType onDidAddSubview; // @synthesize onDidAddSubview=_onDidAddSubview;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)arg1;
- (void)didMoveToSuperview;
- (void)willMoveToSuperview:(id)arg1;
- (void)willRemoveSubview:(id)arg1;
- (void)didAddSubview:(id)arg1;

@end

