//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/NSObject-Protocol.h>

@class IGVideoTimelineRange;
@protocol IGVideoTimelineViewInterface;

@protocol IGVideoTimelineViewDelegate <NSObject>
- (void)videoTimelineDidEndScrubbing:(id <IGVideoTimelineViewInterface>)arg1;
- (void)videoTimeline:(id <IGVideoTimelineViewInterface>)arg1 didChangeSelectedRange:(IGVideoTimelineRange *)arg2;
- (void)videoTimeline:(id <IGVideoTimelineViewInterface>)arg1 didScrubPlayheadToProgress:(double)arg2;
- (void)videoTimelineDidBeginScrubbing:(id <IGVideoTimelineViewInterface>)arg1;
- (void)videoTimelineDidGenerateThumbnails:(id <IGVideoTimelineViewInterface>)arg1;
@end

