//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/KFPropertyMutator.h>

@protocol KFMutatorAssetDelegate;

@interface KFBitmapSwapMutator : KFPropertyMutator
{
    id <KFMutatorAssetDelegate> _assetDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <KFMutatorAssetDelegate> assetDelegate;
- (void)mutateDocument:(struct Document *)arg1;
- (id)mutateAsset:(id)arg1;

@end

