//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FBSharedFramework/MBUIContact-Protocol.h>
#import <FBSharedFramework/NSCopying-Protocol.h>

@class NSString;

@interface MBUIGroupMembershipRequestModel : NSObject <MBUIContact, NSCopying>
{
    struct __MCFRuntimeBaseData _reserved;
    long long _threadKey;
    long long _contactId;
    NSString *_subscribeSource;
    NSString *_contactName;
    NSString *_secondaryName;
    int _contactType;
    NSString *_profilePictureUrl;
    NSString *_profilePictureFallbackUrl;
    long long _profilePictureUrlExpirationTimestampMs;
    int _blockedByViewerStatus;
}

- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (unsigned long long)_cfTypeID;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) int blockedByViewerStatus;
@property(readonly, nonatomic) long long profilePictureUrlExpirationTimestampMs;
@property(readonly, copy, nonatomic) NSString *profilePictureFallbackUrl;
@property(readonly, copy, nonatomic) NSString *profilePictureUrl;
@property(readonly, nonatomic) int contactType;
@property(readonly, copy, nonatomic) NSString *secondaryName;
@property(readonly, copy, nonatomic) NSString *contactName;
@property(readonly, copy, nonatomic) NSString *subscribeSource;
@property(readonly, nonatomic) long long contactId;
@property(readonly, nonatomic) long long threadKey;
- (id)capabilities2;
- (int)contactReachabilityStatusTypeInt32;
- (id)messengerCallLogThirdPartyIdString;
- (id)capabilities;
- (id)profileRingColorExpirationTimestampMs;
- (id)profileRingState;
- (id)profileRingColor;
- (_Bool)canViewerMessage;
- (int)contactTypeExactInt32;
- (int)threadType;
- (int)blockedByViewerStatusInt64;
- (long long)secondaryProfilePictureUrlExpirationTimestampMsInt64;
- (id)secondaryProfilePictureFallbackUrlString;
- (id)secondaryProfilePictureUrlString;
- (long long)profilePictureUrlExpirationTimestampMsInt64;
- (id)profilePictureFallbackUrlString;
- (id)profilePictureUrlString;
- (id)firstName;
- (id)nickname;
- (id)name;
- (long long)contactTypeInt64;
- (int)restrictionType;
- (id)contactIdInt64;

// Remaining properties
@property(readonly) Class superclass;

@end

