//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FBSharedFramework/FBAnnouncerBase.h>

#import <FBSharedFramework/SNPlaybackExtendableStateListener-Protocol.h>

@class NSString;

@interface SNPlaybackExtendableStateListenerAnnouncer : FBAnnouncerBase <SNPlaybackExtendableStateListener>
{
}

- (void)playerDidFailPlayback:(id)arg1 error:(id)arg2;
- (void)playerDidChangeStatePlayback:(id)arg1 state:(unsigned long long)arg2;
- (void)playerDidDetectFirstImpression:(id)arg1;
- (void)playerDidFinishPlayback:(id)arg1;
- (void)playerDidStartPlayback:(id)arg1;
- (void)playerIsReadyToPlayback:(id)arg1;
- (void)playerDidStartPreparingPlayback:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

