//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UITapGestureRecognizer;
@protocol UITimingCurveProvider;

@interface UIView (THBounce)
- (void)_th_addBounceAnimation:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_th_triggerHapticIfNeeded;
- (void)_th_setBounceAnimator:(id)arg1;
- (id)_th_bounceAnimator;
- (id)_th_hapticGenerator;
- (void)th_triggerTouchHaptic;
- (void)th_handleTouches:(id)arg1 withType:(long long)arg2;
@property(nonatomic, getter=th_isPressed) _Bool th_pressed;
- (void)th_setPressed:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) id <UITimingCurveProvider> th_timingParametersForBounceScale; // @dynamic th_timingParametersForBounceScale;
@property(nonatomic) __weak UITapGestureRecognizer *th_tapGestureRecognizerForHapticFeedback; // @dynamic th_tapGestureRecognizerForHapticFeedback;
@property(nonatomic) _Bool th_hapticTapEnabled;
@property(nonatomic) double th_bounceDuration;
@property(nonatomic) double th_bounceScale;
@end

